### ISSUE TITLE
On Windows: NameError: name `startup_check` is not defined

### ISSUE THREAD

**Issue by j-mas** [master-of-zen/Av1an#100]
c:\>python ./av1an.py -i c:/Film/1.mkv -o c:/Film/2.mkv
Traceback (most recent call last):
  File "./av1an.py", line 286, in <module>
    main()
  File "./av1an.py", line 279, in main
    Av1an().main_thread()
  File "./av1an.py", line 271, in main_thread
    startup_check()
NameError: name 'startup_check' is not defined

**Comment by master-of-zen** [comment]
@j-mas pip?

**Comment by master-of-zen** [comment]
@j-mas updated pip to latest git, update. :+1:

**Comment by j-mas** [comment]
Av1an 1.10.5.post4 works!!!

Thank you!
