### ISSUE TITLE
2 pass process fails with --rt flag in aomenc video config

### ISSUE THREAD

**Issue by ramanverma-dev** [master-of-zen/Av1an#101]
2 pass encoding always fails after a certain amount of percentage or time when using --rt flag in aomenc video config but it works when i set -p 1 flag. i guess its a piping issue or --rt doesn't support 2 pass encoding yet?

**Comment by master-of-zen** [comment]
`--rt` is real-time mode and it works only when using 1-pass

**Comment by master-of-zen** [comment]
@ramanverma-dev if you don't have more questions please close issue :)

**Comment by ramanverma-dev** [comment]
thank you for clarifying, I was suspicious about it not being able to do to 2 pass encodes yet and also i've been trying to set model path for libvmaf on windows but it is not working and always ends up in path issues for example:

 [Parsed_libvmaf_2 @ 000001f554c7f9c0] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
Input model at av1modelvmaf_v0.6.1.pkl cannot be read successfully.
Caught VmafException: Error loading model (.pkl): Trouble reading the file:av1modelvmaf_v0.6.1.pkl

It is not taking (\) as input but rather as an escape character i guess?
Tried with double quotes (""), single quotes ('') and without any quotes.

model directory is present in both source directory and as well as on an another partition and the parameter i am passing is 
`--vmaf_path="D:\av1\model"`

**Comment by master-of-zen** [comment]
@ramanverma-dev you should give model itself, like that
![Screenshot_20200625_212128](https://user-images.githubusercontent.com/46526140/85776944-d7c86c80-b729-11ea-880b-bc1ee96642e7.jpeg)

**Comment by master-of-zen** [comment]
Try also moving both model and pkl files to folder where you encode

**Comment by ramanverma-dev** [comment]
yep that worked, thanks much appreciated.

I will rename the issue for vmaf_path too.

**Comment by master-of-zen** [comment]
@ramanverma-dev :+1:
