### ISSUE TITLE
--resume broken?

### ISSUE THREAD

**Issue by ramanverma-dev** [master-of-zen/Av1an#103]
My pc suddenly turned off because of power cut and when i try to resume it on windows it starts all over again but the process was already 48% done and it took 13hrs to reach that ;-;.

.temp folder along with csv and log file are available in the root directory of av1an with aom and ffmpeg binaries.

**Comment by master-of-zen** [comment]
@ramanverma-dev check frame count, it different because when you resume you start at 0% but only chunks that left

**Comment by master-of-zen** [comment]
So if you encoded 48% of 1000 frames at resume it will start at 0% and total frame count will be 520

**Comment by ramanverma-dev** [comment]
i see , i'll get back to you in a bit.

**Comment by ramanverma-dev** [comment]
yep it worked, Originally it was processing 157k frames now it is 82k.

Thanks.
