### ISSUE TITLE
[Feature Request] Set video height and width automatically when using SVT-AV1

### ISSUE THREAD

**Issue by nathanielcwm** [master-of-zen/Av1an#12]
Currently, if you do not pass any options while attempting to encode with SVT-AV1 it errors out because the video width and height are not specified.

I think that if it isn't specified it should by default set it to the original height and width of the video.

**Comment by master-of-zen** [comment]
Videos resolution and framerate can be modified before you start encoding, for example with `-vf 'scale=192:108'` option or `-fps` . So adding that for svt-av1 adds more problems than it solves
