### ISSUE TITLE
Error at encode 'tqdm' object has no attribute 'reset'

### ISSUE THREAD

**Issue by cromefire** [master-of-zen/Av1an#123]
I get for (almost?) every segment
```
Error at encode 'tqdm' object has no attribute 'reset'
At line 153
```
And in the end it fails to concatenate.

Ref file: https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_60fps_normal.mp4

## Env
Commandline: `av1an -i "bbb_sunflower_1080p_60fps_normal.mp4" -enc vpx`
OS: Ubuntu 20.04
Python: Python 3.8.2
Installed: Via pip
vp9: WebM Project VP9 Encoder v1.8.2

**Comment by megapro17** [comment]
> Installed: Via pip

Try `python -m pip install --upgrade https://github.com/master-of-zen/Av1an/archive/master.tar.gz`

**Comment by n9Mtq4** [comment]
What version of tqdm are you using? You can get this by running
```
pip list | grep tqdm
```

**Comment by cromefire** [comment]
> What version of tqdm are you using? You can get this by running
> 
> ```
> pip list | grep tqdm
> ```

```
tqdm                    4.30.0
```

**Comment by cromefire** [comment]
I also get this, I'm unsure if those are related:

```
Frame Count Differ for Source 00020.mkv: 6/1170
```

I'll try master once the current run is finished

**Comment by n9Mtq4** [comment]
The most recent version is 4.48.2, you might want to try updating it.

If `pip list --user | grep tqdm` lists tqdm, run `pip install tqdm --user --upgrade`.
Otherwise run `pip install tqdm --upgrade`.

**Comment by master-of-zen** [comment]
@cromefire frame count difference is between source and encoded chunk. As result encoder crashing or stopping before finishing - this warning will pop up.

**Comment by cromefire** [comment]
Yeah makes sense

**Comment by cromefire** [comment]
Well upgrading `tqdm` seemed to work, so you might wanna add a minimum version here: https://github.com/master-of-zen/Av1an/blob/c0fb9fae21fb2b2f8a0953676dda147e651e3211/requirements.txt#L4

**Comment by master-of-zen** [comment]
@cromefire 👍
