### ISSUE TITLE
[feature] Support for SVT-VP9

### ISSUE THREAD

**Issue by cromefire** [master-of-zen/Av1an#124]
Support for [SVT-VP9](https://github.com/OpenVisualCloud/SVT-VP9) would be great, because libvpx is really slow. Already having support for SVT-AV1, I'd think that's probably relatively easy-ish.

**Comment by n9Mtq4** [comment]
I'll look into adding this.

**Comment by cromefire** [comment]
One of the biggest things for me would be the ability to resume and depending on how good it works the improvements for darker scenes

**Comment by master-of-zen** [comment]
Should be a one day thing 🙂

**Comment by master-of-zen** [comment]
@cromefire initial support for svt-vp9 added.
Usage as follow:
`-w -h` and fps parameters required
`av1an.py -i video.mkv -enc svt_vp9 -v " -w 1920 -h 1080 -fps-num 24000 -fps-denom 1001 -enc-mode 4 -rc 0 -q 30  "`
Currently dynamic progress bar doesn't work for family of SVT encoders, so updates will be on chunk finish.

**Comment by master-of-zen** [comment]
@cromefire I will close this issue tomorrow.
SVT-VP9 support added.
