### ISSUE TITLE
--no_check seems not work

### ISSUE THREAD

**Issue by RinaOgata** [master-of-zen/Av1an#127]

**Comment by RinaOgata** [comment]
I add this command but av1an still check the frames before encoding.Here is my command:
"av1an --no_check -i {} -enc x265 -v " {} " -w 10  -a " {} " -ff " {} " -o {}".format( infile,  video_params, audio_params,ffmpeg_params, outfile)

**Comment by master-of-zen** [comment]
`--no-check` disables check that done after chunk is finished.
It needed if framerate of video changes, because otherwise check will print `frame count differ for {Chunk}` and this chunk will not be saved as finished

**Comment by RinaOgata** [comment]
> `--no-check` disables check that done after chunk is finished.
> It needed if framerate of video changes, because otherwise check will print `frame count differ for {Chunk}` and this chunk will not be saved as finished

so if there any way to start encode faster? I mean that the process reading frame before encode is too long...

**Comment by master-of-zen** [comment]
@RinaOgata what your source and full command line? I don't understand full context of issue

**Comment by Felixkruemel** [comment]
@RinaOgata With checking the frames, do you mean the pyscenedetect thing which checks the file for scenes every time you start it?

Instead of doing that you can also let it create a scenes file on the first run with `-s scenes.csv`. If you specify that in the following tasks as well (with the same file of course) it won't re-do the scene detection but will skip directly to the encoding.

**Comment by RinaOgata** [comment]
> @RinaOgata With checking the frames, do you mean the pyscenedetect thing which checks the file for scenes every time you start it?
> 
> Instead of doing that you can also let it create a scenes file on the first run with `-s scenes.csv`. If you specify that in the following tasks as well (with the same file of course) it won't re-do the scene detection but will skip directly to the encoding.

Thanks! It's a good idea!

**Comment by RinaOgata** [comment]
> @RinaOgata what your source and full command line? I don't understand full context of issue

I know how to skip the process creating scene now. @Felixkruemel has sloved my question.
