### ISSUE TITLE
[Feature Request] Encoder FPS

### ISSUE THREAD

**Issue by nathanielcwm** [master-of-zen/Av1an#13]
Currently, it appears like Av1an doesn't display FPS values unlike FFmpeg while encoding I believe that it would be quite useful to display it alongside the progress bar.

**Comment by master-of-zen** [comment]
On linux `-log log_file` can be added to gather all encoders output.
There will be all encoders outputs, settings, frame rates and other stuff 
![20:12:02_30_01_20](https://user-images.githubusercontent.com/46526140/73477420-df632f80-439c-11ea-82e1-0e163446a984.png)
Progress bar made in a way that it need to be redone from scratch and be a lot more complex to support that feature
:)
