### ISSUE TITLE
Av1an generates 2 (or more) extra frames on sources.

### ISSUE THREAD

**Issue by RozeFound** [master-of-zen/Av1an#140]
I've seen this only on Geforce Experience generated videos. 
![ConEmu64_Mvw5tXooGa](https://user-images.githubusercontent.com/68745888/91666484-43aec300-eb27-11ea-814d-b8d8a73a602d.png)

**Comment by master-of-zen** [comment]
@RozeFound can you send video, so I can examine that myself? :blush:

**Comment by master-of-zen** [comment]
Also does video have audio desync after encode is done?
Try using aomenc, which is default encoder

**Comment by RozeFound** [comment]
There are 3 video, source, av1 encoded in ffmpeg, and av1 encoded in Av1an with rav1e encoder. And, yes, audio desync is expectedly. https://drive.google.com/file/d/1A-kRYEu_9nztOsImKNTfavhZ-IpFmLSq/view?usp=sharing
I will try encode video in av1an with default encoder as soon as possible.

**Comment by RozeFound** [comment]
@master-of-zen encoding with aomenc have the same problem. I think problem exactly in Av1an.

**Comment by master-of-zen** [comment]
As works around I recommend use `-s 0` which will disable splitting, and you will encode whole video with single instance of encoder

**Comment by RozeFound** [comment]
But it's much slower than with splitting... You don't know how to fix this? Without -s 0, encode speed is 2.7 frames per second, otherwise it is 1.3 frames per second...

**Comment by n9Mtq4** [comment]
Often there are no new frames being added and instead it is an issue with the expected number of frames. Can you try getting a frame count of the source and the final encoded video with `ffmpeg -i input.mkv -map 0:v:0 -c copy -f null -` and see if they match?

**Comment by RozeFound** [comment]
@n9Mtq4 No, they not match. In source 712 frames,  in encoded 723.

**Comment by master-of-zen** [comment]
@RozeFound does transcoding source to lossless x264 and later using av1an helps?

**Comment by RozeFound** [comment]
@master-of-zen Oh, I'm so sorry. I forgot one very important thing, it's not Geforce Experience generated video, it's video edited in Movavi, and saved in x264. And this video can't be encoded in av1an correctly. Original Geforce Experience generated video can be properly encoded into AV1 using av1an.

**Comment by Fuchs4** [comment]
@RozeFound is it possible that your source has a variable framerate? Av1an decodes with ffmpeg and then pipes to the encoder. Pipes do not support variable framerates and ffmpeg automatically converts to a fixed framerate by dropping and duplicating frames. You can check for variable framerate with `ffmpeg -i source.avi -vsync 1 -f null -`. `-vsync 1` forces a fixed framerate. ffmpeg will print `dup=` and `drop=` in its output if it had to duplicate or drop frames to achieve a fixed framerate.

**Comment by krakow10** [comment]
I run shadowplay recordings through ffmpeg -r 60 -i shadowplay.mp4 -c copy 60fps.mkv to get rid of the variable framerate weirdness that goes all the way through to YouTube and appears as like 55fps if you don't fix it.  I haven't seen audio desync problems when I do that but that is a possible issue with my fix

**Comment by master-of-zen** [comment]
Closing the issue, looks resolved
