### ISSUE TITLE
Fails when a file named "encode" is already present in the current working directory

### ISSUE THREAD

**Issue by 01y** [master-of-zen/Av1an#141]

**Comment by master-of-zen** [comment]
@01y provide full example please

**Comment by master-of-zen** [comment]
Possible reason is that file lacks extension. Medial files should have extensions like '.mkv', '.mp4', if file just named 'encode', it will not open it

**Comment by 01y** [comment]
`$ av1an --input test0.mkv --ff " -vf scale=-1:360 " -o test1.mkv
Traceback (most recent call last):
  File "/usr/bin/av1an", line 33, in <module>
    sys.exit(load_entry_point('Av1an==1.12', 'console_scripts', 'av1an')())
  File "/usr/lib/python3.8/site-packages/av1an.py", line 18, in main
    Av1an().main_thread()
  File "/usr/lib/python3.8/site-packages/av1an.py", line 14, in main_thread
    main_queue(self.args)
  File "/usr/lib/python3.8/site-packages/Av1an/encode.py", line 97, in main_queue
    video_encoding(args)
  File "/usr/lib/python3.8/site-packages/Av1an/encode.py", line 37, in video_encoding
    setup(args.temp, args.resume)
  File "/usr/lib/python3.8/site-packages/Av1an/setup.py", line 142, in setup
    shutil.rmtree(temp)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 26] Text file busy: 'encode'
`

fixed by moving to a new directory

**Comment by master-of-zen** [comment]
That's super weird, what if you remove .temp folder?

**Comment by 01y** [comment]
oh, could be that (.temp/encode)... unrelated to ./encode 

Will try that when I get a chance.

**Comment by 01y** [comment]
Just to follow up, I got another similar error message after completing that encode in a new directory. Output file was created successfully in this case, however, in contrast to the previous attempt.

**Comment by n9Mtq4** [comment]
Do you have full read and write permissions on the directory you are running Av1an in?

**Comment by 01y** [comment]
> Do you have full read and write permissions on the directory you are running Av1an in?

I do.

**Comment by n9Mtq4** [comment]
It looks like a file (`.temp/encode`) was open in another application, so it wasn't able to be deleted when Av1an tries to clear the `.temp` directory on start up. 

Has this issue gone away on its own?

**Comment by master-of-zen** [comment]
@01y I'm closing this issue as it looks that cause was related to other application using folder/file in folder.
If you think that it's other issue, reopen :)
