### ISSUE TITLE
Cannot seem to encode anything

### ISSUE THREAD

**Issue by kozross** [master-of-zen/Av1an#148]
I tried using Av1an as follows, with the results you see here:

```
[koz@Sebastian ~]$ av1an --input test.mp4 --output_file test.mkv --encoder svt_av1
 64%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                     | 12032/18808 [03:21<01:53, 59.73frames/s]
Queue: 17 Workers: 1 Passes: 1
Params: --preset 4 --rc 0 --qp 25
  0%|                                                                                                                                                                     | 0/18808 [00:00<?, ?fr/s]
```

It sat at 0% for ages, doing nothing, eventually stopping all load on my CPU. I probably waited more than half an hour for it to do anything on the second progress bar.

**Comment by master-of-zen** [comment]
@kozross what OS?
Also try using aomenc and smaller file

**Comment by kozross** [comment]
It's on Arch Linux, using the AUR package, on a 5-minute video. I tried using `vpx` to encode a webm - that works, but the framerate it reports on the second stage is like, 3fps.

**Comment by master-of-zen** [comment]
@kozross now Av1an use new SVT-AV1 output parsing, encoding progress should show

**Comment by kozross** [comment]
@master-of-zen Can confirm it shows now. Closing.
