### ISSUE TITLE
Two Pass Encode

### ISSUE THREAD

**Issue by dengelsma** [master-of-zen/Av1an#149]
Great script!

Do I have to run the script twice for a two pass encode?

**Comment by master-of-zen** [comment]
It manages 2-pass encoding for you.
Default passes determined by the encoder.
You can set number of passes explicitly by using `-p 1` or `-p 2`

**Comment by dengelsma** [comment]
Is there any indication in the log files that the second pass is under way? (It's not clear to me that the second pass is actually running). I'm using x265 with the following command line: 

 ./av1an.py -i ./DC_Test.mkv -enc x265 -v ' --vbv-maxrate 1000 --vbv-bufsize 2000 -p slower ' -w 20 --split_method pyscene -a " -c:a copy " --passes 2 --ffmpeg " -vf yadif=1 " --mkvmerge --temp ~/tmp -o ~/test_s1_1Mbps

**Comment by master-of-zen** [comment]
Progress bar updates only on encoding pass.

**Comment by dengelsma** [comment]
Is the first pass split up among workers then (because it takes place pretty fast!)?

**Comment by master-of-zen** [comment]
The first bar that appears is pyscenedetection doing its job, after which paralleled encode starts

**Comment by master-of-zen** [comment]
I would recommend optimizing command a little bit.
`-split_method pyscene -a " -c:a copy "` 
Those are defaults, so they can be removed.

**Comment by dengelsma** [comment]
After PyScene finishes up, is the first pass ran on individual chunks or the complete video file?

**Comment by master-of-zen** [comment]
Also to not redo scenedetection on restart of encoding, I recommend specifying `-s scenes.csv` which will save and reuse scenes after scenedetection has done once

**Comment by master-of-zen** [comment]
Individual chunks

**Comment by dengelsma** [comment]
Got it. Thanks!

**Comment by master-of-zen** [comment]
I will close this issue if there nothing more to ask about.
