### ISSUE TITLE
SynthaxError in python script

### ISSUE THREAD

**Issue by SugoiSheep** [master-of-zen/Av1an#15]
After trying to execute ./av1an.py -i [filename] it spits out a syntax error.
` 
File "./av1an.py", line 22
    self.bar_iteration: int = 0
                      ^
SyntaxError: invalid syntax
`

**Comment by master-of-zen** [comment]
Python3 required

**Comment by SugoiSheep** [comment]
I have python3 installed. maybe a different dependency I am missing?

**Comment by master-of-zen** [comment]
But script in your case executed with Python 2. You can change what Python is default in your environment or call Python3 av1an.py

**Comment by SugoiSheep** [comment]
A yes I see. that fixed it. thanks :^)
