### ISSUE TITLE
Incorrect Frame Count with Yadif=1 Deinterlace

### ISSUE THREAD

**Issue by dengelsma** [master-of-zen/Av1an#150]
When using yadif=1 for deinterlacing in ffmpeg, the frame count doubles as the deinterlacer doubles the frame count... The av1an encode progress bar disappears after reaching 100% of the initial video file frame count.

**Comment by master-of-zen** [comment]
For clear usage of interlaced, I would recommend to first convert your file to lossless x264 and when to feed it to av1an.

**Comment by master-of-zen** [comment]
I will close this issue if there nothing more to ask about.
