### ISSUE TITLE
No audio extracted

### ISSUE THREAD

**Issue by dengelsma** [master-of-zen/Av1an#151]
I've seen this situation a few times on different video files (these are MKV files with MPEG2 video/AC3 audio from DVD rips).

Running this command:

~/Av1an/./av1an.py -i "./XXXXXXXXXXXX.Mkv" -enc x265 -v " --vbv-maxrate 1000 --vbv-bufsize 2000 -p fast " -w 12 --passes 2 --mkvmerge --temp ~/tmp -o ./XXXXXXXXXXXXXXXX

Once pyscene finishes, I get a message in red, presumably from ffmpeg: "Subtitle encoding currently only possible from text to text or bitmap to bitmap" and no audio is extracted (the audio.mkv file has a zero size).

The video encoding begins and, upon completion, the av1an script fails with an error when combining audio and video.

The log after completion of video encoding:

```
10:02:16 Concatenating
10:03:01 mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
Error: The file '/home/dengelsma/tmp/audio.mkv' could not be opened for reading: end of file error.
10:03:01 Concatenation failed, aborting, error:

Complete log file is attached.

[log.log](https://github.com/master-of-zen/Av1an/files/5239640/log.log)

```

**Comment by dengelsma** [comment]
If I change the ffmpeg command in ffmpeg.py to use an alternate form of extracting the audio, av1an works just fine.

**Comment by master-of-zen** [comment]
@dengelsma What changes you did?

**Comment by dengelsma** [comment]
I changed the lines in the extract_audio function (in ffmpeg.py) to the following:

        cmd = ('ffmpeg', '-y', '-hide_banner', '-loglevel', 'error', '-i', input_vid.as_posix(),
               '-vn', *audio_params, audio_file.as_posix())
