### ISSUE TITLE
Install failed due to absence of progress_bar

### ISSUE THREAD

**Issue by henrypijames** [master-of-zen/Av1an#153]
For a project aimed to make AV1 encoding accessible to the average user, the very first step - installing av1an - is nightmarishly difficult. I say this with highest respect for that goal and the effort to achieve it.

The Install section of `README.md` doesn't specify where to find AOMEnc binary (or is the average user indeed expected to compile it himself?!), nor where to put the ffmpeg binaries.

But worst of all, install of av1an itself simply fails - both via PyPI and `setup.py`. The error is the same:

```
scenedetect 0.5.4.1 does not provide the extra 'progress_bar'
```

I really don't think the average user can be expected to find his way through this much fragile complexity to arrive at a working installation. And I've been a sysadmin (Windows and Linux), Python developer, and casual video encoder for more than 20 years.

**Comment by lastrosade** [comment]
aomenc and ffmpeg are both present in most if not all big distributions package repositories.
If you are on windows and fail to find aomenc

You may try the first result when searching for aomenc
[https://ci.appveyor.com/project/marcomsousa/build-aom/history](https://ci.appveyor.com/project/marcomsousa/build-aom/history)

Or my own windows builds
[https://jeremylee.sh/bin.html](https://jeremylee.sh/bin.html)

Concerning the pip problem, I can't get this error both on archlinux and windows via `pip install av1an` it just installs fine.

Av1an was not really developed with the "Average User" in mind (as the "Average User" rarely takes interest in arcane encoding methods for a bleeding edge video codec), but its true that it could use some polishing.

**Comment by lastrosade** [comment]
aomenc and ffmpeg are both present in most if not all big distributions package repositories.

If you are on windows and fail to find aomenc, you may try the first result when searching for aomenc:
[https://ci.appveyor.com/project/marcomsousa/build-aom/build/artifacts](https://ci.appveyor.com/project/marcomsousa/build-aom/build/artifacts)
Or try my own windows builds:
[https://jeremylee.sh/bin.html](https://jeremylee.sh/bin.html)

Concerning the pip problem, I can't get this error both on archlinux and windows via `pip install av1an` it just installs fine.

Av1an was not really developed with the "Average User" in mind (as the "Average User" rarely takes interest in arcane encoding methods for a bleeding edge video codec), but its true that it could use some polishing.

**Comment by henrypijames** [comment]
Sorry, I should have specified: I'm on Windows 10 x86-64 (latest) and Python 3.8 x86-64.

I think I will wait until the AOM codec gets native multithreading support - preferably when that finds its way into ffmpeg. Until then, the quality tradeoff of libsvtav1 is worth saving me all those endless debugging.

**Comment by henrypijames** [comment]
> Concerning the pip problem, I can't get this error both on archlinux and windows via `pip install av1an` it just installs fine.

Perhaps you have an existing, older version of scenedetect that works, whereas the latest version no longer has `progress_bar`?

**Comment by master-of-zen** [comment]
Progress_bar is now a requirement for PyScenedetect.
I removed optional requirement, please try installing from pip again

**Comment by RozeFound** [comment]
Aomenc and much more may be found here: [Custom ffmpeg windows builds](https://jeremylee.sh/bin.html)
Link to it, and to Av1an I was found here: [HAV1T](https://hav1t.com/)
If it anyone still interesting.

**Comment by master-of-zen** [comment]
Closing
