### ISSUE TITLE
Cannot encode raw YUV files

### ISSUE THREAD

**Issue by adamjw24** [master-of-zen/Av1an#155]
It seems there is not possibility for av1an to encode raw YUV files.
The following call
`PATH=$PATH:/path/to/projects/aom/build_dir/ av1an -i /path_to_yuv/file_2160p60_420_10bit.yuv -fmt yuv420p10le`
produces an error:
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(av1an:190329): Gdk-CRITICAL **: 11:37:53.905: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[IMGUTILS @ 0x7ffc4124fc40] Picture size 0x0 is invalid
Error in PySceneDetectOpenCV VideoCapture object failed to return True when calling isOpened().
```
Im ignoring the X-server problems, but it seems neither avian nor ffmpeg can infer the picture size (see second last output line), which indeed needs to be specified explicitly for raw YUV files.

Is there a way to do it?

**Comment by n9Mtq4** [comment]
Raw YUV files have no height and width information, so pyscenedetect cannot read it and ffmpeg and the encoders needs that information specified manually.

1. You will need to tell ffmpeg the frame size and framerate with `-ff " -s 3840x2160 -r 60 "`.
2. You will need to use aom_keyframes for the scene detection. Add `--split_method aom_keyframes`.
3. You will need to tell aomenc the frame size and framerate with `-v " --fps=60 --width=3840 --height=2160 "`.
