### ISSUE TITLE
[Feature request] Nvenc support

### ISSUE THREAD

**Issue by RozeFound** [master-of-zen/Av1an#156]
I think nvenc support for x264 and x265 may be very useful.

**Comment by master-of-zen** [comment]
What is the incentive for that?

**Comment by RozeFound** [comment]
What do you mean?

**Comment by RozeFound** [comment]
I'm bad in english, and can't fully understand your question

**Comment by master-of-zen** [comment]
For what reason it should be added?
Both x264 and x265 software encoders are fast and vastly superior to Nvenc

**Comment by RozeFound** [comment]
Encode in parallel one video into av1 and x264 without loss performance. Very, very useful for encoding content for sites, when I use one video in three codecs, for show it by browser abilities. AV1 for chrome, HEVC(x265) for Safari, and x264 for others.

**Comment by master-of-zen** [comment]
Nvenc is just Nvidia hardware encoder of H.264 and HEVC, it's worse in terms of efficiency compared to software implementations

**Comment by RozeFound** [comment]
Maybe, but encode two videos in one time on CPU and GPU, is more efficient than the same videos on CPU but in turns.

**Comment by n9Mtq4** [comment]
What features would Av1an bring to nvenc that isn't in ffmpeg or handbrake? Nvenc is already very fast and most GPUs are limited to 2 or 3 videos at the same time, so chunked encoding makes no sense.

**Comment by RozeFound** [comment]
Oh, I don't know... Comfortable interface?

**Comment by nathanielcwm** [comment]
You can just use ffmpef

**Comment by RozeFound** [comment]
Um, ok.
