### ISSUE TITLE
Encoder encountered an error: 3221225477

### ISSUE THREAD

**Issue by RozeFound** [master-of-zen/Av1an#157]
![image](https://user-images.githubusercontent.com/68745888/94812593-240a0380-0421-11eb-9f06-573b8c236989.png)

[convertAllFolderToAV1.py](https://pastebin.com/3w4yk0px)

**Comment by master-of-zen** [comment]
`libupus` this should not be here)
Also, there should be no Cyrillic in the path

**Comment by RozeFound** [comment]
**libupus** its the new over9000% compression audio codec, you don't hear about that? :D 
Little fault while editing .py file before send to you. On the screenshot command is correct.
I will try to remove Cyrillic in the path a bit later, and close the issue if all will work fine.

**Comment by RozeFound** [comment]
@master-of-zen You don't planning add a bit more straightforward way to call av1an from python?

**Comment by RozeFound** [comment]
Removing Cyrillic from path doesn't help.

**Comment by master-of-zen** [comment]
@RozeFound this is FFmpeg error, try using the newest FFmpeg

**Comment by RozeFound** [comment]
I tried it. Doesn't help. I can send problematic video, you will check what's the problem.

**Comment by master-of-zen** [comment]
@RozeFound does `ffmpeg -i file -f null - ` decodes whole file normally?

**Comment by RozeFound** [comment]
Um idk... How do I know this? Process was ended without any errors.

**Comment by master-of-zen** [comment]
I send you the command above, run it on your file, it will decode whole file and if there is decoding error, it will pop up in console

**Comment by RozeFound** [comment]
> Process was ended without any errors.

**Comment by master-of-zen** [comment]
@RozeFound This is ffmpeg error.
http://trac.ffmpeg.org/ticket/8698
Closing for now as it's third party bug

**Comment by dexeonify** [comment]
@master-of-zen Weird that it's a ffmpeg error considering `aomenc.exe` is the one that crashed.
@RozeFound I suggest setting up and use `vs_ffms2` as the chunk method, it *might* fix the issue.
