### ISSUE TITLE
missing scenes

### ISSUE THREAD

**Issue by iRed4321** [master-of-zen/Av1an#16]
`Traceback (most recent call last):`
  `File "./av1an.py", line 512, in <module>`
    `av1an.main()`
  `File "./av1an.py", line 476, in main`
    `self.split_video(self.args.file_path)`
  `File "./av1an.py", line 266, in split_video`
    `stamps = self.read_csv(file_path)`
  `File "./av1an.py", line 237, in read_csv`
   ` with open(file_path) as csv_file:`
`FileNotFoundError: [Errno 2] No such file or directory: '/[...]/av1tests/Av1an/.temp/../test-Scenes.csv'`

This is the first run so I don't have any test-Scenes.csv...

**Comment by master-of-zen** [comment]
check is there spaces in path, there shouldn't be any

**Comment by iRed4321** [comment]
Ok, it's me, I used sudo but without it's working, sorry
