### ISSUE TITLE
Do scene analysis ahead of time

### ISSUE THREAD

**Issue by kozross** [master-of-zen/Av1an#160]
My pipeline involves transcoding the same video into different resolutions, which means I have to pay the scene detection overhead N times, where N is the number of resolutions that I want. This is suboptimal, considering that the videos I'm interested in targeting take nearly 50 minutes to run scene detection on.

Is it possible to do scene detection once, and then re-use it for each resolution I want to transcode into?

**Comment by master-of-zen** [comment]
With `-s file.csv`, it will save scene detection informantion

**Comment by kozross** [comment]
@master-of-zen Thanks! How do I then give this information to future transcodes?

**Comment by master-of-zen** [comment]
Just let them have the same `-s file.csv`, by including it for in commands. (Don't forget to give different sources different scene files)
If `file.csv` doesn't exist, it will create one after running scene detection.
If `file.csv` exists -  it will reuse it.

**Comment by kozross** [comment]
Great, thanks!
