### ISSUE TITLE
How to pass encoder options?

### ISSUE THREAD

**Issue by kozross** [master-of-zen/Av1an#162]
Is there a way to pass ffmpeg options to the encoding step, such as `-qp` or `-preset` for `x265`?

**Comment by master-of-zen** [comment]
Av1an use x265 encoder directly, all encoder options go to `-v` so the proper way to use that would be ` -v " -p slow --crf 20 "`
More here https://github.com/master-of-zen/Av1an#usage

**Comment by kozross** [comment]
I tried the following (using ``--force`` to dodge #159 ), but get errors every time:

```
av1an -s scenes.csv --input /home/koz/streaming/p4g/raws/2020-10-03_10-00-29.mkv --output_file test --encoder x265 --force --workers 11 -v " -p 0 -qp 20 "
```

**Comment by n9Mtq4** [comment]
Instead of `-v " -p 0 -qp 20 "` it should be `-v " -p 0 -q 20 "` or `-v " -p 0 --qp 20 "`.

You can see all the x265 command line options here https://x265.readthedocs.io/en/master/cli.html .

**Comment by kozross** [comment]
@n9Mtq4 Can confirm this worked. Thanks!
