### ISSUE TITLE
Surprisingly slow behaviour for x265

### ISSUE THREAD

**Issue by kozross** [master-of-zen/Av1an#166]
If I use x265 via ffmpeg on the same present and qp, I can easily get 120fps transcodes, but with `av1an`, even with 11 workers, I only get 30 or so. I suspect this is due to overly-aggressive scene splitting (I end up with 136 scenes for about 180 minutes of footage). Is there a way I can determine what causes this?

**Comment by BlueSwordM** [comment]
What preset are you specifying with ffmpeg and with av1an?

**Comment by kozross** [comment]
Exact ``ffmpeg`` command:

```
ffmpeg -i input.mkv -qp 20 -g 240 -c:v libx265 -preset ultrafast -c:a libopus -b:a 128K output.mkv
```

Exact ``av1an`` command:

```
av1an -s scenes.csv --input input.mkv --output_file output --encoder x265 --force --workers 11 -v " -p 0 -q 20 "
```

**Comment by master-of-zen** [comment]
@kozross Hybrid approach to how encoding is handled is I/O heavy, so it's primary I/O limited.
On slow preset on 3970x, I manage to get 2X fps difference in comparison to FFmpeg on 1080p footage.(Av1an 45 vs FFmpeg 20)
Also, keep in mind that x265 spawns a thread pool equal to thread count, so by using 11 workers you spawn a huge amount of threads. So better keep under 4 workers for less than 64 core systems.

> I suspect this is due to overly-aggressive scene splitting (I end up with 136 scenes for about 180 minutes of footage)
It has nothing to do with scene splitting or how aggressive it is.
For 180 minutes it's normal to have 1000-1500 scenes. Probably it's not aggressive enough.
For accurate determination of where it's beneficial to cut for parallel encoding use aom_keyframes scene detection method

**Comment by kozross** [comment]
@master-of-zen So you suggest using `aom_keyframes` for scene detection and 4 workers? Let me try that and see how I go.

**Comment by master-of-zen** [comment]
The number of workers depends on your system capabilities.
Also using slow preset will show real difference.

**Comment by kozross** [comment]
@master-of-zen I have 6 cores, 12 hyperthreads.

**Comment by master-of-zen** [comment]
1-2 workers more than enough.

**Comment by kozross** [comment]
OK, thanks. Is there some kind of formula for this? Does it vary by encoder?

**Comment by luigi311** [comment]
@kozross yes it varies by encoder. If you do not set the workers manually it will handle it automatically based on your available threads or ram

**Comment by kozross** [comment]
@luigi311 OK, I'll try not setting anything for workers, then.

**Comment by master-of-zen** [comment]
@kozross Make sure you have the latest aomenc. It should be 0.5-1.0x of real-time

**Comment by luigi311** [comment]
Multi threaded single pass is not on version 2.0 I think so you have to get a build that was built from main

**Comment by kozross** [comment]
@luigi311 I'm on 2.0, so that confirms it. May try today, see how I go.

**Comment by master-of-zen** [comment]
@kozross close issue?
