### ISSUE TITLE
aom_keyframe scenedetection commanline generation broken?

### ISSUE THREAD

**Issue by adworacz** [master-of-zen/Av1an#169]
Since Pyscenedetect appears broken on my source (see [this issue](https://github.com/Breakthrough/PySceneDetect/issues/186)), I tried running av1an with aom_keyframes as the splitting mechanism.

It seemed to be using only one core, running very slowly, and the commandline being generated looks like it's got extra spaces in it. I noticed that the broken commandline includes the threading options, which would explain why I'm only using one core.

![2020-10-04_22:50:04_maim](https://user-images.githubusercontent.com/561689/95045390-cbdc3700-0696-11eb-86a3-b6e01602f295.png)

**Comment by master-of-zen** [comment]
Fixed https://github.com/master-of-zen/Av1an/commit/3863c0a8226d48993b457213f71477c5e2415ee9
Please update to the latest PIP

**Comment by adworacz** [comment]
Looks like that fixed the command as fed to aomenc. Unfortunately, it's still running slower than molasses, and doesn't seem to be using 32 threads at all, even though they are specified.

I expect this is a function of aomenc, and not a problem with av1an:

![2020-10-05_08:58:07_maim](https://user-images.githubusercontent.com/561689/95102980-e808c400-06e8-11eb-8bcc-805cd29e720e.png)

Mostly making this comment for awareness, in case there is a known fix.

If not, I think you can close this issue.

**Comment by BlueSwordM** [comment]
What AOM build are you using?

**Comment by adworacz** [comment]
```
~ >>> pacman -Qi aom
Name            : aom
Version         : 2.0.0-1
Description     : Alliance for Open Media video codec
Architecture    : x86_64
URL             : https://aomedia.org/
Licenses        : BSD  custom:PATENTS
Groups          : None
Provides        : libaom.so=2-64
Depends On      : gcc-libs
Optional Deps   : None
Required By     : ffmpeg  python-av1an-git  qencoder
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 11.71 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Wed 20 May 2020 06:52:05 AM PDT
Install Date    : Sun 19 Jul 2020 12:08:32 PM PDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by BlueSwordM** [comment]
Yeah, you should really compile/install the latest aom master.

The difference in speed, especially in the 1st pass, is very large(except for CPU-0).

**Comment by adworacz** [comment]
Good to know - running a quick `yay -Sa aom-git` right now, will let you know how it turns out.

**Comment by adworacz** [comment]
You're right it is quite a bit faster. I hope that PyScenedetect fixes their bug so I can use them instead, since they're faster still, but this gets me into a more acceptable range (down from 4+ hours to ~1 hour) for scenedetection.

I wonder if we could improve that by downscaling the content before feeding it to aomenc, just like PyScenedetect does?

Regardless, this issue has been resolved.

**Comment by seighail3** [comment]
> You're right it is quite a bit faster. I hope that PyScenedetect fixes their bug so I can use them instead, since they're faster still, but this gets me into a more acceptable range (down from 4+ hours to ~1 hour) for scenedetection.
> 
> I wonder if we could improve that by downscaling the content before feeding it to aomenc, just like PyScenedetect does?
> 
> Regardless, this issue has been resolved.

compile our own ?

**Comment by adworacz** [comment]
> > You're right it is quite a bit faster. I hope that PyScenedetect fixes their bug so I can use them instead, since they're faster still, but this gets me into a more acceptable range (down from 4+ hours to ~1 hour) for scenedetection.
> > I wonder if we could improve that by downscaling the content before feeding it to aomenc, just like PyScenedetect does?
> > Regardless, this issue has been resolved.
> 
> compile our own ?

I'm afraid I don't understand your question. Compile what and why do it our own?

**Comment by adworacz** [comment]
Since I got aomenc speed ups by compiling the latest version, and I finally got pyscenedetect working with my source by extracting out the video track (thanks to the pyscenedetect dev who helped me figure this out), I’m going to resolve this issue for now. 

Feel free to reopen if it’s worth tracking the resize + aomenc keyframe first pass approach I called out above. I tested it locally and aomenc appeared to fail completely for some reason.

**Comment by master-of-zen** [comment]
@adworacz The problem with resizing video for aomenc keyframes is that it makes different decisions based on resolution.
The general rule is that lower resolutions result in more keyframes.
Also because of decent multithreading, substantial speed difference occurs only at <480p resolution, which results in a substantial amount of additional scenes.
