### ISSUE TITLE
[Feature Request] Vapoursynth Input Support

### ISSUE THREAD

**Issue by adworacz** [master-of-zen/Av1an#173]
A lot of the pieces to get this working are already there, with the biggest obstacle being PySceneDetect support (although I have an idea to solve that one that I want to try out). An obvious workaround would be to just use aomenc keyframes instead, but I much prefer the speed of PySceneDetect.

There's a good chance that I'll implement this myself, as I'm working in a similar space already, but I figured I should open this issue to track support, and collect any pertinent conversation.

**Comment by adworacz** [comment]
Success!

In short - by using a named pipe, feeding vspipe to it, and then reading said named pipe using `scenedetect` (making sure to specify the duration in frames using `-d`), you can definitely feed PySceneDetect using a vapoursynth script.

![2020-10-09_17:49:13_maim](https://user-images.githubusercontent.com/561689/95641535-cfd1d580-0a57-11eb-8133-73a654641f54.png)

**Comment by Felixkruemel** [comment]
@adworacz You can open a PullRequest once you are finished.
Would be great to have that support available for everyone

**Comment by adworacz** [comment]
Yup, that’s exactly my plan. I need to finish analyzing everywhere that needs an update, but it’s looking like not too much work considering how a pipe is already used to feed most operations. So we’d end up using vspipe instead of ffmpeg, but the encoders wouldn’t even know the difference. 

The only ‘gotcha’ that I can see being an issue is that python’s `os.mkfifo` is apparently only supported on Unix, so Windows support for Pyscenedetect + Vapoursynth won’t work immediately. 

I think we can ship a v1 that uses this, and then look for an alternative that’s exclusive to Windows.

**Comment by adworacz** [comment]
As Github already noted - I made an official feature request on Pyscenedetect to support input via pipe/stdin. If native support is added, then we can skip the use of named pipes (and the Windows issues I called out above) altogether.

**Comment by adworacz** [comment]
:grin: 

![2020-10-11_09:39:46_maim](https://user-images.githubusercontent.com/561689/95684308-98713f00-0ba5-11eb-9c80-f346a54af62f.png)

It should be noted that scenedetection is not working yet in this example. This was a quick hack to get me off the ground. Basically, my script just does a crop of input with scenes I already generated with av1an and saved. So I'm reusing those scenes, passing them in, specifying the vs_ffms2 chunk method (which I modified), and after some additional code to use vspipe instead of ffmpeg when the input is detected as a vpy/py script, we're off to the races with a basic encode.

**Comment by adworacz** [comment]
Okay, got scenedetection working with pyscenedetect.

Also fixed it so that the user doesn't need to specify the chunking method to be "vs_ffms2" in order to run with Vapoursynth scripts.

In short, I have something that works end to end now, but has a few caveats:
1. Windows support doesn't work. If Pyscenedetect can add pipe support for us, this becomes a nonissue and is easy to fix (no more need for a named pipe).
1. The Pyscenedetect progress bar doesn't work when reading from a pipe. Seems to be its bug, not ours, as the same thing happens when using the CLI and reading from a named pipe that I setup in my terminal.
1. aom chunking doesn't work yet, but should be an easy fix.
1. Likely want to add vspipe parameter passing, just like ffmpeg pipe commands. Maybe even reuse the same flag... But, I can definitely imagine a usecase where passing two different sets of args to pipe will be useful - example: pass flag to vspipe when feeding to pyscenedetect to disable all filtering for maximum scenedetection speed, and then pass flag to vspipe to configure args during encoding. The most likely used flag for vspipe will be `--arg` for the purposes already mentioned.

Proof it's working now:
![2020-10-11_15:22:54_maim](https://user-images.githubusercontent.com/561689/95691747-4dbbeb00-0bd6-11eb-87a8-a78f4da28241.png)

**Comment by adworacz** [comment]
For those curious - here's my development branch with the associated changes:
https://github.com/adworacz/Av1an/tree/vapoursynth

I'm not going to do a pull request just yet, as I want to do a little code cleanup first, rebase off the latest changes in mainline, etc.

**Comment by adworacz** [comment]
Pull request is up! There's still some improvements that can be made after this is merged, but I didn't want the changes to get too overwhelming, which is why I called this "Part 1", with other improvements to come. See my commit message for a list.

**Comment by adworacz** [comment]
Soooo funny thing is - I found a bug in what appears to be Vapoursynth as part of this work. I'm putting together all of the evidence for it right now, but it looks like it has some issues when selecting frame ranges in certain cases.

**Comment by adworacz** [comment]
Looks like the bug was actually in the FFMS2 source plugin for Vapoursynth. Using L-SMASH is proving much more reliable, at least for this source. It might be worth adding (I can do it easily, if the team's cool with it) to Av1an as an option/alternative to the `vs_ffms2` chunking method - essentially `vs_lsmash`.

**Comment by wwww-wwww** [comment]
I've already prepared adding vs_lsmash, but i'm waiting for your pr to go through lol

**Comment by Breakthrough** [comment]
Hey @adworacz;

A few questions for you:

1. Do you need to specify the duration because the stream is never ending?  Or is it because OpenCV cannot find the duration of the named pipe?
2. In your example, does it actually output the entire video to the file, or does the file act like a stream/pipe itself?

I'd love to support this, but currently am using OpenCV under the hood is why I ask.  There doesn't seem to be a way to allow passing video data into the OpenCV VideoCapture API at a high level, but I can do some investigation to see if there's a painless way to perhaps modify the internals of it.  My concern is that this might drive a fundamental change to PySceneDetect for how video I/O is done to use a lower level library directly like ffmpeg.  I'm willing to support that change, I just can't commit to any specific times for when I would be able to do it unfortunately.

Also good catch with the progress bar - that definitely is a bug, looks like I assume I know the video length.  I need to allow a mode for when the video length is unknown to avoid that issue.  Do you think that's related to my first question?

Thanks!

**Comment by adworacz** [comment]
I'll answer your questions on the PyScenedetect thread, since it seems more appropriate and prevents spamming this closed issue.
