### ISSUE TITLE
[feature request] switch to have av1an encode chunks in order rather than longest first

### ISSUE THREAD

**Issue by plonk264** [master-of-zen/Av1an#177]
even tho this could lead to a situation where an av1an worker is left encoding a long chunk at the end, being able to encode chunks in order would be nice feature to have.

target use: so i can more easily search thru logs to find and hand (re)encode a chunk that's not achieving the quality i'm wanting (e.g. a random scene that's overly denoised _because aomenc_) after finishing an encode with --keep

**Comment by master-of-zen** [comment]
@plonk264 If you want to reencode chunks:  
1. get chunk number 
2. remove that chunk from done.json in temp folder
3. resume with new settings
(recommend to use --keep)

**Comment by plonk264** [comment]
you can't conveniently browse thru the chunks sequentially in the log, though, if it's in the current chunk encode order

**Comment by master-of-zen** [comment]
use search function to find chunk you need

**Comment by plonk264** [comment]
i don't really want to search the entire log for every chunk

**Comment by master-of-zen** [comment]
@plonk264 to redo chunk, you can remove it from `done.json` and resume encoding without target quality, and with desired CQ level settings.

I close it for now :+1:
