### ISSUE TITLE
Target VMAF produces results with much lower vmaf score than expected

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#183]
`av1an --force -i "$TargetFileWithoutExt.nut" -enc aom -v " --cpu-used=3 --end-usage=q --cq-level=35 --tile-columns=1 --tile-rows=0 -b 10 --lag-in-frames=28 --enable-chroma-deltaq=1 --threads=4 --enable-keyframe-filtering=0 --enable-cdef=0 --enable-fwd-kf=1 --enable-palette=0 --tune=ssim --enable-qm=1 " --vmaf_target 94 --vmaf_steps 5 --min_q 15 --max_q 45 --vmaf_path "../vmaf_v0.6.1.pkl" -w 16 -p 2 -s "$TargetFileWithoutExt.csv" --output_file "$TargetFileWithoutExt.ENC.mkv" -log "$TargetFileWithoutExt.log" --temp "$TargetFileWithoutExt.tmp" -fmt yuv420p10le --n_threads 6 --vmaf_res "1280x720" --vmaf_plots --extra_split 220`

Using this command targeting a vmaf score of 92, av1an successfully finds the cq values to use as we can see in the logs:
```
11:31:03 Chunk: 00050, Fr: 220
Q: [30, 37, 45]
Vmaf: [94.68, 91.76, 87.32]
Target Q: 36 Vmaf: 92.032

11:31:06 Chunk: 00067, Fr: 220
Q: [30, 40, 45]
Vmaf: [95.79, 91.81, 88.4]
Target Q: 39 Vmaf: 92.017

11:31:07 Chunk: 00056, Fr: 220
Q: [30, 34, 45]
Vmaf: [93.84, 92.07, 85.06]
Target Q: 34 Vmaf: 91.928
```

But the resulting encoded chunks vastly undershoot the targeted vmaf score with a mean score of 86

```json
    {
      "frameNum":14300,
      "metrics":{
        "adm2":0.96441,
        "motion2":2.1258,
        "vif_scale0":0.78262,
        "vif_scale1":0.90263,
        "vif_scale2":0.93679,
        "vif_scale3":0.95617,
        "vmaf":85.95289
      }
    },
    {
      "frameNum":14301,
      "metrics":{
        "adm2":0.96877,
        "motion2":2.08694,
        "vif_scale0":0.79244,
        "vif_scale1":0.91761,
        "vif_scale2":0.9495400000000001,
        "vif_scale3":0.96648,
        "vmaf":88.21199
      }
    }
```

![vid](https://user-images.githubusercontent.com/20532320/96818772-658b3e80-1422-11eb-832a-0074f66eab1b.png)

**Comment by master-of-zen** [comment]
Target VMAF don't use user commands for CQ search, (all kind of tunes and expensive settings, aka tune vmaf, high bit depth, which can make process of search N times slower, etc) and makes probes with default settings, like `aomenc -i file --threads=8 --cq-level=N --end-usage=q.
If user provided settings that reduce encoding efficiency, for aomenc it can be " --tune ssim, --enable-cdef=0 ", results will vary negatively

**Comment by master-of-zen** [comment]
Also I would recommend to use default vmaf calculation resolution (1920x1080) with default model, even with sources that are 720p

**Comment by lastrosade** [comment]
> results will vary negatively
Right now the results are very negative, Shouldn't the probe test with the same parameters as the final encode ?

If I target a certain vmaf score with a set of parameters, then that's what I would like to get.

**Comment by luigi311** [comment]
@lastrosade 
I believe it is already using your encoding parameters for probing. Should be relatively simple to check, just add a flag that affect the encoding efficiency massively negative and see what Q it chooses and then run it with defaults and see if the Q varied. 

You can test with 
```
--min-partition-size=128
```

**Comment by lastrosade** [comment]
@luigi311 The parameters for target vmaf look hardcoded: 

https://github.com/master-of-zen/Av1an/blob/385943895032abc727c1a6deb8948f9d2800952f/VMAF/target_vmaf.py#L55

**Comment by luigi311** [comment]
Your right looking at that snippet the parameters are indeed hard coded. This should be changed

**Comment by lastrosade** [comment]
The parameters should be either:

1. The ones specified by the user.
2. The ones specified by the user with a boolean flag (--vmaf_disable_defaults, True meaning use -v parameters, False means use default hard-coded parameters)
3. Specify target vmaf parameters through a string flag (--vmaf_params) this would allow us to tweak some settings like speed, the absence of this flag would make av1an use the default hard-coded parameters.

I'd say 3.

**Comment by master-of-zen** [comment]
@lastrosade Fixed in https://github.com/master-of-zen/Av1an/commit/7af8e0e7e10dcbca8bf9df9ee8d227ca206fcd2c

**Comment by luigi311** [comment]
Looks like you just changed from percentage to standard deviation on the vmaf calculations, the issue we discovered is that target vmaf doesnt take into account the video encoding parameters we are using so the vmaf target is off from the final output

**Comment by n9Mtq4** [comment]
That is by design. Target vmaf is a feature to keep the vmaf roughly consistent across the entire encode, not necessarily be exactly the target you give. We use hard coded parameters to get an idea of what cq is needed as fast as possible. If we were to use the same parameters for target vmaf as the actual encode, it would take too long.

**Comment by luigi311** [comment]
Thats why @lastrosade suggested either a boolean that makes it use the video parameters or a flag that lets you specify which parameters to use. The default will still be to use the hard coded parameters.

**Comment by master-of-zen** [comment]
@lastrosade If issue is fixed - close.f If some features are required - open feature request

**Comment by lastrosade** [comment]
Ok, this is indeed fixed, its fucking great.
