### ISSUE TITLE
[Feature Request] Detect pix_fmt from input

### ISSUE THREAD

**Issue by adworacz** [master-of-zen/Av1an#186]
Opening this tracking purposes, I'll likely implement this myself when I get some spare time.

Effectively, we can detect the pix_fmt from an input video using ffmpeg or vspipe (Vapoursynth). I've tested this locally (not Python code, manual terminal commands), so the concept is there. 

Examples using ffprobe (bundled with ffmpeg) and vspipe, respectively:
```
/pwd >>> ffprobe -hide_banner -select_streams v:0 -show_entries stream=pix_fmt -loglevel error -of flat -i file.mkv
streams.stream.0.pix_fmt="yuv420p"
/pwd >>>
```

```
/pwd >>> vspipe --info script.vpy -
Width: 1920
Height: 1080
Frames: 218981
FPS: 24000/1001 (23.976 fps)
Format Name: YUV420P8
Color Family: YUV
Alpha: No
Sample Type: Integer
Bits: 8
SubSampling W: 1
SubSampling H: 1
```

Note that vspipe/Vapoursynth uses a different naming schema (look at `Format Name`), so some mapping/translation will be required.

But we can run these commands on either the file or script inputs, enabling automatic detection. We can still support the pix_fmt parameter if a user wants to override for some reason...

**Comment by master-of-zen** [comment]
@adworacz changing default pixel format to `+` will match original, it might backfire on videos that don't use yuv4mpeg

**Comment by adworacz** [comment]
Huh. Good to know. 

At the same time, doesn’t everything that uses pix_fmt use yuv4mpeg? I’m away from the code right now, but I could have worn this was the case for the FFMPEG pipe.

**Comment by master-of-zen** [comment]
Yep, there is no other way around it as I know, and currently so all videos are converted to yuv420p10le, which should cover majority of cases

**Comment by adworacz** [comment]
Resolving this issue, since the new default should handle most cases, as master-of-zen calls out.

Reference: https://github.com/master-of-zen/Av1an/commit/ab4bfd96b4cda65583d02fe0ab14f4d5535c2519
