### ISSUE TITLE
FFmpeg concat fails in Windows 10

### ISSUE THREAD

**Issue by Thomasedv** [master-of-zen/Av1an#196]
Using latest PyPI version (4.2)

FFmpeg fails to concat files as it can't handle absolute files on windows for some reason. ([See this link](https://superuser.com/questions/718027/ffmpeg-concat-doesnt-work-with-absolute-path))

Relevant error, notice the path is says it can't handle:

> C:\Users\user\PyCharmProjects\Project
> [concat @ 000001d70469abc0] Impossible to open '.e5393d3a/C:\Users\user\PyCharmProjects\Project\\.e5393d3a\encode\00000.ivf'
> .e5393d3a/concat: Invalid argument
> 
> Concatenation failed, error
> At line: 27
> Error:
> 

I manually changed this line

https://github.com/master-of-zen/Av1an/blob/ba0c7e7a0cc04295c911d2512f9ede86de7a098a/Av1an/concat.py#L68

into the following:

    f.writelines(f'file {shlex.quote(str(file.relative_to(temp)))}\n' for file in encode_files)

It worked for me. Not sure how other platforms handle that change, but this may let you drop using the safe 0 flag in ffmpeg too. I just started using Av1an, but it's not the first time i've encountered this issue with ffmpeg. I assume my change could work, since all the files should have a possible relative path to temp.(because they are inside temp after all) However, since I'm new to this, I have no idea if this will break anything else.

(Perhaps `.relative_to('.')`) would be more correct?

**Comment by master-of-zen** [comment]
@Thomasedv Thanks for your report.
Problem with relative paths that they create problem if user specify different disk as temp folder location, so using absolute path is preferable.
Error caused by insertion of temp folder name before file path and I'm not sure what cause that. My daily runner is unix based and I never had this problem.

**Comment by Thomasedv** [comment]
It's definitely seems like a long standing bug in ffmpeg. I can verify that the paths in the concat file that ffmpeg reads are correct and normal looking full paths, however ffmpeg still assumes them to be relative path. This leads to the combination of the path of the base path of the concat file given to ffmpeg in the command, and the full file paths the file, prompting this error.

**Comment by master-of-zen** [comment]
I guess best measure in long term would be to make av1an by default use pymkv or other mkvmerge wrapper, idk

**Comment by Thomasedv** [comment]
I've tried a solution from the linked text, this format seems to work:

    file 'file:c:/temp/ffmpeg/01.mov'
    file 'file:c:/temp/ffmpeg/02.mov'

But then again, if this works for something else than windows, I won't know.
This was implemented by undoing the proposed change, and just tucking in a "file:"+ at the right spot:

    f.writelines(f'file {shlex.quote("file:"+str(file.absolute()))}\n' for file in encode_files)

**Comment by master-of-zen** [comment]
Will test :+1:

**Comment by master-of-zen** [comment]
@Thomasedv all checks passed for https://github.com/master-of-zen/Av1an/commit/5310350d8eec2f89af7a6a735ab86e3070f5b363
Looks like it works just fine, thank you :1st_place_medal:

**Comment by Thomasedv** [comment]
Great!
