### ISSUE TITLE
Save extra splits

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#200]
There should be a way to save the extra splits to avoid from recomputing them.
Either save them in the scenes csv or a separate file idk.

**Comment by lastrosade** [comment]
For context, I am encoding a gameplay video and testing different settings using -s 0 to skip scene detection as the video is one single continuous scene I end up waiting 5 to 10 minutes for av1an to recompute the exact same extra splits every time.
Its a lot of time wasted doing the same exact thing over and over again

**Comment by master-of-zen** [comment]
It's not recomputing scenes, it's getting total frame count of file.
For now you can just make -s scenes.json fine, delete all scenes from it, and reuse it.

**Comment by lastrosade** [comment]
There should not be any manual operations beyond command line settings

**Comment by lastrosade** [comment]
`06:06:54 Skipping scene detection
06:06:54 Applying extra splits
06:14:41 Split distance: 240
New splits:123`
Also this is what the log file says which to me points towards recomputing scenes

**Comment by master-of-zen** [comment]
It's not valuable to save extra splits as they can be easily calculated from total frame count and scenes. So it's problem is just about saving  total frame count without scene detection

**Comment by master-of-zen** [comment]
Online https://github.com/master-of-zen/Av1an/commit/bf3e225f48b9b05ce610b47702ff5e7dc175c1e5

**Comment by lastrosade** [comment]
Tested, it works, thanks.
