### ISSUE TITLE
Scene splitting goes beyond the total amount of frames

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#201]
![unknown](https://user-images.githubusercontent.com/20532320/102878943-55ef9c80-4449-11eb-8cef-d4e688d1e79e.png)
As you can see in the included screenshot, this scene file contains 3 scenes beyond the end of the video

The encode obviously failed.
Transcoding the video to ffv1 fixed the issue.

A simple check could help on this issue, ie:
if last_scene_num > frames then crash and inform of the issue else continue.

**Comment by master-of-zen** [comment]
@lastrosade should be fixed by now as the total accurate frame count is fetched with vapoursynth before creating a chunk queue
