### ISSUE TITLE
[suggestion] Keep reuse first pass on resume

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#202]
Currently, `--reuse_first_pass` does not work when resuming an encode.

It should.

**Comment by n9Mtq4** [comment]
I can't reproduce this. Can you be more specific about it not working. Does it not reuse the first pass or does it error?

**Comment by lastrosade** [comment]
I can't reproduce it either for some reason, with the same source and same settings.
I hate computers.
