### ISSUE TITLE
[suggestion] Retry when aomenc crashes

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#203]
There are times when aomenc crashes on certain chunks, this forces the user to resume the encode later on to retry those chunks, most of the time, this works but it's not very practical.

There should be a way to catch those crashes and retry automatically.

also to note that there is a workaround for a few aomenc crashes that simply to transcode the video using for example ffv1. this could be used if a chunk crashes twice.

**Comment by master-of-zen** [comment]
Requires new encoding manager to be written

**Comment by lastrosade** [comment]
As a plus it would be VERY nice if those crashes were to be logged.

**Comment by master-of-zen** [comment]
@lastrosade done in this commits, restart chunk up to 3 times
https://github.com/master-of-zen/Av1an/commit/74d1795e831e1002ab1e8674c84ca37781d24586
https://github.com/master-of-zen/Av1an/commit/740a9fc1766c0f3d65be954cf8939202c96a5c40
https://github.com/master-of-zen/Av1an/commit/04330061a4208c0fd3b3945009583707f5a88139

**Comment by master-of-zen** [comment]
@lastrosade and all crashes logged
