### ISSUE TITLE
--cpu-used doesn't change file quality, but does change encoding time

### ISSUE THREAD

**Issue by TheHardew** [master-of-zen/Av1an#215]
How I encoded the files (I'm using fish as my shell):
```
for c in (seq 0 8)
    mkdir "$c-8"
    av1an -i dota2-10.y4m -o "$c-8/$c-8.mkv" --vmaf -fmt yuv420p -v "--cpu-used=$c --end-usage=q --cq-level=20 --threa
ds=4" -w 8 -log "$c-8/$c-8.log"
end
```

`--cpu-used 8` and `--cpu-used 0` are the same file, they only differ in the header, only in 42 bytes, but one takes 3 hours to encode, the other only 5 minutes.

I encoded first 10 seconds of "DOTA2" from https://media.xiph.org/video/derf/ 

```
~ $ av1an --version
Av1an version: 5.5-3
~ $ pikaur -Qo aomenc
/usr/bin/aomenc is owned by aom 2.0.1-1
```
I installed av1an from https://aur.archlinux.org/packages/python-av1an/

**Comment by master-of-zen** [comment]
@TheHardew for default mode (non-realtime) only `cpu-used` 0-6 exist. Realtime cpu-used are 6-9

There should be no big differences in end quality from preset change(for aomenc). The main gain is in reducing file size. 
Rough example: by going from cpu6 to cpu0 overall deltas is 20-30%, which means that quality is ~5% better, with ~25% size decrease.

I assume something not ok with the script, I would recommend just running these 2 commands:

`av1an -i dota2-10.y4m -o "cpu3.mkv" --vmaf -v "--cpu-used=3 --end-usage=q --cq-level=50 --threa
ds=64 --tile-columns=2 --tile-rows=1 " -log "cpu3.log"`

`av1an -i dota2-10.y4m -o "cpu6.mkv" --vmaf -v "--cpu-used=6 --end-usage=q --cq-level=50 --threa
ds=64 --tile-columns=2 --tile-rows=1 " -log "cpu3.log`

**Comment by TheHardew** [comment]
The logs state that `--cpu-used` is different and as I said, `--cpu-used 0` was 36 times slower. All the files are of the exact same size and only differ in the header by 42 bytes.

**Comment by master-of-zen** [comment]
@TheHardew that might be it, av1an by default use temp directory based on the file name. 
`--temp` specify temp folder.
Use `--temp .$c` in your script to give each run it's own temp folder

**Comment by TheHardew** [comment]
I just checked, by default the temporary folder name is created by hashing the input file name, which can lead to such problems: https://github.com/master-of-zen/Av1an/blob/master/av1an/project/Project.py#L183

I think it would be better to use something like tempfile: https://stackoverflow.com/a/8745610

**Comment by Felixkruemel** [comment]
@TheHardew 
Maybe I'm wrong, but when using a random name each time resuming isn't possible anylonger or?

Also just for m information:
Why are you using 8Bit and not 10Bit?

**Comment by master-of-zen** [comment]
@Felixkruemel it doesn't use a random name each time, name hashed based on the input file name.

**Comment by TheHardew** [comment]
@Felixkruemel oh right, I forgot the program should also be able to resume, without specyfing the directory if possible. It could search folders in the current directory and based on logs determine if it is possible to resume. Doesn't sound like and ideal solution, however the current implementations is also not perfect. Or maybe use the hash as a prefix and temporary name as a suffix?

I was using 8 bit just because I was doing some benchmarks. When I start encoding I'll certainly use 10 bit, it provides better quality and even, if no software can decode it in real time, I'd just transcode it temporarly to x264 veryfast crf 16.

**Comment by master-of-zen** [comment]
@TheHardew close issue?

**Comment by TheHardew** [comment]
Well the problem is still there, I don't think anybody woud expect 2 different instances of the program to interfere with each other by default, I said what could be done to prevent it, but if you want it to remain this way I can close the issue. So what's your call?

**Comment by TheHardew** [comment]
Or maybe switch to hashing the output path instead? That would require the least amount of changes and no one should need to write to the same file multiple times at once.

**Comment by TheHardew** [comment]
Sorry for all the spam, I saw some code has changed, I'll check if it works better now and if it does I will close it. In case you have already fixed it maybe tag commits in the issues next time for easier monitoring.

**Comment by luigi311** [comment]
I think the current implementation is fine. Specifying the temporary directory is available for cases like this where you would run multiple instances while by default it works perfectly as you would only really run a single instance.   
Searching through all the folders in the current directory is not something I would recommend as it can cause unknown results if it finds a log file that it thinks should be read and used and can also use up a lot of I/O for no reason when you use av1an in a large directory.   
As for your script just add a dynamic directory for the temp for 8/10 bit so they each get their own and you won't have an issue. Similar to how you are doing log.

**Comment by TheHardew** [comment]
What about hashing the output path instead? I don't think it has any disadvantages, apart from maybe incompatibility with folders from previous versions. What is most anoying about the current implementation is not, that the user has to specify 1 additional flag, but that it is unexpected and could lead to loss of data if the user doesn't know about the problem beforehand.

**Comment by luigi311** [comment]
If the user tries to resume and change the output file name because there's a typo it would break and restart the encoding fresh.
