### ISSUE TITLE
Creating 8-bit yuv420p video output with the x265 encoder

### ISSUE THREAD

**Issue by kripod** [master-of-zen/Av1an#217]
I’ve tried using the default options with the x265 encoder and it turns out that Safari playback stutters with those. I’m not sure about the cause, but after inspecting with `ffprobe`, it turns out that Safari could play [8-bit yuv420p demo files](https://x265.com/hevc-video-files/) properly, but not the 10-bit files emitted by Av1an.

In addition to that, `ffmpeg -i video-2-tmp.mkv -c:v copy -tag:v hvc1 -c:a copy video-2.mp4` should be used to let Safari and mac OS identify HEVC properly.

**Comment by master-of-zen** [comment]
@kripod you can just set 8 bit output ` -v " -p slow --crf 25 -D 8 " `
By default, all piping and outputs are 10 bit (as it usually inherently better)

**Comment by kripod** [comment]
I’ve tried `-v "-D 8"`, but unfortunately, it didn’t work out as it threw errors at me before the encoding process could even start:

```
Params: -D 8
  0%|                                                  | 0/2700 [00:00<?, ?fr/s]:: Chunk #10 crashed with:
:: Exception: <class 'ValueError'>
 re.compile('--crf') is not in list
:: Restarting chunk
```

I’m not sure if the stuttering/flickering issue could be caused by the endianness of the 10-bit pixel format in use. Unfortunately, I couldn’t find recommendations about pixel formats for Safari playback.

**Comment by master-of-zen** [comment]
@kripod you need to give whole command `-v " -p slow --crf 25 -D 8 "`  just giving -v "-D 8" will crash encoder because no --crf or preset was given, what is exactly what happens

**Comment by kripod** [comment]
Just noticed that you also included `-p slow` and `--crf 25` as they’re included here: https://github.com/master-of-zen/Av1an/blob/efa467fd1f228cdd132f4ef54c9b636287f280d2/av1an/encoder/x265.py#L17

Thank you for that, I thought those options were always provided.
