### ISSUE TITLE
Encoder vpxenc not found. Is it installed in the system path?

### ISSUE THREAD

**Issue by kripod** [master-of-zen/Av1an#219]
I’ve tried converting a video into VP9 using the following command:

```bash
av1an --input source.mkv --target_quality 85 --vmaf_path ~/Downloads/vmaf_float_v0.6.1.pkl --chunk_method vs_ffms2 --output video-3-tmp.mkv --encoder vpx --audio_params="-c:a libopus -b:a 64k -vbr on"
```

Unfortunately, on mac OS 11.1 (Big Sur), I got the following error message, even after running `brew install libvpx` and then restarting the terminal:

```
Encoder vpxenc not found. Is it installed in the system path?
```

After searching on the internet, I found no information about where to install `vpxenc` from on a Mac. I would appreciate some guidance on this issue. Thank you for helping in advance!

**Comment by master-of-zen** [comment]
Search for `vpxenc` systemwide it must be somewhere, and that place is not in `$PATH`

**Comment by kripod** [comment]
@master-of-zen I did that prior to posting this issue, but unfortunately, it came up with no results.

**Comment by master-of-zen** [comment]
@kripod don't familiar with macOS. Here is my binary packed 
[vpxenc.zip](https://github.com/master-of-zen/Av1an/files/5861152/vpxenc.zip)

**Comment by kripod** [comment]
@master-of-zen Thank you! In the meantime, I’ve noticed that the brew formula uses `--disable-examples`  for compilation, which, for some reason, skips the `vpxenc` tool when building. Posted a PR to fix the formula: https://github.com/Homebrew/homebrew-core/pull/69659/files

In the meantime, the following commands helped me out:

```bash
brew edit libvpx
brew reinstall --build-from-source libvpx
```

**Comment by olegshulyakov** [comment]
@kripod Can you please provide the steps how you build/install in on Mac?

**Comment by kripod** [comment]
@olegshulyakov I’m not sure about that anymore, unfortunately.

**Comment by srgb192** [comment]
@olegshulyakov 
I just encountered this issue. 
Brew might download the original formula and overwrite the modified one, so you may need to provide a local formula for installation. 
Here are my steps:

1. `brew edit libvpx`
2. Remove `--disable-examples` like what kripod did, then save the modified formula to somewhere.
3. `brew reinstall --build-from-source /yourPath/libvpx.rb`

Then it should work.
