### ISSUE TITLE
Reword "AVIF" support to "IVF" support

### ISSUE THREAD

**Issue by joedrago** [master-of-zen/Av1an#22]
Hello! --

I regularly see your posts on r/AV1 about this tool, and when I noticed that it supported AVIF, I was excited (as I am the author of libavif), but based on the implementation, it appears you are actually supporting IVF, not AVIF.

I'm not pushing for AVIF support or anything, I just want to note the distinction between IVF and AVIF, and that you accurately cite which one you're actually outputting (or not). Cheers!

**Comment by master-of-zen** [comment]
Hello!
I fixed misleading description, thank you.
 For some reason i thought that AVIF is just single AV1 frame encoded to container, so i make single frame image encode to .ivf container, and called it a day  without giving it a second thought.

Well, it works :) [meme-pic](https://cdn.discordapp.com/attachments/610740411723546635/675510633285812256/031445_08_02_20.png)

I would really like to include AVIF encoding into my project, can you give me guidance how it can be done properly?

**Comment by joedrago** [comment]
If you convert an image to .y4m, you can always encode to .avif with avifenc, or you can take a .ivf and pack a .avif using mp4box.

**Comment by master-of-zen** [comment]
Ok, will look into that
