### ISSUE TITLE
Fails after creating extra splits. "KeyError: None"

### ISSUE THREAD

**Issue by CaidenBlock** [master-of-zen/Av1an#236]
ffmpeg version 4.3.2
AOMedia Project AV1 Encoder 2.0.2-1328-gc458ab0b5
Av1an 6.1.post2

[avian log](https://github.com/master-of-zen/Av1an/files/6056585/my_log.log)
[ffprobe of file](https://github.com/master-of-zen/Av1an/files/6056586/ffprobe.log)

[traceback](https://github.com/master-of-zen/Av1an/files/6056587/traceback.log)

I really can't figure this out, I get this error regardless of what file I use or what arguments I try.
I tried to figure it out for quite a while.
I'll try to provide additional info if requested

I'll clean install everything after work and try again.
There's  a pretty good chance I messed up, but it's too far outside my area of expertise.

**Comment by master-of-zen** [comment]
@CaidenBlock thanks for your issue, I will look into that

**Comment by master-of-zen** [comment]
@CaidenBlock why do you specify `--force` is it showing some error without it?

**Comment by CaidenBlock** [comment]
> 
> 
> @CaidenBlock why do you specify `--force` is it showing some error without it?

Force was just there as a test

I clean installed and the issue is no longer present, Sorry for wasting your time

**Comment by master-of-zen** [comment]
@CaidenBlock Have a good day :kissing_heart:
