### ISSUE TITLE
Workers parameter not working on windows?

### ISSUE THREAD

**Issue by ibex-are-goats** [master-of-zen/Av1an#24]
Note that -t = 10 and Workers = 2
CPU: 6 core 12 thread 3600x 

av1an.exe -i sample-cut.mkv -t 10
100%|██████████████████████████████████████████████████████████████████████████▊| 308/309 [00:01<00:00, 253.62frames/s]
Clips: 2 Workers: 2
Params: --cpu-used=6 --end-usage=q --cq-level=40
|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 2/2
Completed in 320.7 seconds

**Comment by master-of-zen** [comment]
Most probable is that you have `sample-cut.mkv` that only contains 2 scenes. Is that true?

**Comment by ibex-are-goats** [comment]
I think you are right, but that just means I don't understand what workers and threads are ;)

I tested with different files, and different worker amounts would come up. So maybe the -t option is just MAXIMUM threads, not the actual number of threads it will use?

**Comment by master-of-zen** [comment]
I will explain. `-t` is how many workers (encoders) you running in parallel. AOM is basically single threaded encoder. For example if you use 3 workers with rav1e that have 4 tiles it will load 12 threads. 3 encoders with 4 threads per encoder
