### ISSUE TITLE
"'-b' isn't a valid param for vpx. Did you mean '-D'?"

### ISSUE THREAD

**Issue by cogman** [master-of-zen/Av1an#245]
`av1an --input input.mkv --target_quality 85 --encoder vpx`

```WARNING: Invalid params:
'-b' isn't a valid param for vpx. Did you mean '-o'?
To continue anyway, run Av1an with --force
```

With the above settings, av1an complains that I'm passing in `-b` to vpx.  I'm on bullseye debian and I've built master vpx.  I can try forcing this but it causes the thread to crash when I try and run things.

Av1an version: 6.1-2
ffmpeg version 4.3.2
vpx version: current master

**Comment by master-of-zen** [comment]
That's strange, works just fine for me
![2021 04 13_02:39:26](https://user-images.githubusercontent.com/46526140/114475756-89755300-9c01-11eb-9660-7dd7d0edae56.jpg)

**Comment by master-of-zen** [comment]
make sure that you have vpxenc with high bit depth build configuration enabled. Default vpxenc usually builds without it @cogman

**Comment by cogman** [comment]
@master-of-zen That did it, thanks.  I built vpx with `./configure --enable-vp9-highbitdepth` which ultimately got me what I'm after.
