### ISSUE TITLE
Update SVT-AV1 link in README to GitLab repo

### ISSUE THREAD

**Issue by louie-github** [master-of-zen/Av1an#246]
Currently, the link to SVT-AV1 in the README links to the [GitHub](https://github.com/OpenVisualCloud/SVT-AV1) repository of the SVT-AV1 project which has now been archived. 

The repository has moved over to [GitLab](https://gitlab.com/AOMediaCodec/SVT-AV1), as described in this relevant issue on the GitHub repository: [[Announcement] Repo moving to gitlab](https://github.com/AOMediaCodec/SVT-AV1/issues/1679)

I suggest updating the link in the README file to reflect the change, especially as Google still lists the GitHub repo first in its search results, so people might get confused.

Thank you for your time!

**Comment by master-of-zen** [comment]
@louie-github fixed in https://github.com/master-of-zen/Av1an/commit/af1132d0e11af9d5393012c18f23cd98394be9c5
Thank you
