### ISSUE TITLE
Crash after scene detection

### ISSUE THREAD

**Issue by lobomfz** [master-of-zen/Av1an#248]
From time to time i try to use av1an but I always get this error and give up for a few months but i finally got to file an issue. i've tried numerous possible configurations and input files, it always crashes right after the scene detection is done. The log simply states:

> Av1an Started
> Command:
> /usr/bin/av1an -i test3.mkv -enc aom --keep -o output
> 01:51:46 AM Starting scene detection Threshold: 35, Min_scene_length: 60
> 01:51:46 AM Starting PySceneDetect:
> Threshold: 35, Min scene length: 60
>  Is Vapoursynth input: False
> 01:52:04 AM Found scenes: 102
> 01:52:14 AM Applying extra splits
> 01:52:14 AM Split distance: 240
> New splits:110

And the following traceback:

> Traceback (most recent call last):
>   File "/usr/bin/av1an", line 8, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.9/site-packages/av1an/__main__.py", line 14, in main
>     manager.run()
>   File "/usr/lib/python3.9/site-packages/av1an/manager/Manager.py", line 64, in run
>     EncodingManager().encode_file(proj)
>   File "/usr/lib/python3.9/site-packages/av1an/manager/Manager.py", line 93, in encode_file
>     chunk_queue = load_or_gen_chunk_queue(project, project.resume,
>   File "/usr/lib/python3.9/site-packages/av1an/chunk/chunk_queue.py", line 64, in load_or_gen_chunk_queue
>     chunk_queue = create_encoding_queue(project, split_locations)
>   File "/usr/lib/python3.9/site-packages/av1an/chunk/chunk_queue.py", line 86, in create_encoding_queue
>     chunk_queue = chunk_method_gen[project.chunk_method](project,
> KeyError: None

This is the most basic example (almost no args passed), but nothing seems to work. It also crashes if i provide a scenes file.
My system is Arch Linux, latest python3 (3.9.3), I've tried installing both av1an and av1an-git from the AUR and also using pip with no success. If any more information is needed just let me know.

**Comment by master-of-zen** [comment]
@lobomfz Try this
Uninstall av1an, and install arch packages `vapoursynth`, `ffms2``vapoursynth-plugin-lsmashsource`
after that install from pip `vapoursynth`, `opencv-python-headless`
and av1an again

**Comment by lobomfz** [comment]
This does fix the issue, but i think the instructions should be a little clearer since this happened with all my arch installs, anyway, thanks for clarifying
