### ISSUE TITLE
Windows: Unable to work with file paths with spaces?

### ISSUE THREAD

**Issue by ibex-are-goats** [master-of-zen/Av1an#25]
It seems that having a space in the path breaks the script even when path is wrapped with " ". See error:

D:\Downloads\x\!downloaders\Av1an>av1an -i "D:\Downloads\x\!downloaders\Av1an\test - Copy\test2\F0144M-F2.wmv"
100%|████████████████████████████████████████████████████████████████████████▊| 5649/5661 [00:08<00:00, 642.79frames/s]
Argument '-' provided as input filename, but 'D:\Downloads\x\!downloaders\Av1an\test' was already specified.
Clips: 0 Workers: 0
Params: --cpu-used=6 --end-usage=q --cq-level=40
|---------------------------------------------------------------------------------------------------------| 0% 0/0 Traceback (most recent call last):
  File "av1an.py", line 512, in <module>
    av1an.main()
  File "av1an.py", line 490, in main

  File "multiprocessing\context.py", line 119, in Pool
  File "multiprocessing\pool.py", line 205, in __init__
ValueError: Number of processes must be at least 1
[46688] Failed to execute script av1an

**Comment by master-of-zen** [comment]
Fixed in [Merge](https://github.com/master-of-zen/Av1an/commit/6c5caef5fa07987073846f76b28fb1c80e2da665)

**Comment by ibex-are-goats** [comment]
That looks like a lot of work in that merge. Thank yiu for fixing this bug! :)
