### ISSUE TITLE
VMAF default threads set too high

### ISSUE THREAD

**Issue by cogman** [master-of-zen/Av1an#252]
VMAF threads are currently defaulted to 12 threads per process.  However, you can expect "worker" number of VMAF processes to be spun up at any given time. (Giving you roughly worker * VMAF threads in cpu requirements)

Rather than controlling parallelism with both VMAF settings and worker settings, it should be one or the other.   Ideally (IMO) all processes would target using a ~1 core so workers can be set appropriately.

With that in mind, VMAF should be set to 1 or 2 threads by default.  Setting it higher than that will over provision a system where workers are at or close to the number of cores on a system.

**Comment by luigi311** [comment]
I had this implemented a while back but made no difference in encoding time but I can reimplement it. I set vmaf threading to workers/cpu_threads so it wouldn't over provision

**Comment by cogman** [comment]
@luigi311  You don't want vmaf threading set to worker threads.  You want vmaf threading set to 1 or 2 threads.  Setting it to worker threads would over provision because it ends up being a multiplicative effect on CPU resource requirements. You'll have n workers with n vmaf threads giving you n^2 cpu requirements.

**Comment by luigi311** [comment]
I'm not sure I understand. If you have 20 threads and do 5 workers then each vmaf computation will have 4 threads for a total workload of 20 threads.

**Comment by luigi311** [comment]
Setting it statically to 1-2 threads would make the vmaf calculations take forever making target_quality time grow exponentially

**Comment by luigi311** [comment]
If you only have 20 threads and you are running 20 workers then vmaf will only be set to 1 thread similar to the use case you described so even then it will not over provision and will function to how you want but would be better for other use cases where you use less workers than threads.

**Comment by BlueSwordM** [comment]
I agree with luigi311 here.
target_quality is a large latency penalty, and since chunks are done in order of length, it's important to get them done quickly(without saturating the CPU to the point of thread oversaturation).

Let's just say you have an 8C/16T CPU and an encoder that can use 4 threads decently. Well, that means the optimal ratio of workers is around 5-6.

In that case, to take into consideration idle time, it would be best to set the default vmaf_threads to 4/6 instead of 12(except for an encoder like SVT-AV1 which threads extremely well at preset 4 and above), as it would decrease the CPU time used linearly while not decreasing speed as much(scaling for VMAF starts going down after 6 threads).

My point: lowering the default VMAF_threads is good, but not down to 1-2.
I think 4-6 would be good(6 is what I use).

**Comment by cogman** [comment]
@luigi311 I could be reading the code wrong, but when I set my workers to 8 and I don't set my vmaf threads, I end up with 12 vmaf threads.  The end result is lots of scenarios where I'm running 96 threads on a box with 16 cores.  From what I see in the code, it's hardcoded to just do 12 threads if nothing is set, worker threads don't appear to be under consideration.

I'd be amenable to having it try and be smart (say, vmafThreads =  (system cores / workers * fudge factor) )

@BlueSwordM With a ryzen 5600x, VMAF threads set to 2 and workers to 8,  I'm seeing most of my idle time during the encoding process and not the VMAF calculation.

The total amount of VMAF work is fixed and threading an application is generally the worst way to improve parallelism (you have to manage state with locks/immutable data/etc).  The better way to do that is adding more processes with less threads if possible and for an encoding workload it's very possible.  So long as your encoder operation can keep a CPU busy (usually it can) VMAF can too with just 1 thread.

The exception to the above rule is when memory is at a premium.  But if that's not an issue, then more processes trump more threads.

Play with it yourself, but you'll get a lower total time if you try and cut your AV1 thread usage down as much as possible.

That's where I get to the the basis of this case.  An ideal setup is every worker process using 1 CPU core and the number of workers set to the number of CPU cores.  Trying to get each of the worker procceses to match CPU utilization (200% 400%) is a much harder task that's only worth it if you have limited memory or not enough work to keep all your cores busy.

**Comment by luigi311** [comment]
You are correct in that av1an currently default to 12 vmaf threads no matter what and you proposed setting it to 1/2. I proposed setting it dynamically by taking a look at the amount of workers and how many threads your machine has. If you are using 1 worker cool you get all the threads, if you are using as many workers as threads then cool vmaf is single threaded and everything in-between.

**Comment by cogman** [comment]
@luigi311 Yeah, that makes sense.  default vmafThreads = max((system cores / workers) * fudge factor), 1) and I'd set fudge factor to like 1.5 or something.
