### ISSUE TITLE
Concatenation eventually fails if the audio encoding fails

### ISSUE THREAD

**Issue by redzic** [master-of-zen/Av1an#255]
Hi,

If `audio.mkv` in the temp folder ends up being 0 bytes, then concatenation with ffmpeg fails at the end.
This can happen when the encoder fails to downmix some multi-channel audio (happens with libopus with 3 channel audio), and possibly other audio encoders as well.
The current behavior of av1an is that it runs the scene detection, possibly fails to downmix (or fails to encode the audio for some other reason), encodes the entire video, then fails to concatenate at the end (at least with using ffmpeg, haven't tried with mkvmerge).

Example output when using source that has source that fails to encode:

```
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 28776/28778 [01:55<00:00, 248.59frames/s]
[libopus @ 0x55aa11e34040] Invalid channel layout 2.1 for specified mapping family -1.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Queue: 238 Workers: 11 Passes: 2
Params: --threads=8 -b 10 --cpu-used=6 --end-usage=q --cq-level=30 --tile-columns=2 --tile-rows=1
  1%|▉                                                                                                                                            | 183/28776 [00:20<47:42,  9.99fr/s]
```

I think that av1an should probably check for any errors with the audio encoder (maybe just check if `audio.mkv` is 0 bytes), and if there are, print some warning message and then just encode the video without audio.

Currently, a workaround is to delete `audio.mkv` and just use `--resume` with same parameters.

**Comment by master-of-zen** [comment]
@redzic hey, this should solve this issue) https://github.com/master-of-zen/Av1an/commit/6b3353423e2918015c47dc17a6efc0625680f998
FFmpeg "touch" file even if it fails, creating 0 bytes file, this should be handled now

**Comment by redzic** [comment]
Sounds good, thanks
