### ISSUE TITLE
[Feature Request] Change encoding parameters for specific segments

### ISSUE THREAD

**Issue by shssoichiro** [master-of-zen/Av1an#267]
I'm still thinking through what the implementation for this might look like--maybe "Provide a list of frame ranges, and if the start frame for a segment is within that range, use these parameters instead of the default ones for the encode"

My use case here is: I may have segments of some files where I want to change encoding settings for a specific segment. For example, if there is a segment of a video with very heavy film grain, I may want to adjust the cq level or other settings to encode that segment differently from the rest of the file.

**Comment by master-of-zen** [comment]
@shssoichiro right now there is a hack to achieve what you want.
* Finish encode with `--keep` flag
* Find in `temp folder/encode` segments that need to be changed
* Go to temp folder `done.json` file, remove them.
*  Start encode with new parameters and `--resume` flag. This will encode only removed segment with new settings

Complete solution is a though for a future

**Comment by redzic** [comment]
@shssoichiro Is this still a feature you want to see implemented?

**Comment by shssoichiro** [comment]
It's a "nice to have" but not something I'd prioritize if there are more important things on the table.
