### ISSUE TITLE
av1an + rav1e parameters in Windows

### ISSUE THREAD

**Issue by hl2guide** [master-of-zen/Av1an#274]
OS: Windows 10

Installed Software:
* av1an 6.1.5 (pip)
* VapourSynth R53
* ffmpeg version 2021-06-02-git-071930de72-essentials (all three binaries)
* rav1e 0.4.1

when i run this command:

`av1an -i "C:\Temp\TESTING.mp4" -enc rav1e -o "C:\Temp\TESTING out.mp4"`

I get:

```
WARNING: Invalid params:
'--no-scene-detection' isn't a valid param for rav1e. Did you mean '--reconstruction'?
To continue anyway, run Av1an with --force
```

**Comment by master-of-zen** [comment]
@hl2guide `--no-scene-detection` is new parameter for rav1e. If you're using stable/old build - it haven't been added yet. 
You can use latest rav1e git build 
Or add ` -v " --tiles 8 --speed 6 --quantizer 100 "` to your command line to use settings without it

**Comment by hl2guide** [comment]
Are you reffering to a "Weekly pre-release" of rav1e?

What version of rav1e should I look for?

**Comment by master-of-zen** [comment]
> Are you reffering to a "Weekly pre-release" of rav1e?

I usually just compile from current git. 
>What version of rav1e should I look for?

Any version, like current stable 0.4 is totally fine

**Comment by hl2guide** [comment]
Now after running: `av1an -i "C:\Temp\TESTING.mp4" -enc rav1e -v " --tiles 8 --speed 6 --quantizer 100 " --target_quality 98 -o "C:\Temp\TESTING out.mp4"`

I get:

```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32948/32948 [04:49<00:00, 113.92frames/s]
Queue: 148 Workers: 1 Passes: 1
Params: --tiles 8 --speed 6 --quantizer 100
  0%|                                                                                                                                                                                                            | 0/32948 [00:00<?, ?fr/s]::VMAF validation error: 3221225477
::Stream mapping:
libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
libvmaf INFO `compute_vmaf()` is deprecated and will be removed in a future libvmaf version
libvmaf WARNING could not read model from path: "/usr/local/share/model/vmaf_v0.6.1.pkl"
libvmaf WARNING pkl model files have been deprecated, use json
libvmaf ERROR problem loading model file: /usr/local/share/model/vmaf_v0.6.1.pkl
[Parsed_libvmaf_2 @ 00000246b2923ec0] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Finishing stream 0:0 without any data written to it.
Output #0, null, to 'pipe:':
Metadata:
encoder         : Lavf59.2.101
Stream #0:0: Video: wrapped_avframe, yuv444p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 1 fps, 1 tbn (default)
Metadata:
encoder         : Lavc59.1.100 wrapped_avframe
  0%|                                                                                                                                                                                                            | 0/32948 [00:02<?, ?fr/s]
```

**Comment by luigi311** [comment]
You have ffmpeg built with vmaf 2.X. You need to specify the vmaf model file and use their new json files. You can get them at the vmaf github under models https://github.com/Netflix/vmaf/tree/master/model vmaf_v0.6.1.json is the equivalent that everyone's been using by default. You can specify that file with --vmaf_path vmaf_v0.6.1.json

**Comment by hl2guide** [comment]
Now From: `av1an.exe -i "C:\Temp\TESTING.mp4" -enc rav1e -v " --tiles 8 --speed 6 --quantizer 100 " --target_quality 98 --vmaf_path vmaf_v0.6.1.json -o "C:\Temp\TESTING out.mp4"`

I get:

```
Chunk #119 crashed
::Exception: <class 'RuntimeError'> Error in processing encoding pipe
::Restarting chunk
::FATAL
```

I hope that you get this app ready from production as some point but at this point I can't help but come to the conclusion that it's not.
