### ISSUE TITLE
[feature request] switch to have av1an encode chunks in order rather than longest first 2.0

### ISSUE THREAD

**Issue by plonk264** [master-of-zen/Av1an#275]
i have a movie with large swaths (3-10 mins) ending up with a lower quality than normal, even with probing_rate 1, not just a chunk here and there.

an in-order encode log (and execution) would make it a lot easier to see the cq-levels the encoder is using

**Comment by luigi311** [comment]
Would  using -xs not solve this issue? It will force the large chunks to be divided into smaller chunks for finer CQ control in sections. You can also turn up the pyscenedetect sensitivity and that might split it to smaller chunks too.

**Comment by plonk264** [comment]
i don't need greater or fewer splits/chunks. i just need to know what cq levels the encoder is using on the existing ones so i can decide what to do from there about quality.

i don't THINK i want to use the sledge hammer of a ridiculous max_q to control quality. at least on the primary encode (before looking into logs)

**Comment by redzic** [comment]
This is now possible with `--chunk-order sequential`.
