### ISSUE TITLE
Aomenc error in encoding process "Fatal: Specify stream dimensions"

### ISSUE THREAD

**Issue by ahmadrr** [master-of-zen/Av1an#283]
I ran the encode last night, unattended. Last time I checked (about 16 hours ago), it was running just fine (21 chunks done). But when I came back, the last 84 chunks were all saying " Fatal: Specify stream dimensions with --width (-w)  and --height (-h)". CPU usage was 100% despite no more chunks done (just erroring out), RAM usage was 55% and SSD 0%. I restarted the laptop anyway and re-ran the same command, no joy. This is the same command I use for all encodes, only changing the input/output file. Latest av1an from pip and latest aomenc from media-autobuild-suite.

C:\Program Files\Python38\Scripts>av1an -i "E:\Videos\Metamorphosa\2021-06-20 08-13-10 (0).mkv" -enc aom -v "--bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63" -p 1 --keep -fmt yuv420p -o "d:\2021-06-20 08-13-10 (1).mkv" -cm hybrid --split_method none -w 3 -xs 250 -r
Queue: 635 Workers: 3 Passes: 1
Params: --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63
  0%|▏                                                                         | 284/158727 [04:28<40:55:14,  1.08fr/s]::Chunk #225: 87/250 fr
  0%|▏                                                                         | 352/158727 [10:48<81:38:43,  1.86s/fr]::Chunk #53: 275/250 fr

ERROR IN ENCODING PROCESS

 Fatal: Specify stream dimensions with --width (-w)  and --height (-h)
  0%|▏                                                                         | 362/158727 [11:05<81:38:25,  1.86s/fr]:

I then added space around the double quotation mark for the -v switch, but still getting the same error.

C:\Program Files\Python38\Scripts>av1an -i "E:\Videos\Metamorphosa\2021-06-20 08-13-10 (0).mkv" -enc aom -v " --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63 " -p 1 --keep -fmt yuv420p -o "d:\2021-06-20 08-13-10 (1).mkv" -cm hybrid --split_method none -w 3 -xs 250 -r
Queue: 635 Workers: 3 Passes: 1
Params: --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63
  0%|▏                                                                         | 284/158727 [03:53<35:33:53,  1.24fr/s]::Chunk #225: 87/250 fr
  0%|▏                                                                         | 352/158727 [10:22<78:21:38,  1.78s/fr]::Chunk #53: 275/250 fr

ERROR IN ENCODING PROCESS

 Fatal: Specify stream dimensions with --width (-w)  and --height (-h)

This is the log.log excerpt

[22:54:50] File hash: 3c040ba0
[22:54:50] Av1an Started
[22:54:50] Command:
[22:54:50] C:\Program Files\Python38\Scripts\av1an -i E:\Videos\Metamorphosa\2021-06-20 08-13-10 (0).mkv -enc aom -v --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63 -p 1 --keep -fmt yuv420p -o d:\2021-06-20 08-13-10 (1).mkv -cm hybrid --split_method none -w 3 -xs 250 -r
[22:54:50] Resuming...
[22:54:50] Resumed with 21 encoded clips done
[22:54:51] Enc: 22, 250 fr
[22:54:51] Enc: 24, 250 fr
[22:54:51] Enc: 23, 250 fr
[23:03:41] Get frame count with ffmpeg
[23:03:41] Frame count: 250
[23:03:41] Done: 23 Fr: 250/250
[23:03:41] Fps: 0.471 Time: 530.75 sec.
[23:03:41] Enc: 25, 250 fr
[23:03:48] Get frame count with ffmpeg
[23:03:48] Frame count: 250
[23:03:48] Done: 24 Fr: 250/250
[23:03:48] Fps: 0.4652 Time: 537.43 sec.
[23:03:48] Enc: 26, 250 fr
[23:04:01] Get frame count with ffmpeg
[23:04:01] Frame count: 250
[23:04:01] Done: 22 Fr: 250/250
[23:04:01] Fps: 0.4541 Time: 550.59 sec.
...
[08:04:33] Enc: 227, 250 fr
[08:06:47] Get frame count with ffmpeg
[08:06:47] Frame count: 87
[08:06:47] Chunk #225: 87/250 fr
[08:06:47] Done: 225 Fr: 87/250
[08:06:47] Fps: 0.2317 Time: 375.5 sec.
[08:06:47] Enc: 228, 250 fr
[08:15:27] Enc: 229, 250 fr
[08:17:53] Enc: 230, 250 fr
...
[14:24:53] Enc: 310, 250 fr
[14:28:41] Enc: 311, 250 fr
[14:37:34] Enc: 312, 250 fr

Any suggestions please? Thank you.

**Comment by ahmadrr** [comment]
I also tried adding -w 1920 -h 1080 to -v switch, hoping it'll get passed to aomenc. Now I get list index out of range error. Probably passing -w and -h to aomenc via -v is not supported. I've tried matching all settings possible in Av1an to Staxrip but I consistently get lower VMAF score in Staxrip encodes, exact same ffmpeg and aomenc, maybe because Av1an have better
default settings or other magic. But I think I'll have to resort to Staxrip for chunk encoding now.

C:\Program Files\Python38\Scripts>av1an -i "E:\Videos\Metamorphosa\2021-06-20 08-13-10 (0).mkv" -enc aom -v " --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63 -w 1920 -h 1080 " -p 1 --keep -fmt yuv420p -o "d:\2021-06-20 08-13-10 (1).mkv" -cm hybrid --split_method none -w 3 -xs 250 -r
Queue: 635 Workers: 3 Passes: 1
Params: --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=42 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=300 --min-q=0 --max-q=63 -w 1920 -h 1080
  0%|▏                                                                         | 284/158727 [04:48<44:01:34,  1.00s/fr]::Chunk #225: 87/250 fr
  0%|▏                                                                         | 352/158727 [12:18<93:07:11,  2.12s/fr]::Chunk #53: 275/250 fr
  0%|▏                                                                         | 362/158727 [12:32<93:06:49,  2.12s/fr]Chunk #226 crashed
::Exception: <class 'IndexError'> list index out of range

**Comment by master-of-zen** [comment]
Error at start of encoding means: `Fatal: Specify stream dimensions with --width (-w) and --height (-h)` means that encoder crashed at trying to get video. It's not encoder issue, it's piping issue. It can be due to bad file/bad ffmpeg or other third party reasons.
If encoder crashed durring encoding it can be due to bad settings, a lot of aomenc settings are prone to crashes

Your command can be simplified a lot 
 -enc aom` -  aomenc is default encoder
`--cpu-used=9` there is no cpu presets for non rt mode higher than 6, for fastest, it should be 6
`-fmt yuv420p` `--bit-depth=10` av1an pipe 10 bit by default so it's not required to set 10 bit in encoding settings or in pix format
it's highly not recommended to not use split method none, because it means that video will be segmented by time, which is worst case scenario, default is perfectly fine. And with -cm hybrid it creates worst case for operating when frame selection is super expensive.
Chunk method is set automatically to bes available, and it's highly recommended to use vapoursynth one. To install vapoursynth proceed there https://github.com/vapoursynth/vapoursynth/releases/tag/R53 and after that install ffms2 and lsmash with https://github.com/vapoursynth/vsrepo
Better guide can be found here https://github.com/vapoursynth/vsrepo

```
av1an -i "E:\Videos\Metamorphosa\2021-06-20 08-13-10 (0).mkv" -v "  --cpu-used=6 --end-usage=q --cq-level=42 --threads=1 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 " -p 1 --keep -o "d:\2021-06-20 08-13-10 (1).mkv"  -w 3 -xs 250
```

Just in case, try to encode this file with just `av1an -i test.mp4` to ensure that it's not setup problem 

https://user-images.githubusercontent.com/46526140/122739042-3ec02900-d28b-11eb-8ef0-2e5e3e846525.mp4

**Comment by ahmadrr** [comment]
Thanks for your quick reply, but I haven't got the time to test it out. As for why using -fmt yuv420p --bit-depth=10, I encoded a few 10-bit sources and got a higher vmaf score with them on (sadly no screenshot). I knew there is no cpu presets for non rt mode higher than 6. But strangely, in this particular test clip, --cpu-used=9 is faster than --cpu-used=6 (both without -rt). Idle CPU usage 1%. Benchmarked on March 19th 2021.

![image](https://user-images.githubusercontent.com/44171723/123520879-51988a80-d6dd-11eb-970b-4fbdf86e051f.png)
![image](https://user-images.githubusercontent.com/44171723/123520895-6412c400-d6dd-11eb-94c4-bbd0f2be2e02.png)

The VMAF scores:
cpu9=93.882044
cpu8=93.882044
cpu7=93.882044
cpu6=93.882044
cpu5=93.961148
cpu4=93.798072
cpu3=93.732890
cpu2=93.817003
cpu1=93.946445
cpu0=93.973012

--cpu=6 --good is exactly the same as --cpu=6 in vmaf score and file size, but the former is faster.

D:\Video\av1>python av1an.py -i d:\MOV_0036.mkv -enc aom -v "--bit-depth=10 --cpu-used=6 --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63" -p 1 --keep -fmt yuv420p -o d:\video\MOV_0036a.mkv -cm hybrid -w 4 --min_scene_len 292
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [00:01<00:00, 71.61frames/s]

Queue: 1 Workers: 1 Passes: 1
Params: --bit-depth=10 --cpu-used=6 --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [01:47<00:00,  1.30fr/s]
Finished: 144.6s

VMAF score: 94.884937

D:\Video\av1>python av1an.py -i d:\MOV_0036.mkv -enc aom -v "--bit-depth=10 --cpu-used=6 --good --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63" -p 1 --keep -fmt yuv420p -o d:\video\MOV_0036a.mkv -cm hybrid -w 4 --min_scene_len 292
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [00:01<00:00, 70.25frames/s]

Queue: 1 Workers: 1 Passes: 1
Params: --bit-depth=10 --cpu-used=6 --good --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [01:43<00:00,  1.35fr/s]
Finished: 139.7s

VMAF score: 94.884937

D:\Video\av1>python av1an.py -i d:\MOV_0036.mkv -enc aom -v "--bit-depth=10 --cpu-used=7 --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63" -p 1 --keep -fmt yuv420p -o d:\video\MOV_0036a.mkv -cm hybrid -w 4 --min_scene_len 292
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [00:02<00:00, 69.91frames/s]

Queue: 1 Workers: 1 Passes: 1
Params: --bit-depth=10 --cpu-used=7 --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [01:42<00:00,  1.37fr/s]
Finished: 138.0s

VMAF score: 94.884937

D:\Video\av1>python av1an.py -i d:\MOV_0036.mkv -enc aom -v "--bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63" -p 1 --keep -fmt yuv420p -o d:\video\MOV_0036a.mkv -cm hybrid -w 4 --min_scene_len 292
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [00:01<00:00, 80.58frames/s]

Queue: 1 Workers: 1 Passes: 1
Params: --bit-depth=10 --cpu-used=9 --end-usage=q --cq-level=39 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --enable-keyframe-filtering=1 --tune-content=screen --row-mt=0 --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=1 --enable-chroma-deltaq=1 --enable-ab-partitions=0 --enable-chroma-deltaq=1 --auto-alt-ref=1 --kf-max-dist=292 --min-q=0 --max-q=63
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140/140 [01:29<00:00,  1.57fr/s]
Finished: 120.8s

VMAF score: 94.884937

**Comment by ahmadrr** [comment]
I'm currently not interested in the version used to produce the error (it was the latest av1an available from pip).  I might revisit it later.
