### ISSUE TITLE
Missing source code on PyPi for 6.1.5?

### ISSUE THREAD

**Issue by lfam** [master-of-zen/Av1an#286]
I noticed that there is no source tarball for 6.1.5 on PyPi, only a wheel:

https://pypi.org/project/Av1an/6.1.5/#files

If that's not intentional, can you add the tarball?

**Comment by Felixkruemel** [comment]
I don't think that's necessary to fix or? I mean Av1an won't be updating PyPi nonetheless anylonger as it's no Python Project anymore.

**Comment by lfam** [comment]
Oh, I didn't realize that. Sorry for the noise.
