### ISSUE TITLE
Audio and subtitle language information is not preserved

### ISSUE THREAD

**Issue by dnigh** [master-of-zen/Av1an#287]
When audio.mkv is split off, language information for the audio tracks and subtitles(if present) is set to undetermined even if defined in the source file

**Comment by master-of-zen** [comment]
I think the command for splitting audio/etc would require a fix for that. Unfortunately fix will land for new rust version

**Comment by dnigh** [comment]
Yeah that was going to be my plan in the interim, adding a step in my workflow to split off the video before processing with av1an and then muxing back when done

**Comment by master-of-zen** [comment]
There is another way, don't extract audio at all, and mux it directly from source when output is constructed

**Comment by dnigh** [comment]
I gotcha. I'll go ahead and close this if it's already slated for the new rust version

**Comment by FibreFoX** [comment]
I'm starting to fiddle with Av1an, but as far as I understood, the main idea is that the input-files only have one audio track, correct? My files contain multiple audio-tracks, subtitles and even some cover-image, but these are not preserved.

So if anything but the video should be copied into a separate file, why not extracting this by adding `-map 0` to the `ffmpeg`-call?
https://github.com/master-of-zen/Av1an/blob/a8812b990009d4e5e9dc11a2872e0d86575c3335/av1an-core/src/ffmpeg.rs#L124

Got that trick from some superuser thread: https://superuser.com/a/1420068

Wouldn't that help to preserve audio/subtitles/anything else?

**Comment by n00mkrad** [comment]
I would just mux everything that's not video with ffmpeg or other applications.

**Comment by FibreFoX** [comment]
Hm, this is a bit sad to do this with different tools, makes me wonder why I should use Av1an. Would be cool to have more control about these other streams in the output-file.

**Comment by lastrosade** [comment]
I personally only use the video encoding part of av1an and do all of my muxing outside of it.

**Comment by n00mkrad** [comment]
> Hm, this is a bit sad to do this with different tools, makes me wonder why I should use Av1an. Would be cool to have more control about these other streams in the output-file.

If you're on Windows, my GUI has support for both av1an and ffmpeg muxing/encoding:

https://github.com/n00mkrad/nmkoder/
