### ISSUE TITLE
"Loss of framing in Y4M input data" on specific segments

### ISSUE THREAD

**Issue by shssoichiro** [master-of-zen/Av1an#298]
This is a bit of a complicated issue to describe, and I'm not even 100% sure that the issue is with av1an itself, so I apologize if this ends up not being an av1an issue, but this seemed like the best place to possibly get a lead.

I've encoded many, many files with av1an without running into this issue before. Today, I tried encoding a set of anime BDs, and on 2 out of the 2 episodes I've tried so far, I've gotten an error from aomenc saying "Loss of framing in Y4M input data", which then causes the segment to crash.

The error:
- occurs on only one segment out of each video (the others all completed successfully)
- occurs repeatedly on the same segment if I retry it
- occurs about 10 frames from the end of aomenc's second pass (the first pass appears to complete successfully)

The error message led me to consider that the Y4M output from vapoursynth was corrupt (I'm using the default `vs_lsmas` chunk method), but I can use the same pipe command into x264 or ffmpeg without issues (e.g. `vspipe /data/tmp/.978908d8/split/loadscript.vpy -y - -s 14342 -e 14446 | x264 --stdin y4m - -o test.mkv`), so with that eliminated as a possibility, I'm stuck considering it's either an issue in av1an or in aomenc itself. I have tried changing up aomenc settings as well, and the crash still happens consistently no matter what settings I use. In case it matters, I'm using the pip version of av1an.

**Comment by master-of-zen** [comment]
@shssoichiro you can isolate the issue by switching the encoder. So you can resume your broken segment with rav1e.(Yes, you can switch encoders mid encoding, if they are for same codec :) )

Quite a long time ago I had really cryptic issue with one segment of Atlantis: The Lost Empire. No matter what I tried it was crashing for both aomenc and svt-av1, even if I transcode that segment to lossless x264, but rav1e encoded it just fine.

**Comment by shssoichiro** [comment]
Hmm, well it does indeed work if I use rav1e through av1an. So that seems like a bug in aomenc most likely? Worth reporting to their bug tracker, you think?

**Comment by master-of-zen** [comment]
Probably worth it

**Comment by shssoichiro** [comment]
Thanks! I'll close this here, then. (As a side note, I have now tracked down that it only happens at cpu-used <= 5, thus confirming it's an aomenc issue.) 🙂
