### ISSUE TITLE
Video chunks are assigned index in wrong order leading to out-of-order video parts

### ISSUE THREAD

**Issue by mxsrm** [master-of-zen/Av1an#320]
Using the newest git master (06fb8c9eddd1ca9c86b16dac7bde1ef33e15de31) using ffmpeg to concat (the default) leads to a wrong order in the video. This of course leads to video async. Tested multiple source files, problem always appears, even with small files (~30s). Not a big difference, seems to be only 1 or 2 chunks at a time; I think one of the first gets sorted to the end.

Using mkvmerge fixed it for the small files at least, restarting my 3h encode now to test if this fixed it aswell.

**Comment by shssoichiro** [comment]
Which OS are you using? I'm not seeing this issue on my end.

**Comment by mxsrm** [comment]
Up to date Manjaro Linux.

**Comment by mxsrm** [comment]
Example encoding settings:

```bash
av1an -e aom -v " --end-usage=q --cq-level=22 --cpu-used=6 --threads=8 --bit-depth=10 --lag-in-frames=35 --enable-fwd-kf=1 --enable-qm=1 --enable-chroma-deltaq=1 --quant-b-adapt=1 --mv-cost-upd-freq=2 " -a ' -c:a libopus -b:a 288k -mapping_family 1 -af aformat=channel_layouts="7.1|6.1|5.1|stereo|mono" ' -i input.mkv
```

**Comment by mxsrm** [comment]
The two larger test encodes (2x ~45min of video) using mkvmerge failed aswell. I used `--keep` to preserve the temp folders and I'm happy to upload you any of the files you need for debugging this.

I looked in on the encoded chunks and the highest number is not the last part of the video, so maybe the problem is with splitting or scene-detection?!

**Comment by master-of-zen** [comment]
I will look into that

**Comment by master-of-zen** [comment]
@mxsrm can you send a temp folder of small videos that have desync?

**Comment by mxsrm** [comment]
I will prepare an example tomorrow when I'm home (on call tonight).

**Comment by mxsrm** [comment]
@master-of-zen I have prepared an example. What is the best way to send you a 107,6MB tar.bz2 archive?

**Comment by mxsrm** [comment]
@master-of-zen I uploaded the file to WeTransfer (link is valid for 7 days): https://we.tl/t-ETdJ8TPkWQ

concat file is still present because av1an failed to handle a folder with spaces in its name (or because of the `-` sign in the folder name) and I had to manually run the concat command as displayed by the error (after fixing the folder path).

In the temp folder you will see the encodes have a wrong order to begin with (1 is not the beginning).

Kind regards

**Comment by throwabird** [comment]
Can confirm I have just discovered Av1an and it sounds very nice but I am also facing this issue on Arch Linux using `aur/av1an-git 1.12.r953.gbf1b6e9-1`.

**Comment by shssoichiro** [comment]
I'm still failing to reproduce with the coffee_run file, also on Arch Linux. I've tried multiple times, both with and without extra-splits enabled (because I thought that might be relevant), and again making extra sure I'm on the latest git master, 06fb8c9. I'm wondering, since you mentioned spaces or dashes in the folder name, if that might be relevant in some way?

**Comment by shssoichiro** [comment]
After looking at the temp folder, this seems very likely to be an issue with the `select` split method. I'm unable to reproduce this with the Vapoursynth split method.

**Comment by master-of-zen** [comment]
I couldn't reproduce the issue.
Concat file specify in which order files are concatenated, and it looks fine.

**Comment by mxsrm** [comment]
The problem is not with concat but with the chunks; see my chunks.json for example (new fresh run on the coffe_run.mkv; I prettified the result for better readability):

[chunks.txt](https://github.com/master-of-zen/Av1an/files/6939373/chunks.txt)

```json
   {
      "temp":".9e98fbf",
      "index":3,
      "ffmpeg_gen_cmd":[
         "ffmpeg",
         "-y",
         "-hide_banner",
         "-loglevel",
         "error",
         "-i",
         ".9e98fbf/split/00000.mkv",
         "-vf",
         "select=between(n\\,0\\,232),setpts=PTS-STARTPTS",
         "-pix_fmt",
         "yuv420p10le",
         "-strict",
         "-1",
         "-f",
         "yuv4mpegpipe",
         "-"
      ],
      "output_ext":"ivf",
      "size":233,
      "frames":233,
      "per_shot_target_quality_cq":null
   },
```

The beginning of the move (frame 0 to 232) gets assigned the index 3 (instead of 0) and results in being encoded as `00003.ivf` thus leading to a wrong order in the produced file.

**Comment by master-of-zen** [comment]
Can confirm  @mxsrm @shssoichiro `--chunk-method hybrid` is broken

**Comment by mxsrm** [comment]
The problem is with the chunk method:

- hybrid: wrong order but good video quality
- ffms2:  correct order, but the video quality gets absolutely butchered with lagging frames and many artefacts (example: [coffee_run_aom_ffms2.mkv.zip](https://github.com/master-of-zen/Av1an/files/6939553/coffee_run_aom_ffms2.mkv.zip)).
- select: correct order and good video quality (9.48 fps)
- segment: correct order and good video quality (11.25 fps)
- lsmash: not tested (couldn't get the dependency to work)

Used encoding settings (only chunk method changed): `av1an -e aom --keep -m select --verbose -v " --end-usage=q --cq-level=22 --cpu-used=8 --threads=8 --bit-depth=10 --lag-in-frames=35 --enable-fwd-kf=1 --enable-qm=1 --enable-chroma-deltaq=1 --quant-b-adapt=1 --mv-cost-upd-freq=2 " -a ' -c:a libopus -b:a 288k -mapping_family 1 -af aformat=channel_layouts="7.1|6.1|5.1|stereo|mono" ' -i coffee_run.mkv`

**Comment by master-of-zen** [comment]
@mxsrm does pip version with different chunk methods behave the same?

**Comment by shssoichiro** [comment]
Note: lsmash works for me. So it seems like it is just hybrid that is broken. (ffms2 shouldn't be having issues with the latest version of the plugin, but who knows?)

**Comment by mxsrm** [comment]
> @mxsrm does pip version with different chunk methods behave the same?

What exactly do you mean by that?

**Comment by master-of-zen** [comment]
> > @mxsrm does pip version with different chunk methods behave the same?
> 
> What exactly do you mean by that?

if you install av1an from pip and use it with ffsm2, is it also broken?

**Comment by throwabird** [comment]
@master-of-zen I can confirm for me at least: Using @mxsrm's input file the issues does not appear anymore when using the pip version.

**Comment by Nestorfish** [comment]
@master-of-zen Shouldn't ```segments_set``` be a ```Vec``` instead of a ```HashSet``` in ```create_video_queue_hybrid```?

**Comment by master-of-zen** [comment]
@Nestorfish right) @mxsrm should be fixed now

**Comment by mxsrm** [comment]
I can confirm this fixed the issue.
