### ISSUE TITLE
Av1an crashes if the output points to a directory that does not exist

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#321]
As title says, if I point to "/path/that/does/not/exist/video.mp4" av1an will crash.

**Comment by redzic** [comment]
What would you like av1an to do in that case? Should it try to create the parent directories and display an error message if the permissions were insufficient to do so? Or should it just require that the output path be in a directory that exists upfront, displaying an error message if it isn't?

**Comment by lastrosade** [comment]
I'd say that it should crash in a more graceful way before encoding. Creating the parent directories could lead to issues if misused.

**Comment by master-of-zen** [comment]
This should fix it https://github.com/master-of-zen/Av1an/commit/c47e19beade5970fcc2b6cfa5f77c4db193b92a9

**Comment by lastrosade** [comment]
It does, thanks!
