### ISSUE TITLE
VMAF testing: "Concatenation failed"

### ISSUE THREAD

**Issue by ibex-are-goats** [master-of-zen/Av1an#35]
See log below. Aomenc build from this guy: https://www.reddit.com/r/AV1/comments/f17649/is_there_a_download_for_aomenc_built_with_vmaf/fh2cz0x/

av1an.exe -i sample.mkv -v " --cpu-used=5 --end-usage=q --cq-level=40 --tune=vmaf"
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1416/1416 [00:05<00:00, 250.08frames/s]
Queue: 8 Workers: 6 Passes: 2
Params:  --cpu-used=5 --end-usage=q --cq-level=40 --tune=vmaf
  0%|                                                                                                                                        | 0/1416 [00:00<?, ?fr/s]Frame Count Differ for Source 0004.mkv: 0/88
  6%|███████▉                                                                                                                       | 88/1416 [00:09<02:25,  9.14fr/s]Frame Count Differ for Source 0006.mkv: 0/142
 16%|████████████████████▍                                                                                                         | 230/1416 [00:13<01:41, 11.68fr/s]Frame Count Differ for Source 0007.mkv: 0/132
 26%|████████████████████████████████▏                                                                                             | 362/1416 [00:16<01:09, 15.07fr/s]Frame Count Differ for Source 0001.mkv: 0/146
Frame Count Differ for Source 0003.mkv: 0/108
Frame Count Differ for Source 0005.mkv: 0/46
 47%|██████████████████████████████████████████████████████████▉                                                                   | 662/1416 [00:20<00:21, 35.79fr/s]Frame Count Differ for Source 0000.mkv: 0/295
 68%|█████████████████████████████████████████████████████████████████████████████████████▏                                        | 957/1416 [00:30<00:13, 32.93fr/s]Frame Count Differ for Source 0002.mkv: 0/459
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1416/1416 [00:43<00:00, 33.70fr/s]Concatenation failed

**Comment by master-of-zen** [comment]
That means that something in aomenc setup is wrong and encoding started and immediately crashed.
That is why frame count differ show zero, because there is no encoded frames

**Comment by ibex-are-goats** [comment]
Can you get VMAF to work yourself? It works without the --tune=VMAF. Maybe I'm missing a command to point the tuning to the models folder? I don't know because I've never done VMAF before.

**Comment by master-of-zen** [comment]
```
[zen@arch tests]$ av1an.py -i test.mp4 -v ' --tune=vmaf '
100%|█████████████████████████████████████████████████| 1290/1290 [00:01<00:00, 916.91frames/s]
Queue: 14 Workers: 6 Passes: 2
Params:  --tune=vmaf 
  4%|██▏                                                   | 52/1290 [03:28<1:22:32,  4.00s/fr]```
vmaf in lower score + make sure you use vmaf aom

**Comment by master-of-zen** [comment]
Do you fixed you issue?

**Comment by ibex-are-goats** [comment]
I fund out that I need to do --vmaf-model-path=vmaf_v0.6.1.pkl

But now it's just stuck at 0% progress and 100% CPU indefinitely. So I don't know what's wrong. But you can close this if it's nothing to do with av1an :)

av1an.exe -i sample.mkv -v " --tune=vmaf --vmaf-model-path=vmaf_v0.6.1.pkl"
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1416/1416 [00:04<00:00, 285.34frames/s]
Queue: 8 Workers: 6 Passes: 2
Params:  --tune=vmaf --vmaf-model-path=vmaf_v0.6.1.pkl
  0%|                                                                                                                                                            | 0/1416 [00:00<?, ?fr/s]

**Comment by master-of-zen** [comment]
It's working :) frame progress shows when you have finished chunks
Cheers :+1:
