### ISSUE TITLE
[Error] thread '<unnamed>' panicked at 'No match found for params:

### ISSUE THREAD

**Issue by ahmadrr** [master-of-zen/Av1an#352]
Same error whether cmd running as admin or not. Latest Av1an, python, vapoursynth, ffms, lsmash, ffmpeg, rust, aomenc. aomenc.exe in the same folder as av1an.exe 

cmd output

D:\Video\av1\target\release>av1an -v " --row-mt=0 --enable-ab-partitions=0 --auto-alt-ref=1 --bit-depth=10 --cpu-used=6 --end-usage=q --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --tune-content=screen --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=35 --enable-chroma-deltaq=1 " --target-quality 94 --vmaf-path "vmaf_v0.6.1.json" --vmaf -p 1 -w 3 -x 250 --keep -r -i "D:\0proses\Parasit Kulit.mkv" -o "d:\Parasit Kulit.mkv"
Queue: 65 Workers: 3 Passes: 1
Params: --row-mt=0 --enable-ab-partitions=0 --auto-alt-ref=1 --bit-depth=10 --cpu-used=6 --end-usage=q --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --tune-content=screen --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=35 --enable-chroma-deltaq=1

[00:02:45] [---------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/14527 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'No match found for params: [
    "aomenc",
    "--passes=1",
    "--row-mt=0",
    "--enable-ab-partitions=0",
    "--auto-alt-ref=1",
    "--bit-depth=10",
    "--cpu-used=6",
    "--end-usage=q",
    "--threads=1",
    "--tile-columns=0",
    "--tile-rows=0",
    "--lag-in-frames=35",
    "--tune-content=screen",
    "--arnr-maxframes=15",
    "--arnr-strength=6",
    "--enable-fwd-kf=35",
    "--enable-chroma-deltaq=1",
    "-o",
    ".72833eb\\encode\\00012.ivf",
    "-",
]', av1an-core\src\lib.rs:104:3
[00:02:54] [---------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/14527 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'No match found for params: [
    "aomenc",
    "--passes=1",
    "--row-mt=0",
    "--enable-ab-partitions=0",
    "--auto-alt-ref=1",
    "--bit-depth=10",
    "--cpu-used=6",
    "--end-usage=q",
    "--threads=1",
    "--tile-columns=0",
    "--tile-rows=0",
    "--lag-in-frames=35",
    "--tune-content=screen",
    "--arnr-maxframes=15",
    "--arnr-strength=6",
    "--enable-fwd-kf=35",
    "--enable-chroma-deltaq=1",
    "-o",
    ".72833eb\\encode\\00013.ivf",
    "-",
[00:03:01] [---------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/14527 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'No match found for params: [
    "aomenc",
    "--passes=1",
    "--row-mt=0",
    "--enable-ab-partitions=0",
    "--auto-alt-ref=1",
    "--bit-depth=10",
    "--cpu-used=6",
    "--end-usage=q",
    "--threads=1",
    "--tile-columns=0",
    "--tile-rows=0",
    "--lag-in-frames=35",
    "--tune-content=screen",
    "--arnr-maxframes=15",
    "--arnr-strength=6",
    "--enable-fwd-kf=35",
    "--enable-chroma-deltaq=1",
    "-o",
    ".72833eb\\encode\\00011.ivf",
    "-",
]', av1an-core\src\lib.rs:104:3
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core\src\broker.rs:58:35
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core\src\lib.rs:1246:21
---------------------------------------------------------------------------------------------------------------------
log.log

INFO [av1an_core] SC: Found 65 scenes
INFO [av1an_core] SC: Applying extra splits every 250 frames
INFO [av1an_core] SC: Now at 65 scenes
INFO [av1an_core] Resuming...
INFO [av1an_core] Resumed with 0 encoded clips done
INFO [av1an_core::broker] Enc: 11, 247 fr
INFO [av1an_core::broker] Enc: 13, 247 fr
INFO [av1an_core::broker] Enc: 12, 247 fr
INFO [av1an_core::target_quality] Chunk: 00012, Rate: 4, Fr 247
INFO [av1an_core::target_quality] Probes [(100.0, 15), (92.416913, 33), (91.78454, 34), (91.04943, 35)]
INFO [av1an_core::target_quality] Target Q: 29 VMAF: 94.00
INFO [av1an_core::target_quality] Chunk: 00013, Rate: 4, Fr 247
INFO [av1an_core::target_quality] Probes [(100.0, 15), (92.583726, 33), (92.097017, 34), (91.41944, 35)]
INFO [av1an_core::target_quality] Target Q: 29 VMAF: 94.00
INFO [av1an_core::target_quality] Chunk: 00011, Rate: 4, Fr 247
INFO [av1an_core::target_quality] Probes [(100.0, 15), (93.164436, 33), (92.439791, 34), (91.583925, 35)]
INFO [av1an_core::target_quality] Target Q: 30 VMAF: 94.00

**Comment by master-of-zen** [comment]
You didn't added `--cq-level=20` to your encoding parameters

**Comment by ahmadrr** [comment]
Okay thanks for the tip, I thought specifying vmaf target is enough, The encode ran fine, but vmaf threw error after processing for several minutes (no score). Not a dealbreaker though, I can calculate vmaf externally via ffmpeg, but it would be nice if it works.

D:\Video\av1\target\release>av1an -v " --row-mt=0 --enable-ab-partitions=0 --auto-alt-ref=1 --bit-depth=10 --cpu-used=6 --end-usage=q --cq-level=30 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --tune-content=screen --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=35 --enable-chroma-deltaq=1 " --target-quality 94 --vmaf-path "vmaf_v0.6.1.json" --vmaf -p 1 -w 3 -x 250 --keep -r -i "D:\0proses\Parasit Kulit.mkv" -o "d:\Parasit Kulit.mkv"
Queue: 65 Workers: 3 Passes: 1
Params: --row-mt=0 --enable-ab-partitions=0 --auto-alt-ref=1 --bit-depth=10 --cpu-used=6 --end-usage=q --cq-level=30 --threads=1 --tile-columns=0 --tile-rows=0 --lag-in-frames=35 --tune-content=screen --arnr-maxframes=15 --arnr-strength=6 --enable-fwd-kf=35 --enable-chroma-deltaq=1

[02:20:12] [#################################################################################################################################################################] 100% 14527/14527 (1.73 fps, eta 0s)
:: VMAF Run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Can't open file "\\\\?\\D:\\Parasit Kulit.json"

Caused by:
    The system cannot find the file specified. (os error 2)', av1an-core\src\lib.rs:220:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
