### ISSUE TITLE
Support fast first pass

### ISSUE THREAD

**Issue by utack** [master-of-zen/Av1an#36]
It would be great if you could add an option to a fast first pass for rav1e and SVT-AV1
Either bump the speed by +n levels, or use a fixed very high speed level
Thank you for consideration

**Comment by master-of-zen** [comment]
Is that verified that it works and don't produce any errors at time of encoding/decrease quality of encoding?

**Comment by nathanielcwm** [comment]
What about aomenc too?

**Comment by master-of-zen** [comment]
It's should be addressed to encoder developers
