### ISSUE TITLE
Encoding fails with "FRAME MISMATCH" when encoding with aomenc --enable-keyframe-filtering=2

### ISSUE THREAD

**Issue by shssoichiro** [master-of-zen/Av1an#367]
This is likely due to the fact that keyframe filtering mode 2 is not supported by all decoders. Whatever decoder av1an is using is failing to decode the files.

I'll self-assign this and take a look.

**Comment by master-of-zen** [comment]
@shssoichiro It's because `--enable-keyframe-filtering=2` fails to work with ffmpeg decode.
Av1an use `ffmpeg -c copy`  to count number of frames, and that just reports 0 if you use `--enable-keyframe-filtering=2`

**Comment by shssoichiro** [comment]
I'll see if there's a way to work around it. There are like 10 different ways to get the frame count with ffmpeg, hopefully one of them will work.
