### ISSUE TITLE
encoding error: invalid literal for int()

### ISSUE THREAD

**Issue by keturn** [master-of-zen/Av1an#38]
I ran `av1an -i /path/to/myvideo.mp4`. It ran through its first progress bar, and then crashed with this message:

```Encoding error: invalid literal for int() with base 10: '/…/Av1an/.temp/encode/0.ivf: No such file or directory'```

Looking in the log shows some

```
/bin/sh: 1: aomenc: not found
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
```

Could break this down as several issues:

- [ ] print (or at least log) stack trace on fatal error so we can tell where it crashed
- [ ] `call_cmd` could check the exit code of the subprocess, so we can tell when the subprocess failed instead of passing back its stderr as if it was successful.
- [x] check for required dependencies earlier to let the user know they're missing something before we spend time encoding

**Comment by master-of-zen** [comment]
/bin/sh: 1: aomenc: not found
Aom encoder is simply not installed

**Comment by master-of-zen** [comment]
Okay, will think what could be done about that

**Comment by master-of-zen** [comment]
Fixed in https://github.com/master-of-zen/Av1an/commit/a6e46541b1479411a56d0c73341946246fe7cbb9
