### ISSUE TITLE
How to encode in 8 bit?

### ISSUE THREAD

**Issue by quasin** [master-of-zen/Av1an#380]
Hello.
I am encode with this parametres:
```docker run --privileged -v "/home/bitcoren/videos":/videos --user $(id -u):$(id -g) -it --rm masterofzen/av1an:master -i "input.mp4" --encoder aom -v " --input-bit-depth=8 --bit-depth=8 --width=1280 --height=720 --cpu-used=4 --end-usage=q --cq-level=30 --threads=8 " --min-q 10 --max-q 55 -w 8 -a " -c:a libopus -ac 2 -b:a 192k " --keep --vmaf --target-quality 95 -o output.webm```
But output file is 10bit.
How can i encode in 8 bit?

**Comment by redzic** [comment]
@bitcoren Set `--pix-format yuv420p` in av1an options
