### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#388]
The last "release" on github dates to july of last year when the project was still running on python.

Maybe we should create a new release that explains the changes.

**Comment by BlueSwordM** [comment]
A new release should be coming soon now that rav1e 0.5.0 is a thing.

**Comment by svenstaro** [comment]
As someone looking forward to package this in Arch Linux official repos, a new release would be appreciated.

**Comment by master-of-zen** [comment]
@svenstaro @lastrosade @BlueSwordM 
Yep, new release done
