### ISSUE TITLE
Failed to split encoder agruments

### ISSUE THREAD

**Issue by phanluchoaofficial20** [master-of-zen/Av1an#397]
Hello,

I have used your Av1an for encode but I have problem when running command is I got error: "Failed to split encoder agruments" . I don't know a reason why, can anyone help me ?

This is error:

D:\Av1an-1.12>av1an -i latmatnhacokhach.mkv -e x265 -v " --crf 10 --keyint 240 --preset slow --rc-lookahead 48 --aq-mode 3 --colorprim bt709 --transfer bt709 --colormatrix bt709 ' --temp D:\Av1an-1.12\av1antemp -o testvideo1.mkv
Error: Failed to split video encoder arguments

Thanks!

**Comment by redzic** [comment]
You have to use a double quote in both instances. The correct comment would be this:

```
av1an -i latmatnhacokhach.mkv -e x265 -v " --crf 10 --keyint 240 --preset slow --rc-lookahead 48 --aq-mode 3 --colorprim bt709 --transfer bt709 --colormatrix bt709 " --temp D:\Av1an-1.12\av1antemp -o testvideo1.mkv
```

**Comment by phanluchoaofficial20** [comment]
> You have to use a double quote in both instances. The correct comment would be this:
> 
> ```
> av1an -i latmatnhacokhach.mkv -e x265 -v " --crf 10 --keyint 240 --preset slow --rc-lookahead 48 --aq-mode 3 --colorprim bt709 --transfer bt709 --colormatrix bt709 " --temp D:\Av1an-1.12\av1antemp -o testvideo1.mkv
> ```

That means, I have to run 2 time for work ?

**Comment by redzic** [comment]
No, it's all a single command. By "both instances" I meant the fact that there are 2 quotation mark characters. They both have to be the same character. So they can either both be `"`, or both `'`, but you cannot mix both of them in the same command.

**Comment by phanluchoaofficial20** [comment]
> You have to use a double quote in both instances. The correct comment would be this:
> 
> ```
> av1an -i latmatnhacokhach.mkv -e x265 -v " --crf 10 --keyint 240 --preset slow --rc-lookahead 48 --aq-mode 3 --colorprim bt709 --transfer bt709 --colormatrix bt709 " --temp D:\Av1an-1.12\av1antemp -o testvideo1.mkv
> ```

But i cannot see anyfile on my temp folder ? Such as, encode and split folder, I don't see any file

**Comment by redzic** [comment]
@phanluchoaofficial20 Not sure, but can you check if there are still no files even after scene detection has finished? Also, sometimes the default mode of scene detection (which is the most accurate) can be slow in high resolution videos. You can use `--sc-method=fast --sc-downscale-height=720` to speed up the scene detection.
