### ISSUE TITLE
x265 [error]: unable to open input file <->

### ISSUE THREAD

**Issue by phanluchoaofficial20** [master-of-zen/Av1an#398]
Hello,

Is me again, now i got this error after I add crop option and scene detection finished. 

This is my error: 

"[00:00:00] [----------------------------------------------]   0% 0/143836 (0.00 fps, eta 0s)
WARN [av1an_core::broker] Encoder failed (on chunk 628) with exit code: 1:
        x265 [error]: unable to open input file <->"

This is my command:  av1an -i latmatnhacokhach.mkv -e x265 -v " --bitrate 8000 --keyint 240 --rc-lookahead 48 --aq-mode 3 --colorprim bt709 --transfer bt709 --colormatrix bt709 " --sc-method=fast -f " --vf crop=1920:720:0:180 " --temp D:\Av1an-1.12\av1antemp -o testvideo1.mkv

![Untitled](https://user-images.githubusercontent.com/86090065/139795108-78004ece-8133-4095-8486-66456603e1a0.png)

I don't know what problem with this. Can anyone help me ?

Thanks!

**Comment by Werve** [comment]
I've the same problem, how you resolved?
Seems like a process use that chunk files (maybe antivirus?) and release it after some seconds but if is not ready at first try av1an stop encoding.

**Comment by georgesaumen** [comment]
Yes, I have fixed. You have to use raw video file input (Y4M or YUV) for
encode

Vào Th 4, 6 thg 4, 2022 lúc 13:30 Werve ***@***.***> đã viết:

**Comment by georgesaumen** [comment]
> I've the same problem, how you resolved? Seems like a process use that chunk files (maybe antivirus?) and release it after some seconds but if is not ready at first try av1an stop encoding.

I dont remembered, because I only use this for test. I have remembered that I change my video to mp4 file input or raw video input and run

**Comment by Werve** [comment]
I use it with Nmkoder and actually if i skip the scene detector it encode the same file, so more likely a process didn't release in time the chunks
