### ISSUE TITLE
-c mkvmerge on Windows will break due to long command/paths

### ISSUE THREAD

**Issue by n00mkrad** [master-of-zen/Av1an#405]
From what I've gathered, mkvmerge will not work properly if there's more than 739 chunks as the command length exceeds 8192 chars. 

This means on Windows there needs to be a workaround for this, especially when using ` --enable-keyframe-filtering=2` with aomenc as this breaks ffmpeg muxing, so mkvmerge is the only way to mux those.

**Comment by silverbacknet** [comment]
Oh, if that's the problem then the workaround (without going into the API) would be to just do them in sets of 100 chunks (or whatever) at a time, then append those superchunks in turn.

**Comment by n00mkrad** [comment]
> Oh, if that's the problem then the workaround (without going into the API) would be to just do them in sets of 100 chunks (or whatever) at a time, then append those superchunks in turn.

This is exactly what I would've done and might implement in nmkoder unless av1an implements it directly, yes.

**Comment by n00mkrad** [comment]
Av1an just tried to run an mkvmerge command that was 139,904 chars long, and it failed without error.

Is it possible to use relative paths here? This would drastically cut down the length of the command.

Instead of `mkvmerge -o $outpath/path/to/dir/000.ivf + /path/to/dir/001.ivf + /path/to/dir/002.ivf + ...` use `cd /path/to/dir && mkverge -o $outpath 000.ivf + 001.ivf + 002.ivf`, you get the point.

**Comment by n00mkrad** [comment]
Reproduced once again, the console output:

`Error: Failed to execute mkvmerge command for concatenation

Caused by:
    The filename or extension is too long. (os error 206)`

**Comment by redzic** [comment]
Should be fixed as of #521
