### ISSUE TITLE
-c mkvmerge is broken on Windows regardless of chunk amount

### ISSUE THREAD

**Issue by n00mkrad** [master-of-zen/Av1an#416]
mkvmerge fails every time, tested by me and @Simulping (Discord):

![Taskmgr_uivEVdhWzJ](https://user-images.githubusercontent.com/61149547/142582565-fed81669-32c0-4e56-aaac-b1a86ccd835b.png)

Seems to be unrelated to the chunk count so the cmd character limit shouldn't be the problem in this case.

**Comment by redzic** [comment]
Should be fixed now, feel free to reopen if there are still issues in some cases
