### ISSUE TITLE
ffmpeg::Error Stream not found

### ISSUE THREAD

**Issue by niklaskorz** [master-of-zen/Av1an#426]
I'm trying to convert the [Sintel open movie](http://ftp.nluug.nl/pub/graphics/blender/demo/movies/Sintel.2010.1080p.mkv) to AV1 using av1an default settings.

I am getting the following output for tag `0.2.0`:

```
Scene detection
  [00:02:10] [##################################################################] 100% 21312/21312 (162.78 fps, eta 0s)
Queue: 138 Workers: 3 Passes: 2
Params: --threads=8 --cpu-used=6 --end-usage=q --cq-level=30 --tile-columns=2 --tile-rows=1 --kf-max-dist=240 --kf-min-dist=12
⠋ [00:01:23] [#>-------------------------------------------------------------------]   2% 409/21312 (4.84 fps, eta 72m)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)', av1an-core/src/broker.rs:128:69
⠒ [00:02:27] [##>------------------------------------------------------------------]   3% 682/21312 (4.58 fps, eta 75m)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)⠠ [00:02:30] [##>------------------------------------------------------------------]   3% 713/21312 (4.72 fps, eta 73m)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)', av1an-core/src/broker.rs:128:69
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/broker.rs:53:35
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/settings.rs:868:21
```

The same happens for the most recent commit https://github.com/master-of-zen/Av1an/commit/57cbb2930664d26fdd9b8b6624e2190ee07a2f20

```
Scene detection
  00:02:10 [###################################################################] 100%  21312/21312 (163.14 fps, eta 0s)
Queue 138 Workers 3 Passes 2
Params: --threads=8 --cpu-used=6 --end-usage=q --cq-level=30 --tile-columns=2 --tile-rows=1 --kf-max-dist=240 --kf-min-dist=12
⠐ 00:01:17 [#>--------------------------------------------------------------------]   2%  407/21312 (5.19 fps, eta 67m)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)', av1an-core/src/broker.rs:206:70
⠁ 00:02:20 [##>-------------------------------------------------------------------]   3%  687/21312 (4.88 fps, eta 70m)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)⠐ 00:02:22 [##>-------------------------------------------------------------------]   3%  711/21312 (4.97 fps, eta 69m)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)', av1an-core/src/broker.rs:206:70
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/broker.rs:161:35
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/settings.rs:944:21
```

**Comment by redzic** [comment]
@niklaskorz It doesn't happen for me with the same input file you uploaded, my guess is that your ffmpeg build is somehow too outdated or otherwise misconfigured. Make sure your ffmpeg build has libdav1d enabled (you may have to recompile av1an since it links to the ffmpeg C libraries), since it seems as though it cannot detect the AV1 stream in the encoded chunks (the error means that it could not get the number of frames in the encoded chunk, which av1an uses as a sanity check to make sure that are no frame drops).

**Comment by niklaskorz** [comment]
I've built the docker image I executed av1an from the repo's master branch Dockerfile, so the ffmpeg build used is the one from `luigi311/encoders-docker:20210901`.

**Comment by redzic** [comment]
I remember we downgraded from `luigi311/encoders-docker:latest` to `luigi311/encoders-docker:20210901` since the latest version was apparently experimental and was causing some problems for us. I just tried `luigi311/encoders-docker:latest` again but it still seems to have issues for me. @luigi311 will know more about that than me.

For now though you can try `masterofzen/av1an:latest`, which should work.

**Comment by niklaskorz** [comment]
I'll try that, thanks!

**Comment by luigi311** [comment]
Yeah seems to be an issue with vapoursynth. I am currently in the process of migrating over to all static builds for it but running into issues with x265 not building statically when including 8/10/12 bit support so i will skip that for now just to get the fix up and then get that building statically later once i get a solution from the x265 bug tracker.
