### ISSUE TITLE
svt-vp9 missing in Rust rewrite

### ISSUE THREAD

**Issue by niklaskorz** [master-of-zen/Av1an#427]
It looks like svt-vp9 was supported before the Rust rewrite but is now missing. The README still mentions it everywhere but for the "encoder" parameter.

**Comment by n00mkrad** [comment]
It is indeed unsupported.

The readme is outdated.

**Comment by redzic** [comment]
Thanks, I removed the references to SVT-VP9 in the readme. We dropped support for SVT-VP9 because it does not support 10-bit encoding (which also means that it does not work with our default pixel format, yuv420p10le).
