### ISSUE TITLE
Support ISOBMFF container output

### ISSUE THREAD

**Issue by akudan** [master-of-zen/Av1an#52]
ISOBMFF (e.g. MP4) output should be supported since the spec for AV1 support is more mature and widely adopted than even for MKV.

https://en.wikipedia.org/wiki/AV1#Supported_container_formats
https://en.wikipedia.org/wiki/ISO/IEC_base_media_file_format

**Comment by master-of-zen** [comment]
MKV used as default output format to avoid any kind of muxing errors, which can be possible if avi/mp4 etc.
If any other extension is needed user can copy streams using ffmpeg to desired container.
