### ISSUE TITLE
Add a Windows compilation guide

### ISSUE THREAD

**Issue by shssoichiro** [master-of-zen/Av1an#529]
Compiling av1an on Windows is a significant endeavour. We should document, and link in the readme, instructions for compiling av1an with ffmpeg and vapoursynth support on Windows.

**Comment by Werve** [comment]
I was also looking for a guide because of some issues with dependencies for ffmpeg-sys-next.
I found a working one here:
https://www.reddit.com/r/AV1/comments/s8151l/how_to_compile_av1an_on_windows_without_breaking/
