### ISSUE TITLE
Error: svt-av1 does not support YUV422P

### ISSUE THREAD

**Issue by cagelight** [master-of-zen/Av1an#536]
av1an seems to insist that I'm trying to encode yuv422p despite:
`--pix-format yuv420p`
`-f "format=yuv420p"`
`-v "--color-format 1"`
Am I missing something? After all 3 of those options, I wouldn't think it'd be trying to encode a yuv422p video.

av1an 0.3.0

**Comment by menditsa** [comment]
Are those even settings for svt ?
Looks like they are for aom.

**Comment by cagelight** [comment]
The first one is a setting for av1an, the second is an ffmpeg filter, and third is in fact an SVT-AV1 setting (see: https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md)

**Comment by menditsa** [comment]
--color-format states "Color format, only yuv420 is supported at this time [0: yuv400, 1: yuv420, 2: yuv422, 3: yuv444"

**Comment by cagelight** [comment]
And? I pass `--color-format 1` which is *clearly* marked as yuv420.

**Comment by menditsa** [comment]
But you're saying svt does not support yuv422p and that's what you want to encode to.

**Comment by cagelight** [comment]
I'm sorry, but you clearly have insufficient reading comprehension and experience with this issue. Nowhere did I state that was what I was trying to do. In fact it's plainly obvious that I'm trying to encode yuv420.

**Comment by menditsa** [comment]
Clearly I don't:

time fd -I -e .ts -j 1 -x av1an --verbose --split-method av-scenechange -m lsmash -c mkvmerge --sc-pix-format=yuv420p --sc-method=fast --sc-downscale-height=240 -e svt-av1 -v " --rc 0 --crf 40 --preset 6 --irefresh-type 1 --keyint 240 --input-depth 10 --enable-overlays 1 --lp 14 --enable-tf 0 " -a " -c:a libopus -b:a 96k " -s '{.}.json' -i '{}' -o '{.}_SVT_AV1.mkv'

Does not produce a 422 as your snarky comment suggests.

**Comment by cagelight** [comment]
You actually inadvertently solved my problem, `--sc-pix-format=yuv420p` was what I needed, you should have just opened with that. Thanks anyway.

**Comment by redzic** [comment]
Reopening, as the error message for this case is completely misleading, and the results of the scene detection should be separate from the encoder.

**Comment by shssoichiro** [comment]
> I'm sorry, but you clearly have insufficient reading comprehension and experience with this issue. Nowhere did I state that was what I was trying to do. In fact it's plainly obvious that I'm trying to encode yuv420.

This is your first and only warning. Don't be a dick to other people in our repo.

**Comment by cagelight** [comment]
> This is your first and only warning. Don't be a dick to other people in our repo.
Sorry but that's a no-go from me. He came in here refusing to understand what I was saying and being confrontational. And now you issue that warning to me but not to him? Get off your high horse.

**Comment by redzic** [comment]
Closing this issue in favor of #539.
