### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by eblanca** [master-of-zen/Av1an#55]
It should be clarified that PIP means PIP3, as in distributions using both python2 and python3, PIP will install stuff for python2 (and av1an won't be able to find what it needs).

**Comment by master-of-zen** [comment]
Clarified https://github.com/master-of-zen/Av1an/commit/d3b64004df1587e2d461ec29a143f1d3bff51ec3

**Comment by master-of-zen** [comment]
Is that right? If so - close

**Comment by eblanca** [comment]
I would include a further modification on page https://pypi.org/project/Av1an/
for the statement `pip install -r requirements.txt` which is very useful yet misleading.
Thanks!

**Comment by master-of-zen** [comment]
I didn't seen it's not up to date to current git readme

**Comment by master-of-zen** [comment]
@eblanca updated PYPI description
