### ISSUE TITLE
Feature request: Allow Av1an to cache/save scene detection results

### ISSUE THREAD

**Issue by Bl4cKn1gh7** [master-of-zen/Av1an#554]
Av1an currently does a scene detection pass that's separate from actual encoding. In some cases, it also computes a file hash of the input file. It would be useful if it could either cache or save the results of scene detection for use during future encodes. if using a .json file, it could be compared or named to the hash of the input file to make sure that the scene cuts are accurate.

Scene detection for some large files can be slow at times, so it could be a useful feature.

**Comment by lastrosade** [comment]
Currently av1an has
`    -s, --scenes <SCENES>
            File location for scenes`
