### ISSUE TITLE
Specify path to photon noise model to avoid recalculating it.

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#567]
Currently photon noise generation is generated when the encode start and is kept in the temp dir.

An argument like `--photon-noise-model-path somemodel.tbl` would allow us to reuse the model when encoding the same video.

**Comment by shssoichiro** [comment]
I'm not sure how much benefit this provides. Generating the photon noise table is a very quick and deterministic process. Less than 1 second.

Is the concern that the files are cluttering the temp directory? Maybe we can find a way to clean them out even if the encode is interrupted. They should be taking up minimal space though, as these files are also about half a KB each.

**Comment by lastrosade** [comment]
I just ran some tests and it takes up to a minute to generate the model on a 1800 frame sample video of mine.

**Comment by shssoichiro** [comment]
That seems unusual. I'll do some testing and see what's going on with that.

**Comment by lastrosade** [comment]
I can't reproduce the issue anymore when rerunning the same tests.
