### ISSUE TITLE
av1an doesn't find up-to-date Python 3 on Ubuntu 18.04

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#58]
On Linux Mint 19 (based on Ubuntu 18.04), av1an can't find the up-to-date version of Python it needs. When trying to execute, it just outputs `Python 3.7+ required`.

The default version of the `python3` binary on Ubuntu 18.04 is Python 3.6.9. According to advice on various StackExchange sites, this default cannot be changed without potentially breaking the system. However, newer versions are available in the repositories can be installed alongside it. Both Python 3.7 and 3.8 are available and can be accessed from the `python3.7` and `python3.8` binaries. I have Python 3.8 installed, but av1an still exits with the "Python 3.7+ required" error message.

**Comment by nathanielcwm** [comment]
Did you install it with pip?

**Comment by master-of-zen** [comment]
For using custom binaries Av1an must be executed as script `python3.7 av1an.py`

**Comment by master-of-zen** [comment]
@veikk0 Av1an 1.9 python requirement lowered to 3.6, update and check is that fixes your issue.

**Comment by veikk0** [comment]
Many thanks, that fixed the problem.

**Comment by master-of-zen** [comment]
@veikk0 :+1:
