### ISSUE TITLE
Av1an doesn't encode the entire video

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#60]
Running into a strange problem. I'm trying to encode [big_buck_bunny_1080p_h264.mov](https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov), but only about a minute of the file gets encoded.

Command: `av1an -i big_buck_bunny_1080p_h264.mov -enc aom -w 12 --passes 1 --logging bbb.av1an.log -v " --cpu-used=6 --end-usage=q --cq-level=40 " -o bbb.av1an.RF40.webm`

The scene detection seems to run just fine, it processes 14315/14315 frames. Encoding starts fine as well, Av1an reports "Queue: 80 Workers: 12 Passes: 1". The encode finishes in 649.7s after processing 1534/14315 frames, which is 11% according to the progress bar.

Log file: [bbb.av1an.log.log](https://github.com/master-of-zen/Av1an/files/4620407/bbb.av1an.log.log)

**Comment by master-of-zen** [comment]
Fixed in https://github.com/master-of-zen/Av1an/commit/d97fdcd839246667ccd8d079f96e5aa97ac523b7
