### ISSUE TITLE
Crash on Ubuntu 18.04, installing distro package python3-opencv fixes the issue

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#61]
I just tried to install & run Av1an in a fresh Ubuntu 18.04 VM. I installed Av1an via pip, but when trying to run Av1an, it hard crashed with the following error:

    /usr/bin/python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
    /usr/bin/python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
    Segmentation fault (core dumped)

Installing the distro-provided package `python3-opencv` fixed the issue.

**Comment by master-of-zen** [comment]
https://github.com/master-of-zen/Av1an/commit/c278443ae4a570149acfb31c6eb9e338123f28fd
