### ISSUE TITLE
Faster scene detection

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#63]
The scene detection is relatively fast, but can still take quite a bit of time when you're encoding a movie. Looking at the CPU usage, the scene detection seems to be using only a single thread. Would it be possible to use multiple threads for this?

It also occured to me that having the option to downscale the source for the purpose of scene detection might speed things up.

**Comment by master-of-zen** [comment]
PySceneDetect is multi-threaded and downscale video automatically.
To avoid issue spam and provide better communication please join [AV1 Discord](https://discord.gg/2n5UMYK) and write in #Av1an . :+1:

**Comment by veikk0** [comment]
Well, this is a bit strange. I have one file (a 1080p mkv copied from a Blu-ray) for which Av1an's scene detection only uses a single thread for some reason. But with another file I'm testing (720p in resolution), multiple threads are used.

Doesn't make any sense. How would I even troubleshoot this? Does it have something to do with the source files? The 1080p file for which only a single thread is used in scene detection uses the VC-1 codec. For any H.264 files, multithreaded scene detection seems to work fine.

**Comment by BlueSwordM** [comment]
> Well, this is a bit strange. I have one file (a 1080p mkv copied from a Blu-ray) for which Av1an's scene detection only uses a single thread for some reason. But with another file I'm testing (720p in resolution), multiple threads are used.
> 
> Doesn't make any sense. How would I even troubleshoot this? Does it have something to do with the source files? The 1080p file for which only a single thread is used in scene detection uses the VC-1 codec. For any H.264 files, multithreaded scene detection seems to work fine.

This is very late, but VC-1 decoding is single threaded.

Also scene detection has become a lot faster since then.
