### ISSUE TITLE
Cannot transcode using x264: could not open input file `-'

### ISSUE THREAD

**Issue by i0ntempest** [master-of-zen/Av1an#645]
log file:
```
INFO [av1an_core::settings] temporary directory: .3d98e03
INFO [av1an_core::settings] scenecut: found 3 scene(s) [with extra_splits(240 frames): 38]
INFO [av1an_core::settings] Segmenting video
INFO [av1an_core::settings] Segment done
WARN [av1an_core::broker] Encoder failed (on chunk 18):
encoder crashed: exit status: 255
stdout:

stderr:
        y4m [error]: bad sequence header length
        x264 [error]: could not open input file `-'


source pipe stderr:

ffmpeg pipe stderr:
        av_interleaved_write_frame(): Broken pipe
        Error writing trailer of pipe:: Broken pipe

WARN [av1an_core::broker] Encoder failed (on chunk 18):
encoder crashed: exit status: 255
stdout:

stderr:
        y4m [error]: bad sequence header length
        x264 [error]: could not open input file `-'


source pipe stderr:

ffmpeg pipe stderr:
        av_interleaved_write_frame(): Broken pipe
        Error writing trailer of pipe:: Broken pipe

ERROR [av1an_core::broker] [chunk 18] encoder crashed 3 times, shutting down worker
ERROR [av1an_core::broker] [chunk 18] encoder crashed: exit status: 255
stdout:

stderr:
        y4m [error]: bad sequence header length
        x264 [error]: could not open input file `-'


source pipe stderr:

ffmpeg pipe stderr:
        av_interleaved_write_frame(): Broken pipe
        Error writing trailer of pipe:: Broken pipe
```
I'm on macOS and I built av1an using MacPorts (I maintain av1an port in MacPorts).
I tried multiple videos in multiple formats, only 2 video worked and other videos will all cause this error. If needed I can provide those files.

**Comment by silverbacknet** [comment]
That almost always indicates a mismatch between the version of ffmpeg decoding the video and the one consuming it. That seems extremely odd, and even more odd that it would simply work after all on two files (resolution, maybe?). I'm not familiar enough with MacOS to know how to track that down.

**Comment by i0ntempest** [comment]
Most likely not resolution related, I have a 1764*1440 video that'll work, a standard 1080P video that will not work, then a 720P one that'll also work. Also could you elaborate on that version mismatching thing? What do you mean by the ffmpeg version "consuming" the video? I know I have ffmpeg 4.4.1 installed.

**Comment by i0ntempest** [comment]
Just found out: that working 720P video is h264 encoded flv, I remux it with `ffmpeg -c copy` into a mp4 container, suddenly it does not work.
