### ISSUE TITLE
Cpu usage on scene detection

### ISSUE THREAD

**Issue by draco1544** [master-of-zen/Av1an#665]
How i can speed up the scene detection ? My i7-12700k is at 64% usage, its possible to hit 100% ? I use Lsmach

**Comment by CartoonFan** [comment]
Looks like there's a PR in the works to speed up scene detection: https://github.com/master-of-zen/Av1an/pull/627

**Comment by BlueSwordM** [comment]
What binary are you using, and what version of av1an are you otherwise using?
