### ISSUE TITLE
Multiple resolutions output

### ISSUE THREAD

**Issue by phpb-com** [master-of-zen/Av1an#666]
Hi, after struggling to find the answer I wanted to check here if it was possible to output multiple resolutions instead of rerunning av1an with the difference in ffmpeg filter. Or, at least, can we somehow save the progress of the previous run so av1an does not have to probe quality for VMAF over and over for each resolution. Thanks.

**Comment by BlueSwordM** [comment]
That could work, but to avoid redoing the calculation, we'd need to do a lot of testing for each encoder to assign interpolation curve values/formulas to correctly scale quality levels based on resolutions.
