### ISSUE TITLE
--workers ignored for second pass

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#67]
My CPU has 6 cores and 12 threads. By default, Av1an defaults to using 6 workers (not sure if this is a bug or intended behavior). EDIT: Probably related to [this line](https://github.com/master-of-zen/Av1an/blob/86dac0066e509a4eb93b1a793cdcbc81cd04a501/av1an.py#L299). os.cpu_count() [returns the number of physical cores](https://docs.python.org/3.8/library/os.html#os.cpu_count), not the number of usable threads.

I use `--workers 12` to override the default. Scene detection and first pass use 12 processes, but the second pass only uses 6 workers. Av1an reports this in its CLI output (Queue: 80 Workers: 6 Passes: 2), and I verified this with System Monitor, there are only 6 encoding processes running and about 50% of the CPU is being used.

I'm using the latest git and invoking Av1an with the following command:

>python3 ~/Av1an/av1an.py -i big_buck_bunny_1080p_h264.mov --passes 2 --workers 12 -v '--end-usage=q --kf-max-dist=600 --cpu-used=6 --cq-level=42' --output_file bbbtest.mkv

I'm on Linux Mint 19.

**Comment by master-of-zen** [comment]
It's recommended to use 1 worker per real core.  Encoder by default will be limited to single thread, so for better multi threading use `--threads=4` into your command. I recommend this command like this:
```python3 ~/Av1an/av1an.py -i big_buck_bunny_1080p_h264.mov -w 6 -v ' --end-usage=q --kf-max-dist=600 --cpu-used=6 --cq-level=42 --threads=4 ' -o bbbtest ```
Shorten it a little, also output will be always .mkv and .mkv will be added to output filename.
Workers not set fixed https://github.com/master-of-zen/Av1an/commit/3fb1b43cd55947cd78758615c9fb2f55e88474e4
:+1: 
If all ok - close issue

**Comment by veikk0** [comment]
Thank you, it works now.
