### ISSUE TITLE
[Feature request] More "stable" fps & ETA reporting

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#68]
As it is currently, the encoding speed fps and ETA can update very rapidly and vary wildly. At least for me, when using 12 workers, the ETA estimate isn't very useful because of this, as it fluctuates quickly between various values between 7 and 24 hours. It also updates at an inconsistent rate, somtimes multiple times a second, sometimes less than once a second.

I really have two suggestions:

* Have the estimate update at a constant rate, maybe once or twice a second
* Have the fps and ETA be some sort of an average accumulated over time, to make the values more stable. Maybe take into account the total average fps (total number of frames encoded divided by elapsed time) and use it with a more recent fps figure to calculate an average or a weighted average.

**Comment by veikk0** [comment]
Not sure if I should make a separate report for this, I can do that later if necessary.

Another thing that IMO would make the progress reporting better would be having separate progress reporting for the first and second passes, and having all the first pass processes either done or in-progress before starting any second pass work. From what I've observed, the fps reporting only takes second pass processes into account, so when some workers are doing first pass and others second pass, the reported fps is quite low. It also makes it more difficult to estimate a completion time. Separating first and second pass reporting would help with this.

**Comment by n9Mtq4** [comment]
The code as it is now already takes into account the first pass for fps and time remaining. I opened a PR to smooth the fps and ETA.
