### ISSUE TITLE
[Question] How to resize video while keeping target-quality when using SVT-AV1 codec

### ISSUE THREAD

**Issue by SandyRodgers-2017** [master-of-zen/Av1an#696]
So I have been trying to resize a video to 1052x1920 while using  SVT-AV1 codec and SVTENC encoder and having a target-quality set. I've been having a hard time of doing so. Each time I get an error. Could I get some help with them command or does target-quality not work when changing the file resolution?
`docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i 181.mp4 -e svt-av1 -v " --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300 " --target-quality 94 --vmaf-threads 8 --vmaf --probes 5 --ffmpeg " -vf scale=1052:1920 " -a " -c:a libopus -b:a 192k -ac 2 -map 0:a " -c mkvmerge --min-q 15 --max-q 45 -w 4 -o 181-SVT-AV1-2.mkv `

The errors I have been getting look like this:
Scene detection
  [00:00:04] [############################################################################################################################################################################################] 100% 415/415 (94.62 fps, eta 0s)
Queue: 2 Workers: 2 Passes: 1
Params: --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300
⠄ [00:01:06] [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/415 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'VMAF calculation failed:
Command: "ffmpeg" "-loglevel" "error" "-hide_banner" "-y" "-thread_queue_size" "1024" "-hide_banner" "-r" "60" "-i" ".9a1ae79/split/v_3000000.ivf" "-r" "60" "-i" "-" "-filter_complex" "[0:v]scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[distorted];[1:v]select=not(mod(n\\,4)),setpts=0.2500*PTS,scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[ref];[distorted][ref]libvmaf=log_fmt=\'json\':eof_action=endall:log_path=.9a1ae79/split/00000.json:n_threads=8" "-f" "null" "-"
Output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "[Parsed_libvmaf_6 @ 0x6d83e40] Width and height of input videos must be same.\n[Parsed_libvmaf_6 @ 0x6d83e40] Failed to configure input pad on Parsed_libvmaf_6\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #1:0\n" }', av1an-core/src/vmaf.rs:264:3
⠤ [00:01:09] [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/415 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'VMAF calculation failed:
Command: "ffmpeg" "-loglevel" "error" "-hide_banner" "-y" "-thread_queue_size" "1024" "-hide_banner" "-r" "60" "-i" ".9a1ae79/split/v_3000001.ivf" "-r" "60" "-i" "-" "-filter_complex" "[0:v]scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[distorted];[1:v]select=not(mod(n\\,4)),setpts=0.2500*PTS,scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[ref];[distorted][ref]libvmaf=log_fmt=\'json\':eof_action=endall:log_path=.9a1ae79/split/00001.json:n_threads=8" "-f" "null" "-"
Output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "[Parsed_libvmaf_6 @ 0x6cd2180] Width and height of input videos must be same.\n[Parsed_libvmaf_6 @ 0x6cd2180] Failed to configure input pad on Parsed_libvmaf_6\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #1:0\n" }', av1an-core/src/vmaf.rs:264:3
⠠ [00:01:09] [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/415 (0.00 fps, eta 0s)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/lib.rs:1697:21

If I remove target-quality and all of the vmaf options this error no longer comes up. Is this expected behavior? I assume so, but I've seen other commands online where target-quality was seemingly able to work with scale.

**Comment by master-of-zen** [comment]
Resolution doesn't match at target quality stage.
There is option to pass `--vmaf-filter` which passes it to vmaf filter that is run at target quality, you should pass same resizing/cropping that you used. but in `complex_fileter` format.

**Comment by SandyRodgers-2017** [comment]
thank you i'll try that

**Comment by SandyRodgers-2017** [comment]
I tried to use vmaf-filter and I still get these errors 
`docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i 167.mp4 -e svt-av1 -v " --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300 " --target-quality 94 --vmaf-threads 8 --vmaf --probes 5 --ffmpeg " -vf scale=1052:1920 " --vmaf-filter "[0:v]scale=1052:1920" -a " -c:a libopus -b:a 192k -ac 2 -map 0:a " -c mkvmerge --min-q 15 --max-q 45 -w 4 -o 167-SVT-AV1-2.mkv `
Scene detection
  [00:00:06] [############################################################################################################################################################################################] 100% 183/183 (26.17 fps, eta 0s)
Queue: 1 Workers: 1 Passes: 1
Params: --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300
⠤ [00:00:32] [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/183 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'VMAF calculation failed:
Command: "ffmpeg" "-loglevel" "error" "-hide_banner" "-y" "-thread_queue_size" "1024" "-hide_banner" "-r" "60" "-i" ".ed1b856/split/v_3000000.ivf" "-r" "60" "-i" "-" "-filter_complex" "[0:v]scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[distorted];[1:v]select=not(mod(n\\,4)),setpts=0.2500*PTS,[0:v]scale=1052:1920scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[ref];[distorted][ref]libvmaf=log_fmt=\'json\':eof_action=endall:log_path=.ed1b856/split/00000.json:n_threads=8" "-f" "null" "-"
Output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "[Parsed_scale_4 @ 0x5cbc8c0] Option '1920scale' not found\n[AVFilterGraph @ 0x5cb0c80] Error initializing filter 'scale' with args '1052:1920scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease'\nError initializing complex filters.\nOption not found\n" }', av1an-core/src/vmaf.rs:264:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/lib.rs:406:35
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/lib.rs:1697:21
I then tried another command,because maybe my formatting was wrong:

` docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i 167.mp4 -e svt-av1 -v " --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300 " --target-quality 94 --vmaf-threads 8 --vmaf --probes 5 --ffmpeg " -vf scale=1052:1920 " --vmaf-filter "scale=1052:1920" -a " -c:a libopus -b:a 192k -ac 2 -map 0:a " -c mkvmerge --min-q 15 --max-q 45 -w 4 -o 167-SVT-AV1-2.mkv `
I got the same error:
I then tried to just crop the video based on how the documentation said to do so: 
`docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i 167.mp4 -e svt-av1 -v " --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300 " --target-quality 94 --vmaf-threads 8 --vmaf --probes 5 --ffmpeg " -vf crop=200:1000:0:0 " --vmaf-filter "crop=200:1000:0:0" -a " -c:a libopus -b:a 192k -ac 2 -map 0:a " -c mkvmerge --min-q 15 --max-q 45 -w 4 -o 167-SVT-AV1-2.mkv `
This still gave me an error:

Scene detection
  [00:00:06] [############################################################################################################################################################################################] 100% 183/183 (25.70 fps, eta 0s)
Queue: 1 Workers: 1 Passes: 1
Params: --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300
⠒ [00:00:22] [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0% 0/183 (0.00 fps, eta 0s)
thread '<unnamed>' panicked at 'VMAF calculation failed:
Command: "ffmpeg" "-loglevel" "error" "-hide_banner" "-y" "-thread_queue_size" "1024" "-hide_banner" "-r" "60" "-i" ".ed1b856/split/v_3000000.ivf" "-r" "60" "-i" "-" "-filter_complex" "[0:v]scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[distorted];[1:v]select=not(mod(n\\,4)),setpts=0.2500*PTS,crop=200:1000:0:0scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease,setpts=PTS-STARTPTS[ref];[distorted][ref]libvmaf=log_fmt=\'json\':eof_action=endall:log_path=.ed1b856/split/00000.json:n_threads=8" "-f" "null" "-"
Output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "[Parsed_crop_4 @ 0x67c6dc0] Option '0scale' not found\n[AVFilterGraph @ 0x67b8e80] Error initializing filter 'crop' with args '200:1000:0:0scale=1920x1080:flags=bicubic:force_original_aspect_ratio=decrease'\nError initializing complex filters.\nOption not found\n" }', av1an-core/src/vmaf.rs:264:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/lib.rs:406:35
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/lib.rs:1697:21

I then added a comma to the crop command and that worked at least partially:

`docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i 167.mp4 -e svt-av1 -v " --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300 " --target-quality 94 --vmaf-threads 8 --vmaf --probes 5 --ffmpeg " -vf crop=200:1000:0:0 " --vmaf-filter "crop=200:1000:0:0," -a " -c:a libopus -b:a 192k -ac 2 -map 0:a " -c mkvmerge --min-q 15 --max-q 45 -w 4 -o 167-SVT-AV1-2.mkv `
Scene detection
  [00:00:06] [############################################################################################################################################################################################] 100% 183/183 (25.83 fps, eta 0s)
Queue: 1 Workers: 1 Passes: 1
Params: --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300
  [00:01:41] [#############################################################################################################################################################################################] 100% 183/183 (1.74 fps, eta 0s)
::VMAF Run..
thread 'main' panicked at 'VMAF calculation failed:
:"[Parsed_libvmaf_4 @ 0xfe95d40] Width and height of input videos must be same.\n[Parsed_libvmaf_4 @ 0xfe95d40] Failed to configure input pad on Parsed_libvmaf_4\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #1:0\n"', av1an-core/src/vmaf.rs:156:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I then tried this with the scale command and it worked partially as well:

`docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i 167.mp4 -e svt-av1 -v " --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300 " --target-quality 94 --vmaf-threads 8 --vmaf --probes 5 --ffmpeg " -vf scale=1052:1920 " --vmaf-filter "scale=1052:1920," -a " -c:a libopus -b:a 192k -ac 2 -map 0:a " -c mkvmerge --min-q 15 --max-q 45 -w 4 -o 167-SVT-AV1-2.mkv `

Scene detection
  [00:00:06] [############################################################################################################################################################################################] 100% 183/183 (26.12 fps, eta 0s)
Queue: 1 Workers: 1 Passes: 1
Params: --rc 0 --crf 22 --preset 6 --lookahead 120 --keyint 300
  [00:02:44] [#############################################################################################################################################################################################] 100% 183/183 (1.07 fps, eta 0s)
::VMAF Run..
thread 'main' panicked at 'VMAF calculation failed:
:"[Parsed_libvmaf_4 @ 0x771d440] Width and height of input videos must be same.\n[Parsed_libvmaf_4 @ 0x771d440] Failed to configure input pad on Parsed_libvmaf_4\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #1:0\n"', av1an-core/src/vmaf.rs:156:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

It seems that the issue  #326 still affects the docker av1an build.

**Comment by master-of-zen** [comment]
I can't find what exactly causing the issue, for now, i would recommend to use vapoursynth script as input, and have resize inside of it, here is example of script that worked for me.
Rename it to .vpy
[vs.txt](https://github.com/master-of-zen/Av1an/files/10365489/vs.txt)
Usage example `-i vs.vpy --target-quality 90 -o test.mkv`

**Comment by SandyRodgers-2017** [comment]
Thank you that did work for the most part vmaf plot still isn't being made, but overall it seemingly worked according to the logs. I may need to build my own docker container in order to get more up to date packages.
