### ISSUE TITLE
cython

### ISSUE THREAD

**Issue by dprestegard** [master-of-zen/Av1an#71]
Looks like this actually requires cython but that's not mentioned in the docs anywhere :)

**Comment by lastrosade** [comment]
It does not.

**Comment by dprestegard** [comment]
Hmm. Well, when I ran `python setup.pu install` it whined about cython not being available, and when I did `python -m pip install cython` and then retried, it worked...

**Comment by nathanielcwm** [comment]
I don't have cython installed in my system and I can use it just fine.
