### ISSUE TITLE
Update to ffmpeg 6

### ISSUE THREAD

**Issue by svenstaro** [master-of-zen/Av1an#728]
ffmpeg-the-third v1.2.0+ffmpeg-6.0.0 has gained support for ffmpeg 6. This is currently blocking a rebuild in Arch Linux. Can you update the deps to allow for ffmpeg 6?

**Comment by LastBreeze** [comment]
Workaround until this is resolved:
Uninstall lsmashsource
Install "downgrade" from the AUR.
Run "downgrade ffmpeg" and revert to the most recent ffmpeg 5.x
Reinstall lsmashsource
Compile av1an
