### ISSUE TITLE
Encoding failed (using default settings)

### ISSUE THREAD

**Issue by dprestegard** [master-of-zen/Av1an#73]
I'm trying a very simple execution to get familiar with this tool, but it fails to produce a valid output. This is on Windows, running in PowerShell, using Python 3.8.2.

`python C:\av1an\av1an.py -i .\ToS-4k-1920.mov -s scenes.csv -o defaults.mkv`
```
100%|███████████████████████████████████████████████████████████████████████| 17620/17620 [01:43<00:00, 170.12frames/s]
Queue: 119 Workers: 8 Passes: 2
Params: --threads=4 --cpu-used=6 --end-usage=q --cq-level=40
  0%|                                                                                        | 0/17620 [00:00<?, ?fr/s]Encoding failed, check validity of your encoding settings/commands and start again
Encoding failed, check validity of your encoding settings/commands and start again
Encoding failed, check validity of your encoding settings/commands and start again
Encoding failed, check validity of your encoding settings/commands and start again
Encoding failed, check validity of your encoding settings/commands and start again
  3%|██                                                                          | 466/17620 [02:41<7:22:17,  1.55s/fr]
```

After blowing up like this, it does continue to encode (I have 8 aomenc processes running).

What info can I provide to help investigate these errors?

**Comment by luigi311** [comment]
Can you try just
```powershell
python C:\av1an\av1an.py -i .\ToS-4k-1920.mov
```

**Comment by dprestegard** [comment]
Same results.

**Comment by luigi311** [comment]
I will try this locally and see if I can reproduce the same error. I do know that the check validity of your encoding settings error is new so it might have some issues.

**Comment by luigi311** [comment]
I am not receiving the same error. I recreated your structure by placing av1an in my C folder and it is still working as expected. Can you paste the output of ffmpeg -version

**Comment by luigi311** [comment]
Using the same ToS 4k mov file reproduces the error.

**Comment by dprestegard** [comment]
Interesting. I got the same results with a couple of inputs, including that ToS MOV and a 30 second y4m file.

**Comment by luigi311** [comment]
Using the ToS 4k mov even on my linux machine produces the same error so its something that is in the ToS video that is common with all your other y4m.

**Comment by luigi311** [comment]
While not ideal, creating a lossless x264 encode prior to feeding it into av1an does circumvent the issue if you want to try av1an now. The lossless encode can be created with 
```
ffmpeg -i ToS-4k-1920.mov -c:v libx264 -crf 0 ToS.mov
```
Just note the lossless encode file will be bigger than the source in this case, source 704 MB lossless 6.05 GB

**Comment by dprestegard** [comment]
Yeah I'm quite familiar with ffmpeg. Hmm.

It still seems odd that it's throwing those errors, considering ffmpeg is handling the decoding in every case. Is there any way to expose the exact command that's being run that throws that error so I can debug that?

**Comment by arankaren** [comment]
Also, when converting to vp9 I get the video without audio, what could it be? here are my logs

`python av1an.py -i "/home/karenl/Videos/myvideowithaudio.mkv" -enc vpx -a "-c:a copy" -log my_log`

```
12:30:28 Av1an Started
Command:
av1an.py -i /home/karenl/Videos/myvideowithaudio.mkv -enc vpx -a -c:a copy -log my_log
12:30:28 Starting scene detection Threshold: 50
12:30:30 Found scenes: 1
12:30:30 Encoding Queue Composed
Encoder: VPX Queue Size: 1 Passes: 2
Params: --codec=vp9 --threads=4 --cpu-used=1 --end-usage=q --cq-level=40
12:30:32 Enc: %05d.mkv, 176 fr

12:31:50 Done: %05d.mkv Fr: 176
Fps: 2.2287 Time: 78.97 sec.

12:31:50 Concatenated
```

**Comment by master-of-zen** [comment]
@arankaren by default audio is copied. So no need to set it explicitly, 
Also, it's recommended to put spaces around params. `-a " -c:a copy "`
Try this settings ` python av1an.py -i "/home/karenl/Videos/myvideowithaudio.mkv" -enc vpx -log my_log`

**Comment by arankaren** [comment]
> @arankaren by default audio is copied. So no need to set it explicitly.
> Also, it's recommended to put spaces around params. `-a " -c:a copy "`
> Try this settings ` python av1an.py -i "/home/karenl/Videos/myvideowithaudio.mkv" -enc vpx -log my_log`

Humm, default not work 🥺

Original file:

```
+ ---- [Issue 0]
|
| Type: Video
| Buffer Dimensions: 1920x1080
| Orientation: Top-Left
| Codec: H264 - MPEG-4 AVC (part 10) (avc1)
| Frame rate: 24,000384
| Video Resolution: 1920x1080
|
+ ---- [Issue 1]
|
| Bits per sample: 32
| Codec: Vorbis Audio (vorb)
| Type: Audio
| Sample rate: 44100 Hz
|
+ ---- [Meta data]
|
| DURATION: 00: 00: 07.260000000
| ENCODER: Lavf57.25.100
| filename: myvideowithaudio.mkv
|
```

Output file:

```
+ ---- [Issue 0]
|
| Video Resolution: 1920x1080
| Frame rate: 24,000384
| Codec: Google / On2's VP9 Video (VP90)
| Orientation: Top-Left
| Buffer Dimensions: 1920x1080
| English language
| Type: Video
|
+ ---- [Meta data]
|
| DURATION: 00: 00: 07.332000000
| ENCODER: Lavf57.71.100
| filename: myvideowithaudio_av1.mkv
```

my_log:
```
12:47:32 Av1an Started
Command:
av1an.py -i /home/karenl/Videos/myvideowithaudio.mkv -enc vpx -log my_log
12:47:32 Starting scene detection Threshold: 50
12:47:33 Found scenes: 1
12:47:33 Encoding Queue Composed
Encoder: VPX Queue Size: 1 Passes: 2
Params: --codec=vp9 --threads=4 --cpu-used=1 --end-usage=q --cq-level=40
12:47:35 Enc: %05d.mkv, 176 fr

12:48:53 Done: %05d.mkv Fr: 176
Fps: 2.244 Time: 78.43 sec.

12:48:53 Concatenated
```

**Comment by master-of-zen** [comment]
@arankaren update to latest git, the issue with audio is fixed)

**Comment by arankaren** [comment]
> @arankaren update to latest git, the issue with audio is fixed)
Yes, now it works!

**Comment by master-of-zen** [comment]
@arankaren sorry for the inconvenience, stable releases are on PIP, git is mostly WIP stuff :smile:
