### ISSUE TITLE
Copy mkv attachments to output file.

### ISSUE THREAD

**Issue by nathanielcwm** [master-of-zen/Av1an#74]
While by default it copies the audio and subtitles to the output file it doesn't copy the attachments. So subtitles that use a variety of fonts, that aren't installed onto the system, can look terrible due to the file and system lacking the fonts needed to properly display the subtitles.

**Comment by nathanielcwm** [comment]
Original:
![image](https://user-images.githubusercontent.com/22572406/82859121-748bc480-9f48-11ea-8055-3b90a822eff8.png)

av1an:
![image](https://user-images.githubusercontent.com/22572406/82859164-938a5680-9f48-11ea-9914-f2f1fc4bb8b3.png)

ffmpeg:
![image](https://user-images.githubusercontent.com/22572406/82859224-bae12380-9f48-11ea-9d24-764b1e9df296.png)

manually added by mkvtoolnix:
![image](https://user-images.githubusercontent.com/22572406/82859257-d0eee400-9f48-11ea-82e8-157cd8895563.png)

**Comment by nathanielcwm** [comment]
Strange I thought that with ffmpeg it would have been fine.

**Comment by nathanielcwm** [comment]
Looks like ffmpeg needs -map 0:t specified to copy attachments

**Comment by master-of-zen** [comment]
:+1:  that's why I don't answer to all issues instantly))
