### ISSUE TITLE
Provide some example commands for different encoders and their options in the wiki

### ISSUE THREAD

**Issue by Felixkruemel** [master-of-zen/Av1an#75]
Maybe it would be great to get some more examples in e.g. a wiki page.

Additionally a comparison speed wise between encoding only with ffmpeg and av1an would be great to have. I would also provide benchmarks if you want.

**Comment by master-of-zen** [comment]
@Felixkruemel for a better communication I recommend using Av1an discord server

**Comment by Felixkruemel** [comment]
I think I can close this issue now. The commands are pretty good documented in the readme.md
