### ISSUE TITLE
Build error: failed to verify the checksum of `const_fn_assert v0.1.2`

### ISSUE THREAD

**Issue by rokibhasansagar** [master-of-zen/Av1an#752]
Looks like the package `const_fn_assert` got deprecated just today.
Both `rav1e` and `av1an` build fails in `cargo fetch` stage with error related to checksum verification.
But if the checksum line is removed from the `Cargo.lock` file, it builds successfully.

The issue may also need to be raised in `rav1e` repository.

**Comment by rokibhasansagar** [comment]
Removing the checksum line is just my workaround. If there's a better way to fix this, please guide me.

**Comment by shssoichiro** [comment]
rav1e just removed the dependency, since it's no longer needed in recent rustc versions

**Comment by rokibhasansagar** [comment]
> rav1e just removed the dependency, since it's no longer needed in recent rustc versions

Av1an still have `const_fn_assert` in it's lockfile, so builds are likely to be failed if the lockfile is not updated..
What can I do right now to fix my builds, or are you going to update the codes with fixes?
Can simple `cargo update` fix the issue?

**Comment by shssoichiro** [comment]
We can't actually remove it on our end until rav1e publishes a new release, it looks like, although I'm also curious where/how you are encountering the issue? I am able to run `cargo build`, `cargo fetch`, etc without problem on my end, even after deleting the cargo cache on my machine.

**Comment by rokibhasansagar** [comment]
I'm building in **Arch Docker** with *AUR package: av1an-git* which fetches from latest git commit.
I was getting error in the time period between when the `const_fn_assert` rust package got deprecated and `rav1e` repo got updated.

I haven't tested a clean build after they fixed `rav1e` repository.
I'll test again to see if my error is resolved when they fixed the `rav1e` repository.

**Comment by rokibhasansagar** [comment]
I'm not using `cargo chef` method which was used in your `Dockerfile`.

In a clean environment inside `Arch Docker`, where there is no cargo cache available, and if the following command was used, build gives the mentioned error.
But if I replace `cargo fetch` with `cargo update`, it builds successfully.

```diff
git clone https://github.com/master-of-zen/Av1an
cd Av1an
- cargo fetch     # This fails
+ cargo update    # This works
cargo build --release
```
