### ISSUE TITLE
Encoding failed using aom

### ISSUE THREAD

**Issue by Felixkruemel** [master-of-zen/Av1an#76]
![grafik](https://user-images.githubusercontent.com/12109804/82832988-0b12a400-9ebd-11ea-8a05-423add318389.png)
Maybe it's my mistake, but I don't know what I did wrong in the command.
The source is encoded in x265 with 3 streams (video & 2 Audio streams) if that matters.

That's my command:
` av1an -i '.\test.mkv' -enc aom -v " --cq-level=35 " -ff " -map 0:0 -map 0:1 -map 0:2 " -a " -c:a copy " -log test.log -o test2.mkv`

And the log:

18:55:27 Starting scene detection Threshold: 50
19:12:18 Found scenes: 345
19:12:25 Audio processing
Params:  -c:a copy 
19:12:47 Encoding Queue Composed
Encoder: AOM Queue Size: 345 Passes: 2
Params:  --cq-level=35 
19:15:29 Started encoding queue with 8 workers

19:15:50 Enc:  00324.mkv, 4680 fr

19:15:50 Enc:  00154.mkv, 5064 fr

19:15:51 Enc:  00036.mkv, 5016 fr

19:15:53 Enc:  00149.mkv, 5760 fr

19:15:53 Enc:  00180.mkv, 5856 fr

19:16:13 Enc:  00319.mkv, 13584 fr

19:16:13 Enc:  00083.mkv, 10128 fr

19:16:17 Enc:  00344.mkv, 11664 fr

19:16:21 Enc:  00009.mkv, 4368 fr

19:16:29 Enc:  00186.mkv, 4248 fr

19:16:37 Enc:  00003.mkv, 3984 fr

19:16:46 Enc:  00276.mkv, 4248 fr

19:16:49 Enc:  00155.mkv, 4368 fr

19:16:57 Enc:  00325.mkv, 3216 fr

19:17:02 Enc:  00343.mkv, 3312 fr

19:17:04 Enc:  00027.mkv, 3648 fr

19:17:13 Enc:  00273.mkv, 3384 fr

19:17:14 Enc:  00113.mkv, 3096 fr

19:17:14 Enc:  00218.mkv, 3504 fr

19:17:16 Enc:  00139.mkv, 2952 fr

19:17:21 Enc:  00114.mkv, 2352 fr

19:17:24 Enc:  00268.mkv, 2088 fr

19:17:25 Enc:  00322.mkv, 3144 fr

19:17:33 Enc:  00320.mkv, 2112 fr

19:17:35 Enc:  00318.mkv, 2568 fr

19:17:37 Enc:  00338.mkv, 1848 fr

19:17:38 Enc:  00321.mkv, 2040 fr

19:17:40 Enc:  00257.mkv, 1536 fr

19:17:42 Enc:  00292.mkv, 1752 fr

19:17:42 Enc:  00096.mkv, 2040 fr

19:17:50 Enc:  00342.mkv, 1704 fr

19:17:50 Enc:  00143.mkv, 1776 fr

19:17:50 Enc:  00267.mkv, 1392 fr

19:17:51 Enc:  00202.mkv, 1416 fr

19:17:53 Enc:  00250.mkv, 1584 fr

19:17:53 Enc:  00236.mkv, 1248 fr

19:17:54 Enc:  00013.mkv, 1368 fr

19:18:00 Enc:  00253.mkv, 1392 fr

19:18:01 Enc:  00142.mkv, 1368 fr

19:18:01 Enc:  00296.mkv, 888 fr

19:18:01 Enc:  00140.mkv, 912 fr

19:18:02 Enc:  00293.mkv, 840 fr

19:18:03 Enc:  00134.mkv, 1008 fr

19:18:06 Enc:  00311.mkv, 1080 fr

19:18:07 Enc:  00275.mkv, 768 fr

19:18:09 Enc:  00126.mkv, 936 fr

19:18:10 Enc:  00308.mkv, 984 fr

19:18:10 Enc:  00018.mkv, 1032 fr

19:18:10 Enc:  00298.mkv, 864 fr

19:18:12 Enc:  00252.mkv, 960 fr

19:18:13 Enc:  00088.mkv, 792 fr

19:18:15 Enc:  00111.mkv, 864 fr

19:18:16 Enc:  00112.mkv, 840 fr

19:18:16 Enc:  00095.mkv, 744 fr

19:18:17 Enc:  00090.mkv, 744 fr

19:18:19 Enc:  00178.mkv, 768 fr

19:18:19 Enc:  00040.mkv, 768 fr

19:18:20 Enc:  00135.mkv, 648 fr

19:18:21 Enc:  00332.mkv, 816 fr

19:18:23 Enc:  00081.mkv, 552 fr

19:18:23 Enc:  00328.mkv, 480 fr

19:18:23 Enc:  00101.mkv, 576 fr

19:18:24 Enc:  00310.mkv, 696 fr

19:18:24 Enc:  00185.mkv, 480 fr

19:18:25 Enc:  00336.mkv, 456 fr

19:18:25 Enc:  00032.mkv, 624 fr

19:18:26 Enc:  00039.mkv, 504 fr

19:18:28 Enc:  00089.mkv, 504 fr

19:18:28 Enc:  00159.mkv, 384 fr

19:18:28 Enc:  00285.mkv, 432 fr

19:18:29 Enc:  00280.mkv, 480 fr

19:18:29 Enc:  00119.mkv, 576 fr

19:18:31 Enc:  00151.mkv, 384 fr

19:18:31 Enc:  00305.mkv, 360 fr

19:18:31 Enc:  00144.mkv, 432 fr

19:18:32 Enc:  00150.mkv, 360 fr

19:18:32 Enc:  00271.mkv, 336 fr

19:18:34 Enc:  00205.mkv, 360 fr

19:18:34 Enc:  00272.mkv, 384 fr

19:18:34 Enc:  00153.mkv, 552 fr

19:18:35 Enc:  00131.mkv, 336 fr

19:18:35 Enc:  00033.mkv, 360 fr

19:18:36 Enc:  00339.mkv, 432 fr

19:18:37 Enc:  00158.mkv, 336 fr

19:18:37 Enc:  00064.mkv, 456 fr

19:18:38 Enc:  00300.mkv, 360 fr

19:18:38 Enc:  00340.mkv, 408 fr

19:18:38 Enc:  00299.mkv, 456 fr

19:18:39 Enc:  00231.mkv, 360 fr

19:18:40 Enc:  00046.mkv, 288 fr

19:18:40 Enc:  00070.mkv, 360 fr

19:18:40 Enc:  00220.mkv, 408 fr

19:18:41 Enc:  00221.mkv, 360 fr

19:18:42 Enc:  00115.mkv, 288 fr

19:18:42 Enc:  00030.mkv, 264 fr

19:18:42 Enc:  00066.mkv, 288 fr

19:18:43 Enc:  00206.mkv, 288 fr

19:18:43 Enc:  00334.mkv, 240 fr

19:18:44 Enc:  00229.mkv, 312 fr

19:18:44 Enc:  00100.mkv, 312 fr

19:18:44 Enc:  00303.mkv, 240 fr

19:18:45 Enc:  00260.mkv, 264 fr

19:18:45 Enc:  00330.mkv, 288 fr

19:18:45 Enc:  00323.mkv, 240 fr

19:18:46 Enc:  00048.mkv, 288 fr

19:18:46 Enc:  00099.mkv, 264 fr

19:18:47 Enc:  00080.mkv, 216 fr

19:18:47 Enc:  00312.mkv, 336 fr

19:18:47 Enc:  00277.mkv, 240 fr

19:18:48 Enc:  00198.mkv, 312 fr

19:18:49 Enc:  00074.mkv, 264 fr

19:18:49 Enc:  00146.mkv, 288 fr

19:18:49 Enc:  00132.mkv, 216 fr

19:18:50 Enc:  00270.mkv, 216 fr

19:18:50 Enc:  00230.mkv, 264 fr

19:18:50 Enc:  00087.mkv, 312 fr

19:18:51 Enc:  00207.mkv, 336 fr

19:18:52 Enc:  00179.mkv, 192 fr

19:18:52 Enc:  00042.mkv, 240 fr

19:18:52 Enc:  00122.mkv, 264 fr

19:18:52 Enc:  00118.mkv, 216 fr

19:18:53 Enc:  00052.mkv, 264 fr

19:18:53 Enc:  00098.mkv, 216 fr

19:18:53 Enc:  00093.mkv, 192 fr

19:18:54 Enc:  00269.mkv, 168 fr

19:18:55 Enc:  00014.mkv, 264 fr

19:18:55 Enc:  00247.mkv, 192 fr

19:18:55 Enc:  00238.mkv, 216 fr

19:18:55 Enc:  00152.mkv, 240 fr

19:18:56 Enc:  00249.mkv, 192 fr

19:18:56 Enc:  00284.mkv, 240 fr

19:18:56 Enc:  00317.mkv, 216 fr

19:18:56 Enc:  00006.mkv, 192 fr

19:18:57 Enc:  00050.mkv, 192 fr

19:18:57 Enc:  00258.mkv, 240 fr

19:18:57 Enc:  00082.mkv, 168 fr

19:18:57 Enc:  00002.mkv, 216 fr

19:18:58 Enc:  00091.mkv, 144 fr

19:18:58 Enc:  00123.mkv, 240 fr

19:18:59 Enc:  00290.mkv, 192 fr

19:18:59 Enc:  00103.mkv, 144 fr

19:19:00 Enc:  00069.mkv, 144 fr

19:19:00 Enc:  00335.mkv, 144 fr

19:19:00 Enc:  00329.mkv, 168 fr

19:19:00 Enc:  00147.mkv, 216 fr

19:19:01 Enc:  00037.mkv, 144 fr

19:19:01 Enc:  00297.mkv, 168 fr

19:19:01 Enc:  00309.mkv, 144 fr

19:19:01 Enc:  00184.mkv, 144 fr

19:19:02 Enc:  00254.mkv, 168 fr

19:19:02 Enc:  00000.mkv, 168 fr

19:19:02 Enc:  00021.mkv, 168 fr

19:19:02 Enc:  00278.mkv, 168 fr

19:19:03 Enc:  00049.mkv, 168 fr

19:19:03 Enc:  00076.mkv, 192 fr

19:19:04 Enc:  00234.mkv, 144 fr

19:19:04 Enc:  00054.mkv, 144 fr

19:19:05 Enc:  00281.mkv, 144 fr

19:19:05 Enc:  00287.mkv, 168 fr

19:19:05 Enc:  00199.mkv, 168 fr

19:19:05 Enc:  00043.mkv, 168 fr

19:19:06 Enc:  00015.mkv, 216 fr

19:19:06 Enc:  00059.mkv, 168 fr

19:19:06 Enc:  00182.mkv, 120 fr

19:19:06 Enc:  00189.mkv, 144 fr

19:19:07 Enc:  00120.mkv, 168 fr

19:19:07 Enc:  00071.mkv, 120 fr

19:19:07 Enc:  00227.mkv, 192 fr

19:19:07 Enc:  00294.mkv, 120 fr

19:19:08 Enc:  00196.mkv, 144 fr

19:19:08 Enc:  00341.mkv, 120 fr

19:19:08 Enc:  00242.mkv, 144 fr

19:19:08 Enc:  00194.mkv, 120 fr

19:19:09 Enc:  00279.mkv, 120 fr

19:19:09 Enc:  00141.mkv, 144 fr

19:19:09 Enc:  00075.mkv, 168 fr

19:19:09 Enc:  00105.mkv, 96 fr

19:19:10 Enc:  00020.mkv, 120 fr

19:19:10 Enc:  00130.mkv, 96 fr

19:19:10 Enc:  00164.mkv, 96 fr

19:19:10 Enc:  00008.mkv, 120 fr

19:19:11 Enc:  00274.mkv, 144 fr

19:19:11 Enc:  00232.mkv, 120 fr

19:19:11 Enc:  00102.mkv, 96 fr

19:19:11 Enc:  00289.mkv, 120 fr

19:19:12 Enc:  00078.mkv, 144 fr

19:19:12 Enc:  00304.mkv, 192 fr

19:19:12 Enc:  00010.mkv, 120 fr

19:19:12 Enc:  00176.mkv, 96 fr

19:19:13 Enc:  00301.mkv, 96 fr

19:19:13 Enc:  00016.mkv, 144 fr

19:19:13 Enc:  00117.mkv, 96 fr

19:19:13 Enc:  00256.mkv, 120 fr

19:19:14 Enc:  00222.mkv, 144 fr

19:19:14 Enc:  00291.mkv, 96 fr

19:19:14 Enc:  00333.mkv, 96 fr

19:19:14 Enc:  00138.mkv, 120 fr

19:19:15 Enc:  00248.mkv, 96 fr

19:19:15 Enc:  00165.mkv, 96 fr

19:19:15 Enc:  00181.mkv, 96 fr

19:19:15 Enc:  00188.mkv, 96 fr

19:19:16 Enc:  00067.mkv, 120 fr

19:19:16 Enc:  00177.mkv, 96 fr

19:19:16 Enc:  00047.mkv, 96 fr

19:19:16 Enc:  00121.mkv, 120 fr

19:19:17 Enc:  00190.mkv, 96 fr

19:19:17 Enc:  00116.mkv, 120 fr

19:19:17 Enc:  00063.mkv, 72 fr

19:19:17 Enc:  00209.mkv, 144 fr

19:19:18 Enc:  00007.mkv, 72 fr

19:19:18 Enc:  00226.mkv, 120 fr

19:19:18 Enc:  00062.mkv, 120 fr

19:19:18 Enc:  00239.mkv, 96 fr

19:19:19 Enc:  00085.mkv, 96 fr

19:19:19 Enc:  00109.mkv, 72 fr

19:19:19 Enc:  00244.mkv, 72 fr

19:19:19 Enc:  00166.mkv, 72 fr

19:19:20 Enc:  00061.mkv, 72 fr

19:19:20 Enc:  00228.mkv, 96 fr

19:19:20 Enc:  00017.mkv, 120 fr

19:19:20 Enc:  00210.mkv, 168 fr

19:19:20 Enc:  00068.mkv, 72 fr

19:19:20 Enc:  00204.mkv, 72 fr

19:19:21 Enc:  00092.mkv, 72 fr

19:19:21 Enc:  00035.mkv, 72 fr

19:19:22 Enc:  00028.mkv, 96 fr

19:19:22 Enc:  00129.mkv, 72 fr

19:19:22 Enc:  00316.mkv, 96 fr

19:19:22 Enc:  00034.mkv, 120 fr

19:19:22 Enc:  00183.mkv, 72 fr

19:19:22 Enc:  00108.mkv, 72 fr

19:19:23 Enc:  00286.mkv, 72 fr

19:19:23 Enc:  00214.mkv, 120 fr

19:19:23 Enc:  00259.mkv, 72 fr

19:19:23 Enc:  00148.mkv, 72 fr

19:19:23 Enc:  00161.mkv, 72 fr

19:19:24 Enc:  00072.mkv, 72 fr

19:19:24 Enc:  00097.mkv, 72 fr

19:19:24 Enc:  00240.mkv, 72 fr

19:19:24 Enc:  00261.mkv, 72 fr

19:19:24 Enc:  00055.mkv, 72 fr

19:19:25 Enc:  00045.mkv, 72 fr

19:19:25 Enc:  00193.mkv, 96 fr

19:19:25 Enc:  00235.mkv, 72 fr

19:19:25 Enc:  00201.mkv, 72 fr

19:19:26 Enc:  00169.mkv, 48 fr

19:19:26 Enc:  00237.mkv, 72 fr

19:19:26 Enc:  00124.mkv, 72 fr

19:19:26 Enc:  00145.mkv, 72 fr

19:19:27 Enc:  00065.mkv, 48 fr

19:19:27 Enc:  00191.mkv, 72 fr

19:19:27 Enc:  00314.mkv, 72 fr

19:19:27 Enc:  00295.mkv, 48 fr

19:19:27 Enc:  00327.mkv, 48 fr

19:19:27 Enc:  00331.mkv, 72 fr

19:19:28 Enc:  00110.mkv, 48 fr

19:19:28 Enc:  00208.mkv, 120 fr

19:19:28 Enc:  00127.mkv, 48 fr

19:19:28 Enc:  00172.mkv, 48 fr

19:19:28 Enc:  00217.mkv, 96 fr

19:19:29 Enc:  00086.mkv, 72 fr

19:19:29 Enc:  00163.mkv, 72 fr

19:19:29 Enc:  00162.mkv, 48 fr

19:19:29 Enc:  00106.mkv, 48 fr

19:19:29 Enc:  00133.mkv, 48 fr

19:19:30 Enc:  00025.mkv, 48 fr

19:19:30 Enc:  00053.mkv, 48 fr

19:19:30 Enc:  00302.mkv, 48 fr

19:19:30 Enc:  00104.mkv, 48 fr

19:19:30 Enc:  00266.mkv, 72 fr

19:19:31 Enc:  00038.mkv, 48 fr

19:19:31 Enc:  00073.mkv, 72 fr

19:19:31 Enc:  00157.mkv, 48 fr

19:19:31 Enc:  00243.mkv, 48 fr

19:19:31 Enc:  00233.mkv, 48 fr

19:19:32 Enc:  00004.mkv, 72 fr

19:19:32 Enc:  00160.mkv, 48 fr

19:19:32 Enc:  00024.mkv, 48 fr

19:19:32 Enc:  00213.mkv, 96 fr

19:19:32 Enc:  00245.mkv, 48 fr

19:19:32 Enc:  00200.mkv, 72 fr

19:19:33 Enc:  00022.mkv, 48 fr

19:19:33 Enc:  00019.mkv, 48 fr

19:19:33 Enc:  00051.mkv, 48 fr

19:19:33 Enc:  00031.mkv, 48 fr

19:19:33 Enc:  00203.mkv, 48 fr

19:19:34 Enc:  00216.mkv, 72 fr

19:19:34 Enc:  00246.mkv, 48 fr

19:19:34 Enc:  00265.mkv, 48 fr

19:19:34 Enc:  00041.mkv, 48 fr

19:19:34 Enc:  00306.mkv, 48 fr

19:19:34 Enc:  00084.mkv, 48 fr

19:19:35 Enc:  00137.mkv, 48 fr

19:19:35 Enc:  00094.mkv, 48 fr

19:19:35 Enc:  00212.mkv, 72 fr

19:19:35 Enc:  00077.mkv, 48 fr

19:19:35 Enc:  00263.mkv, 48 fr

19:19:36 Enc:  00283.mkv, 48 fr

19:19:36 Enc:  00192.mkv, 48 fr

19:19:36 Enc:  00251.mkv, 48 fr

19:19:36 Enc:  00282.mkv, 48 fr

19:19:37 Enc:  00012.mkv, 48 fr

19:19:37 Enc:  00044.mkv, 48 fr

19:19:37 Enc:  00313.mkv, 48 fr

19:19:37 Enc:  00107.mkv, 24 fr

19:19:37 Enc:  00173.mkv, 24 fr

19:19:37 Enc:  00307.mkv, 24 fr

19:19:37 Enc:  00223.mkv, 48 fr

19:19:38 Enc:  00225.mkv, 48 fr

19:19:38 Enc:  00211.mkv, 72 fr

19:19:38 Enc:  00156.mkv, 24 fr

19:19:38 Enc:  00011.mkv, 48 fr

19:19:38 Enc:  00174.mkv, 24 fr

19:19:39 Enc:  00128.mkv, 24 fr

19:19:39 Enc:  00060.mkv, 24 fr

19:19:39 Enc:  00326.mkv, 24 fr

19:19:39 Enc:  00125.mkv, 48 fr

19:19:39 Enc:  00079.mkv, 24 fr

19:19:39 Enc:  00170.mkv, 24 fr

19:19:40 Enc:  00057.mkv, 48 fr

19:19:40 Enc:  00175.mkv, 24 fr

19:19:40 Enc:  00171.mkv, 24 fr

19:19:40 Enc:  00029.mkv, 24 fr

19:19:40 Enc:  00215.mkv, 48 fr

19:19:40 Enc:  00337.mkv, 24 fr

19:19:41 Enc:  00167.mkv, 24 fr

19:19:41 Enc:  00264.mkv, 24 fr

19:19:41 Enc:  00195.mkv, 24 fr

19:19:41 Enc:  00197.mkv, 24 fr

19:19:41 Enc:  00058.mkv, 24 fr

19:19:41 Enc:  00262.mkv, 24 fr

19:19:42 Enc:  00001.mkv, 24 fr

19:19:42 Enc:  00187.mkv, 24 fr

19:19:42 Enc:  00241.mkv, 24 fr

19:19:42 Enc:  00026.mkv, 24 fr

19:19:42 Enc:  00288.mkv, 24 fr

19:19:42 Enc:  00136.mkv, 24 fr

19:19:43 Enc:  00315.mkv, 24 fr

19:19:43 Enc:  00168.mkv, 24 fr

19:19:43 Enc:  00219.mkv, 24 fr

19:19:43 Enc:  00255.mkv, 24 fr

19:19:43 Enc:  00005.mkv, 48 fr

19:19:43 Enc:  00023.mkv, 24 fr

19:19:43 Enc:  00056.mkv, 24 fr

19:19:44 Enc:  00224.mkv, 24 fr

**Comment by master-of-zen** [comment]
`-enc aom`
AOM is default encoder, no need to set this explicitly 

`-log test.log`
.log always added to the end of the file, so with the current setting, it would look like test.log.log.
Proper: `-log test`

`-v " --cq-level=35 "`
Default encoding mode is target bitrate, and Q mode needs to be set explicitly using  ` --end-usage=q `. Also `--cpu-used=N` needs to be specified. So proper parameter would look something like (added threads for better multithreading):
`-v " --end-usage=q  --cq-level=35 --cpu-used=4 --threads=4 "`

-ff " -map 0:0 -map 0:1 -map 0:2 "
FF settings are passed to the encoder directly, after splitting is done. So this command is wrong as splits only carry video stream and audio processed separately. This line is breaking encode, for sure.

-a " -c:a copy "
Audio is copied by default if audio is don't need to be changed - no parameters for audio encoding should be passed 

-o test2.mkv
.mkv is always added to output file because it is consistent at muxing. so with this params, it would be `test2.mkv.mkv`

So final proper command would look like 
`av1an -i '.\test.mkv'  -v "  --end-usage=q  --cq-level=35 --cpu-used=4 --threads=4 " -log test -o test2`

Also would be nice to not copy paste 700 line log into issue page. Files can be attached to the comment :point_down: 
[file.txt](https://github.com/master-of-zen/Av1an/files/4678367/file.txt)

If your issue is solved, close it

**Comment by Felixkruemel** [comment]
@master-of-zen 
Nice thanks for the fast answer!
Seems to work now :)

**Comment by master-of-zen** [comment]
@Felixkruemel :+1:

**Comment by cryptobank** [comment]
Sorry for the resurrection of this issue, but I'm having the same problem and i'm at the end of my wits here. I'm on arch linux running av1an-git, aom-git and ffmpeg-git.

av1an --resume -i MuzHK.mkv -v " --end-usage=q --cq-level=24 --cpu-usage=4 " -log out -o MuzHKAV1
Queue: 187 Workers: 4 Passes: 2
Params: --end-usage=q --cq-level=24 --cpu-usage=4
  0%|                                                                                                                                                                                                              | 0/139284 [00:00<?, ?fr/s]Encoding failed, check validity of your encoding settings/commands and start again


Even with default parameters it fails

av1an --resume -i MuzHK.mkv -log out -o MuzHKAV1
Queue: 187 Workers: 4 Passes: 2
Params: --threads=4 --cpu-used=6 --end-usage=q --cq-level=40
  0%|                                                                                                                                                                                                              | 0/139284 [00:00<?, ?fr/s]Encoding failed, check validity of your encoding settings/commands and start again
Killed

ffmpeg
ffmpeg version N-98064-gd09c35677d Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3

**Comment by cryptobank** [comment]
worked it out. video was interlaced and had to pass -vf yadif to ffmpeg. it would be helpful if these errors get passed to client. Another issue seems to be the progress bar is stuck on 

av1an --resume -i MuzHK.mkv -v " --end-usage=q --cq-level=24 --cpu-used=4 " -ff " -vf yadif " -log out -o MuzHKAV1
Queue: 187 Workers: 4 Passes: 2
Params: --end-usage=q --cq-level=24 --cpu-used=4
  0%|
