### ISSUE TITLE
Av1an fails to render videos

### ISSUE THREAD

**Issue by JustSimplyKyle** [master-of-zen/Av1an#765]
https://c-v.sh/unsoldskidlids.txt
I'll spare you the details, but the main error is this.
`Fatal: Specify stream dimensions with --width (-w)  and --height (-h)`
if we do specify it, it turns out like this instead.
```bash
stderr:
        Failed to initialize encoder: Invalid parameter
            rc_twopass_stats_in requires at least two packets.
```
https://github.com/master-of-zen/Av1an/issues/212
according to this issue, I have tried doing
`av1an -i  PXL_20230610_063235501.TS.mp4_mkvmerge_fix.mkv_framerate_change.mkv -o arst.mkv --split-method none -x 0  -e x264 -m select` and it does in fact fix it
all things should be at the latest(except for av1an, I'm one commit behind)
```bash
❯ paru -Qi av1an-git
Name            : av1an-git
Version         : r2287.50f50d9-1
Description     : A cross-platform all-in-one tool for streamlining AV1 encoding
Architecture    : x86_64
URL             : https://github.com/master-of-zen/Av1an
Licenses        : GPL3
Groups          : None
Provides        : av1an
Depends On      : ffmpeg  aom  vapoursynth
Optional Deps   : svt-av1: SVT-AV1 encoder support [installed]
                  rav1e: rav1e encoder support [installed]
                  libvpx: vpx encoder support [installed]
                  vmaf: VMAF calculation support [installed]
                  mkvtoolnix-cli: mkvmerge support [installed]
                  ffms2 [installed]
                  vapoursynth-plugin-lsmashsource [installed]
```

**Comment by damian101** [comment]
Av1an seems to be incompatible with VapourSynth 62. A downgrade to version 61 got Av1an working for me again.

**Comment by JustSimplyKyle** [comment]
thanks for the workaround
got it working for me too!

**Comment by JustSimplyKyle** [comment]
Fixed in upstream(vapoursynth 63)
