### ISSUE TITLE
[Feature Request] Don't resplit a video file if it has been split before

### ISSUE THREAD

**Issue by Felixkruemel** [master-of-zen/Av1an#77]
Currently, if we set wrong encoding paramters we need to wait for the finished video splitting before we see an error. If we restart Av1an it starts again with splitting. 

Maybe an option to use the already slit files would be a good idea?

**Comment by n9Mtq4** [comment]
It already has this. Check out the `--scenes` option. You give it a file to write the split information to and if it doesn't exist it does the splitting and then records the splits for the next time.

**Comment by Felixkruemel** [comment]
@n9Mtq4 
Oh nice!
Then that solves the issue.
