### ISSUE TITLE
Vpxenc video desync issues.

### ISSUE THREAD

**Issue by jkkma** [master-of-zen/Av1an#772]
If you try to use vpxenc with av1an and the video is longer than two minutes the video will start synced but slowly desync with the audio. Using latest av1an on Windows 11.

**Comment by silverbacknet** [comment]
Would you be able to use the program MediaInfo to check the exact framerates of the original and encoded files? https://mediaarea.net/en/MediaInfo

**Comment by jkkma** [comment]
Hello @silverbacknet, thank you for replying. Ive checked with mediainfo and both videos show 50 fps as the target framerate, yet the desync on the encode remains. Ive possibly identified the issue though as the metadata of the encode somehow messing up FPS info, so i was recommended to remux the encode using mkvtoolnix and specifying the FPS there.
And yes, this seems to fix the encode.
So this might be a bug with libvpx itself and not av1an, but i dont know how to notify google devs of this, they dont seem to keep a standard github repo.
![Screenshot 2023-07-10 181036](https://github.com/master-of-zen/Av1an/assets/16640398/28abb88c-8c2c-4364-85f2-b13ed7c7bd2f)
![Screenshot 2023-07-10 175921](https://github.com/master-of-zen/Av1an/assets/16640398/0e87bf8d-61f0-41aa-ad1b-dc183c136ac5)

**Comment by master-of-zen** [comment]
Make sure that you use --lsmash encoding method

**Comment by jkkma** [comment]
Chunk generation method was set to lsmash and chunk merging method to mkvmerge.

**Comment by Simulping** [comment]
try using the "select" chunk method

**Comment by jkkma** [comment]
Tried it, still desynced. So far only remuxing and specifing FPS in mkvtoolnix worked.
