### ISSUE TITLE
Feature Request: Add option to split video equally

### ISSUE THREAD

**Issue by Provissy** [master-of-zen/Av1an#79]
Well, the _spirit_ of this application is to provide parallel encoding utilising scene detection. But sometimes when dealing a long video with limited CPU cores, equally splitting it by an interval is more efficient than cutting by scenes. Please consider add an option to do this, it also makes this application more versatile. Thank you.

**Comment by master-of-zen** [comment]
There is `-xs` option, that does that.
```
-xs  --extra_split      
Adding extra splits if frame distance beetween splits bigger than
given value. Split only on keyframes. Works with/without PySceneDetect
Example: 1000 frames video with single scene, 
-xs 200 will try to add splits at keyframes 
that closest to 200,400,600,800.```

**Comment by Provissy** [comment]
Oh! sorry, I didn't notice that help message in README.MD. Actually, when I was reviewing the code I cannot understand what `Number of frames after which make split` means... it looks quite confusing. 

Okay, that is what I want, but it requires user calculating frame intervals by themself, consider add a more convenient option like... _just split them into 4 pieces equally_?

**Comment by master-of-zen** [comment]
@Provissy extra splits synergize with scene detection, as it can affect only scenes longer than N, so you can set -xs 720 and it will try split only scenes that longer than 720 frames (30 seconds 24fps). 
Just make N splits is not a good way to make encode.

**Comment by Provissy** [comment]
> @Provissy extra splits synergize with scene detection, as it can affect only scenes longer than N, so you can set -xs 720 and it will try split only scenes that longer than 720 frames (30 seconds 24fps).
> Just make N splits is not a good way to make encode.

Yes, that is not ideal. But I don't think it's necessary to scene detect a long video(like a movie) and split into many chunks if user's cpu is less than 6 or 4 cores. 

The main purpose, I assume, for this software is to accelerate the encoding time since `aomenc` is too slow. But, for example, if splitting an one hour long video into four chunks, whether the splitted position is at a scene changing point or just where the interval hits does not make big difference. Not everyone is encoding with a 64 threads CPU and huge amount of RAM, but opposite - I think most people own a cpu with less than 8 cores with less than 16 GB of RAM. Since it's hard to guess how scene detection splits the video, it may result in additional encoding time if the detected scenes do not spread evenly.

**Comment by master-of-zen** [comment]
> Yes, that is not ideal. But I don't think it's necessary to scene detect a long video(like a movie) and split into many chunks if the user's CPU is less than 6 or 4 cores.
It allows the usage of lots of features and general flexibility. Stopping and resuming encode, so huge encode can be scheduled instead of running encode from start to end. Using scene based features like boost and target VMAF, etc
