### ISSUE TITLE
Using --target-quality forces --vmaf

### ISSUE THREAD

**Issue by luigi311** [master-of-zen/Av1an#790]
Seems like whenever you use target-quality it forces the vmaf that happens after encoding finishes. You can see the : : VMAF Run line at end after the encode has finished when i never added in the --vmaf flag.

**Comment by damian101** [comment]
Right, and using `--vmaf` by itself doesn't do anything anymore.
It has been an issue since at least half a year...

**Comment by carif** [comment]
Seems like this part of the code is the problem:
https://github.com/master-of-zen/Av1an/blob/db278e27729ddc2f99b358d72a0d5cb2a93b93b8/av1an-core/src/context.rs#L349

Assuming I understand it correctly, someone put the code of `--vmaf` and `--target-quality` under the setting for `--target-quality` .
