### ISSUE TITLE
Encoder rav1e not found

### ISSUE THREAD

**Issue by mayurzujo** [master-of-zen/Av1an#85]
i fetch issues on all encoder

**Comment by master-of-zen** [comment]
That's mean that encoder is can't be found by the program, because it's not reachable or not installed.
Try installing rav1e or making sure that rav1e can be called system-wide by adding executable to your path

**Comment by luigi311** [comment]
Rav1e can be located by av1an when it is reachable system-wide based on the last runs via github actions. This issue looks like it can be closed.
