### ISSUE TITLE
Scene detection performance regression

### ISSUE THREAD

**Issue by Uranite** [master-of-zen/Av1an#852]
Scene detection speed has a performance regression because of commit https://github.com/master-of-zen/Av1an/commit/5184c0504e7d7af9a2a564558d9bf0c9bfd0474d
This happens with any video (that I've ever tested at least)
This issue is especially worse on high bitrate video
How to reproduce:
1. Run a test encode on a video with av1an commit https://github.com/master-of-zen/Av1an/commit/5184c0504e7d7af9a2a564558d9bf0c9bfd0474d, the encoder or the encoder parameters doesn't matter because we're only comparing the scene detection speed. Here is an example command that I used, `av1an -i input.mkv -o output.mkv -e svt-av1`, you can cancel the encode afterward if the scene detection is done
2. Run a test encode on a video with av1an prior to commit https://github.com/master-of-zen/Av1an/commit/5184c0504e7d7af9a2a564558d9bf0c9bfd0474d. In this case I used av1an commit https://github.com/master-of-zen/Av1an/commit/a506a924f2c98dca7512eb0ba8daf0e68c51b42a
3. Compare the speed of the scene detection, and you can see that av1an commit https://github.com/master-of-zen/Av1an/commit/5184c0504e7d7af9a2a564558d9bf0c9bfd0474d is slower at scene detection

**Comment by trixoniisama** [comment]
Can you provide data?

**Comment by Uranite** [comment]
> Can you provide data?

On windows 11
command used: `av1an -i testpubg.mkv -o testpubg-av1.mkv -e svt-av1`
In a short 8 second test clip comprised of 501 frames, 60 fps 1080p video with average bitrate of 141 Mb/s
av1an commit https://github.com/master-of-zen/Av1an/commit/a506a924f2c98dca7512eb0ba8daf0e68c51b42a
![image](https://github.com/master-of-zen/Av1an/assets/62639703/5f791485-627e-4463-bbd4-320aff2e696f)
182 fps for the scene detection which took only 2 seconds

av1an commit https://github.com/master-of-zen/Av1an/commit/5184c0504e7d7af9a2a564558d9bf0c9bfd0474d
![image](https://github.com/master-of-zen/Av1an/assets/62639703/65b2253d-404f-4b02-b34a-ac1cfc17fa7b)
I got 28 fps for the scene detection which took 17 seconds

this is the test clip that i used
https://pixeldrain.com/u/96ND4jQt
if you're planning to test on windows you can grab the windows build for a506a9 here
https://github.com/Uranite/Av1an/actions/runs/9447421308

**Comment by redzic** [comment]
If I were to guess, the issue is almost certainly that decoder multi threading is not enabled with the new PR. I've faced a very similar issue with my project. With the libav* libraries, `thread_count` on the codec context should be set to 0 BEFORE calling `avcodec_open2()`.

**Comment by shssoichiro** [comment]
@redzic since you seem to know this better--the ffmpeg api requires setting a type of threading, either Frame or Slice. Is Slice the recommended, and safe to use for all decoding? Or is Frame better and/or safer?

**Comment by shssoichiro** [comment]
Never mind, I tested and the very clear winner seems to be Frame threading.

**Comment by shssoichiro** [comment]
Thanks @Uranite , please let us know if you are still seeing any issues after the latest patch
