### ISSUE TITLE
0.4.2 fails to build with Rust 1.80.0

### ISSUE THREAD

**Issue by getchoo** [master-of-zen/Av1an#863]
See https://github.com/rust-lang/rust/issues/127343 and https://github.com/time-rs/time/issues/681 for some background here

I help package av1an in [nixpkgs](https://github.com/NixOS/nixpkgs), and as we are updating to Rust 1.80.0 internally, we've come across build failures on 0.4.2. This was indirectly fixed in `master` with https://github.com/master-of-zen/Av1an/pull/845 when the `time` crate was bumped, but this has yet to make it in a stable release. Is there any ETA on a stable release with this dependency bumped?

Thanks for your time! 😄

**Comment by shssoichiro** [comment]
@master-of-zen Now that we've got the last set of bugfixes merged, it probably does make sense to publish a new version.

**Comment by getchoo** [comment]
0.4.3 has been released with the `time` crate bumped. Thanks!
