### ISSUE TITLE
Outdated av1an's crates.io release (github: 0.4.3 / crates.io: 0.4.1)

### ISSUE THREAD

**Issue by davidandreoletti** [master-of-zen/Av1an#870]
Hi,

Av1an's crates.io provides av1an 0.4.1 (1y old). Currently av1an 0.4.3 is not yet available.

Do you plan to push new releases on crates.io ?

Regards,

**Comment by Uranite** [comment]
Now crates.io has 0.4.3, you can safely close this issue
