### ISSUE TITLE
v0.4.3 is released yet master branch shows 0.4.1

### ISSUE THREAD

**Issue by davidandreoletti** [master-of-zen/Av1an#871]
Hi,

v0.4.3 has been released but master branch show the [current/next release will be 0.4.1](https://github.com/master-of-zen/Av1an/blob/6d2325d99cb38f53bb3f1c60dc5e1106d49735da/av1an/Cargo.toml#L3)

**Comment by Uranite** [comment]
I think you made your PR in the wrong repo

**Comment by davidandreoletti** [comment]
@Uranite Yes. This is fixed now with https://github.com/master-of-zen/Av1an/pull/872

**Comment by davidandreoletti** [comment]
https://github.com/master-of-zen/Av1an/commit/90fcd3b4eb4a9f2b9d025a73cbcf055f11707b19 bumped versions. Closing this issue.
