### ISSUE TITLE
x265 [WARN]: extra unused command arguments given 

### ISSUE THREAD

**Issue by joeyabouharb** [master-of-zen/Av1an#892]
looks like the latest x265 (version 4) return error:

```
ERROR [av1an_core::broker] [chunk 95] encoder failed 3 times, shutting down worker
ERROR [av1an_core::broker] [chunk 95] encoder crashed: exit status: 1
stdout:

stderr:
        x265 [warning]: extra unused command arguments given <->


source pipe stderr:

ffmpeg pipe stderr:
```

as mentioned in staxrip issue looks like the parameter --input is required. 
https://github.com/staxrip/staxrip/issues/1459

**Comment by shssoichiro** [comment]
Confirmed, I've started seeing this as well since upgrading to x265 version 4. I will try to create a patch ASAP.
