### ISSUE TITLE
[Feature request] add ffmpeg video filter options

### ISSUE THREAD

**Issue by utack** [master-of-zen/Av1an#9]
It would be nice to have ffmpeg video filter options (-vf) supported  
This way video can for example be cropped remove black bars.
Thank you for consideration

**Comment by master-of-zen** [comment]
Added -vf option. Usage is: ... -vf ' options ' ...
Usage example: [Screenshot](https://cdn.discordapp.com/attachments/665440744567472169/669231270399705088/Screenshot_20200121_192352.png)
Please test :)

**Comment by utack** [comment]
Works as expected, thank you
