### ISSUE TITLE
Progress not visible 

### ISSUE THREAD

**Issue by EdgeLord69-dev** [master-of-zen/Av1an#900]
Hey guys, i was encoding with av1an & i ran into this issue where i cannot see how much video has been encoded, the progress, but i could see it when i had started using av1an earlier. I can also confirm that the video was being encoded, since i saw my ram usage spike up
![image](https://github.com/user-attachments/assets/24a1c6df-68bb-4f07-ab3a-4ad0e4e46aa5)

**Comment by master-of-zen** [comment]
Av1an count only complete frames, so 1st pass and target quality probes are not counted towards it. Wait some time and it will go up

**Comment by arshlearn** [comment]
I am not using 2pass mode or target quality
